### ISSUE TITLE
async onShareAppMessage设置自定义标题无效

### ISSUE THREAD

**Issue by princescar** [wepyjs/wepy#101]
```javascript
	async onShareAppMessage() {
		const obj = await Promise.resolve({
			title: 'ok',
			desc: 'haha',
			path: '/pages/landing'
		})
		return obj
	}
```

分享出去是默认的小程序名称作为title.

**Comment by Gcaufy** [comment]
async 函数的返回值永远都是一个Promise， 并非`onShareAppMessage`的预期返回值 Object

**Comment by princescar** [comment]
这种情况下框架能否做处理，将Promise resolve的结果给真正的wx API？

**Comment by Gcaufy** [comment]
async本质上还是异步的，`onShareAppMessage`需要一个同步返回的Object，这种情况是不可能做到的。

**Comment by princescar** [comment]
有道理，看来只能把`onShareAppMessage`中要异步做的事，放在生命周期函数里提前做掉了
