### ISSUE TITLE
滚动一下页面才能渲染新页面

### ISSUE THREAD

**Issue by nnecec** [wepyjs/wepy#107]
比如进入详情页，是没有数据显示的，稍微往下滚动一下才会把详情页渲染出来。搜索也是一样的情况，输入关键字点搜索，已经发送请求了，但是页面没有变化，稍微滚动一下或者再点击搜索才能渲染结果列表。

**Comment by Gcaufy** [comment]
看看是不是异步请求中没有用$apply

**Comment by nnecec** [comment]
感谢@Gcaufy提示，已解决。
AppData里显示确实没有绑定上数据。
之前$apply调用放到onLoad里了，用错了。
放到await获取数据并绑定之后，执行this.$apply()绑定数据成功。
