### ISSUE TITLE
针对原生API进行优化的函数有哪些

### ISSUE THREAD

**Issue by pscj** [wepyjs/wepy#108]
我看doc里举的例子是getuserinfo，其它优化过的函数还有哪些，函数原型是什么样的 ，API文档里没找到，也没在代码里找到实现，请给点参考谢谢

**Comment by Gcaufy** [comment]
没有单独对原生函数作过优化。原生API函数文档请参考官方文档。
比如`wx.getUserInfo`这个API，在`wepy`中有一份拷贝，`wepy.getUserInfo`，但如果使用`this.use('promisefy')`后，`wepy.getUserInfo`由函数回调变成了promise函数。
其它API同理，除了一些原生的同步API如`xxxSync`之外。

**Comment by GeoffZhu** [comment]
```this.use('promisefy')``` 拼写错了，应该是promisify。 @Gcaufy
