### ISSUE TITLE
不支持moment.js locale

### ISSUE THREAD

**Issue by lilac** [wepyjs/wepy#114]
配置moment.js的語言無效，依然只輸出 英文。
```
import moment from 'moment';

    moment.locale('zh-cn');
```
檢查dist目錄，發現moment/locale下面的文件沒有被包含進來。也許與https://github.com/moment/moment/issues/1435 有關。也許只是wepy的配置問題。但不知如何在wepy項目中配置webpack，嘗試增加webpack.config.js無效。

**Comment by Gcaufy** [comment]
这样就可以了

```
import moment from 'moment'
import 'moment/locale/zh-cn'
```
