### ISSUE TITLE
关于编译时空格跟tab换行报错的问题

### ISSUE THREAD

**Issue by z448401921** [wepyjs/wepy#117]
您好，我在编译时只要js格式稍有不正确,比如空格不对，换行符不对，就会出现如下错误，请问该如何避免。
  35:3  error  Mixed spaces and tabs     no-mixed-spaces-and-tabs
  35:5  error  Unexpected tab character  no-tabs

**Comment by Gcaufy** [comment]
如果不希望使用`eslint`可以在`wepy.config.js`中把`eslint`改为false

如果使用`eslint` 请参考 http://eslint.cn/docs/user-guide/configuring 修改相应配置
