### ISSUE TITLE
当 wx:if 指令中出现 ‘>’ 时，xmldom 不能正常解析

### ISSUE THREAD

**Issue by brucx** [wepyjs/wepy#118]
例如：
```
<input focus wx:if="{{test > 0}}" @input="changeInput"  @confirm="search"  />
```
报错：
```
xmldom warning]        attribute "focus" missed value!! "focus" instead2!!
@#[line:6,col:5]
[xmldom error]  element parse error: Error: invalid attribute:@input
@#[line:6,col:5]
```

**Comment by Gcaufy** [comment]
经测试，报错并非由wx:if引起的，以下写法不会报错。
```
wx:if="{{test > 0}}"
```

上面的错误信息是说`attribute "focus" missed value!! "focus" instead2!!`

**Comment by Gcaufy** [comment]
修复了`attribute "focus" missed value!! "focus" instead2!!`的问题。

**Comment by Gcaufy** [comment]
在发新版本之间这里可以使用`computed`或者`wx:if="{{!!(test - 0)}}"`的这种方式暂时代替

**Comment by brucx** [comment]
我现在的 workaround 是改写成 <input focus @input="changeInput"  @confirm="search" wx:if="{{test > 0}}" />

**Comment by Gcaufy** [comment]
这样可以，正好避开的BUG
