### ISSUE TITLE
wept.cofig.js中的配置项可以具体介绍一下吗

### ISSUE THREAD

**Issue by webdzq** [wepyjs/wepy#121]
wept.cofig.js中的配置项可以具体介绍一下吗？我们工程都是使用的svn。我发现编译监控都有.svn文件的改动。很烦的。是否可以做文件夹过滤呢？

**Comment by Gcaufy** [comment]
是wepy.config.js么？
https://github.com/wepyjs/wepy/blob/master/packages/wepy-cli/templates/template/wepy.config.js

**Comment by Gcaufy** [comment]
有没明白的地方吗？如果没有那就关掉这个issue吧。
