### ISSUE TITLE
【新功能支持】能否考虑增加 bower 支持

### ISSUE THREAD

**Issue by kirozhao** [wepyjs/wepy#122]
能否考虑增加 bower 支持？

有些库没有提供 npm 的 node_modules 支持 （比如 https://github.com/tencentyun/wafer-client-sdk ）

**Comment by Gcaufy** [comment]
现在可以直接使用bower安装，然后用require处理相对路径。和他们的原来用法一样

**Comment by kirozhao** [comment]
好的，thx
