### ISSUE TITLE
当把一个组件放在最 template 最顶层的时候，会覆盖接下来所有的元素

### ISSUE THREAD

**Issue by THaGKI9** [wepyjs/wepy#123]
具体表现：
【正常情况】
![snipaste_20170504_120714](https://cloud.githubusercontent.com/assets/14999583/25690307/7dcff16c-30c2-11e7-83ea-48890155bd22.png)

【覆盖：第一个Panel能正常编译出来，第二个Panel直接消失】
![snipaste_20170504_120752](https://cloud.githubusercontent.com/assets/14999583/25690309/81abe994-30c2-11e7-8667-a7a5d4520e95.png)

我尝试着修复这个 bug，定位到了 wepy-cli\src\compile-template.js@465 这里，猜测是因为这个判断导致了这样子的bug，但是不清楚为何这里要做一个顶层元素的判断，还请 repo 主解答一下
![snipaste_20170504_120511](https://cloud.githubusercontent.com/assets/14999583/25690332/b173419a-30c2-11e7-8714-5cf9447c3195.png)

**Comment by Gcaufy** [comment]
因为在顶层就是components的情况下，编译会直接报错，最后为了fix这个问题加了这个判断。
如果顶层放两个components，那么`node.documentElement === com`还成立么？

**Comment by THaGKI9** [comment]
成立的。


```XML
<Panel/>
<Panel2/>
```
这样子的 source 传给 domParser 的时候，由于没有一个**唯一的顶层元素**，所以 parser 把 Panel 当成了顶层元素。

所以我想是不是可以在编译的时候，给 template 加一个顶层元素
```XML
<xml>
    <Panel/>
    <Panel2/>
</xml>
```
让其正常编译，在写入到 wxml 的时候再去掉这个顶层元素？

**Comment by Gcaufy** [comment]
xmldom在处理删除节点的时候比较麻烦，我暂时还没想到好的办法。这个问题后面我再调试一下看看。
你这边先暂且手动个个节点吧。

**Comment by Gcaufy** [comment]
发布的1.5.3 版本已修复这个问题
