### ISSUE TITLE
组件props默认值bug

### ISSUE THREAD

**Issue by CalvinHong** [wepyjs/wepy#13]
effect: 组件在没有传props时，props默认值会有误,所有prop的默认值变成第一个prop的默认值

导致的原因 :
      file：component.js
![wx20170109-165003](https://cloud.githubusercontent.com/assets/9970390/21761119/e18eeb0e-d68b-11e6-960a-377bddeef35b.png)

**Comment by Gcaufy** [comment]
好的，谢谢。

**Comment by Gcaufy** [comment]
修复了prop默认值的问题， 同时还修复了默认值和coerce同时存在的问题。

参见这里的测试用例：https://github.com/wepyjs/wepy/commit/9ce499199b41340200ef9bdf0dc2065f02301f94#diff-5fc79eeeb7cc6fec5fb1192b456620e2

**Comment by Gcaufy** [comment]
等发布1.3.10版本后再close此issue
