### ISSUE TITLE
创建video对象wepy.createVideoContext('myVideo')是出错

### ISSUE THREAD

**Issue by webdzq** [wepyjs/wepy#133]
在onReady函数中创建 wepy.createVideoContext是报错，求解决。参考官网demo中的video示例
onReady(res)

 {
      try {
        this.videoContext = wepy.createVideoContext('myVideo')
      } catch (e) {
        console.log(e.message)
      }
    }

**Comment by Gcaufy** [comment]
```
this.videoContext = wx.createVideoContext('myVideo')
```
先这样写就可以解决问题。
