### ISSUE TITLE
wepy new 的 demo 项目运行直接报错

### ISSUE THREAD

**Issue by baijunjie** [wepyjs/wepy#138]
![b5e39a67-8493-454d-aaa7-c2be53a61d84](https://cloud.githubusercontent.com/assets/7956480/26023867/7dc482ae-37f8-11e7-9406-39e7c9165b53.png)

**Comment by Gcaufy** [comment]
是不是没有关转ES6?

**Comment by baijunjie** [comment]
果然是这个问题，关闭就ok了

**Comment by baijunjie** [comment]
唯一的遗憾就是不能和  wept 搭配使用，也是由于这个原因，使用 wept 启动会报错，要是能够兼容就完美了

**Comment by Gcaufy** [comment]
很久之前我试过，好像是可以的
