### ISSUE TITLE
wx.createCanvasContext没有同步更新官方的api

### ISSUE THREAD

**Issue by CalvinHong** [wepyjs/wepy#14]
微信小程序更新之后，`wx.createCanvasContext`是同步操作，不再有success/fail回调,因此wepy封装的`wx.createCanvasContext`的promise版会因为找不到success属性报错:
![image](https://cloud.githubusercontent.com/assets/9970390/21761893/e47901f6-d690-11e6-9ef4-48cabe95f98c.png)

> PS:建议不要直接重写微信原有接口，另起名字，比如 `wx.getUserInfo --> wx.getUserInfoAsync` ，

**Comment by Gcaufy** [comment]
@hongbinfu 最初版本是重写API, 后来考虑到这里的问题，打算不重写wx.api然后以`wepy.request`来代替，但考虑到向下兼容就没有处理，后面找机会再更新 一下这个问题吧。
