### ISSUE TITLE
wepy.request问题，无法使用promise

### ISSUE THREAD

**Issue by milawoai** [wepyjs/wepy#140]
根据文档上的说明，wepy.request('xxxx').then((d) => console.log(d));
我将Index.wpy中的

wepy.request({
            url: 'https://www.madcoder.cn/tests/sleep.php?time=1&t=css&c=' + map[i] + '&i=' + i,
            success: function (d) {
              self.netrst += d.data + '.'
              self.$apply()
           }
          })

改成了：

         wepy.request('https://www.madcoder.cn/tests/sleep.php?time=1&t=css').then((d) => console.log(d));

结果报错，找不到 then函数：

Cannot read property 'then' of undefined;at "pages/index" page request function

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy/wiki/wepy%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8Promise
