### ISSUE TITLE
只要声明 async 函数编译就报错？

### ISSUE THREAD

**Issue by baijunjie** [wepyjs/wepy#141]
已经按照这里的说明设置过了，但还是不能使用 async 函数
https://github.com/wepyjs/wepy/wiki/wepy%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8async-await

![c3ae5f46-4742-4010-b7b1-c092d7ffac4c](https://cloud.githubusercontent.com/assets/7956480/26033506/80b46b6c-38e0-11e7-80fa-04937181471c.png)
![a3051176-e4d6-4f9a-ace6-9b24c547fca1](https://cloud.githubusercontent.com/assets/7956480/26033511/93f51758-38e0-11e7-842b-dfc2939b8c06.png)
![102bfa31-0534-4744-bb3b-ee5e52fc6f51](https://cloud.githubusercontent.com/assets/7956480/26033514/9fe49a5c-38e0-11e7-8a38-dccc616b6876.png)

**Comment by Gcaufy** [comment]
`acync` -> `async`
