### ISSUE TITLE
warning 阻塞页面加载？

### ISSUE THREAD

**Issue by Jimco** [wepyjs/wepy#143]
第一次进入页面的时候没有问题，后退然后第二次进入页面的时候报了几个 warning，同时页面会出现一段时间的白屏，可以明显感觉到比第一次进入的时候慢，log 截图如下：

> `Time span` 是我打上的时间戳，从 `pages/index/index` onHide 到 `pages/search/index` onLoad 的耗时

第一次加载：
![wechatimg5](https://cloud.githubusercontent.com/assets/1623161/26087335/c0fac44e-3a22-11e7-8278-8e65c38a3b5a.jpeg)

第二次加载：
![wechatimg6](https://cloud.githubusercontent.com/assets/1623161/26087349/d435f29a-3a22-11e7-9776-40985f65ee06.jpeg)

进入页面的耗时不能接受啊.. 这要怎么解决？

**Comment by Jimco** [comment]
debug 发现 `pages/index/index` 页面加载的组件数量和组件同步传值会导致第2次进入 `pages/search/index` 页面的时候阻塞渲染，出现白屏，目前我自己的解决方案是异步 fetch 到数据后 $broadcast 给各个组件，这个方案能感觉到页面加载有卡顿，但是还算能接受了，不知道是否有更优的解决方案？

**Comment by Gcaufy** [comment]
你参考上面的 commit 修改 `node_modules/wepy/base.js ` 试试，应该可以解决 Warning 的问题。

**Comment by liumin1128** [comment]
这个问题同样困扰了我很久，参考上面的方法已解决问题，现在打开页面速度正常。

**Comment by Jimco** [comment]
修改之后，warning 没了，加载白屏的问题解决，但是之前通过 `this.$wxapp.$app` 获取 app 实例的方法废掉了，so sad~ 目前还可以通过 `wepy.$instance` 取得实例（mark 给需要的同学），感谢 @Gcaufy

**Comment by Gcaufy** [comment]
@Jimco 也可以 `this.$root.$parent`

**Comment by Jimco** [comment]
@Gcaufy get !

**Comment by Gcaufy** [comment]
已发布1.5.5版本
