### ISSUE TITLE
怎么使用zanui呢

### ISSUE THREAD

**Issue by hyacinthus** [wepyjs/wepy#146]
抱歉，不知道这是不是个问题，我是个后端，在摸索前端玩，需要指导。

zanUI的说明是基于官方的结构的，用了wepy后不会引用zanUI了。

或者说用了wepy后能不能用 semantic-ui 之类的框架呢?

**Comment by Gcaufy** [comment]
参考这里：https://github.com/wepyjs/wepy-weui-demo

**Comment by hyacinthus** [comment]
太感动了，竟然现写了个 demo ，谢谢哈!

**Comment by Liqiankun** [comment]
@Gcaufy 但是用起来实在不太顺手

**Comment by ace-han** [comment]
@Gcaufy wepy 可支持原生 小程序第三方ui库的引用方式不，只带样式的组件现在可直接引用
但是对于那些带回调式的或者api类的组件就没办法引用了，又或者说有对应的插件完成这个引用不
谢谢
