### ISSUE TITLE
大神，有几点疑问

### ISSUE THREAD

**Issue by baijunjie** [wepyjs/wepy#153]
感觉这个框架很给力，开发过程还是很爽的，目前有几点疑问，希望大神给解答一下：
1）关于this绑定问题
app中定义的方法是不是没有做 this 绑定？
我在page中调用app中的方法，与app中直接调用的方法，this指向是不同的
例如：
```js
export default class extends wepy.app {
    onLaunch() {
        this.login(); // login中this指向的是 e 对象，$app 才是自己
    }
    login() {
        console.log(this);
    }
}

export default class User extends wepy.page {
    onLoad() {
        this.$parent.login(); // 这时，login中this指向的是 this.$parent，说明 app 中方法中的 this, 没有做绑定处理
    }
}
```

2) methods 中的方法好像不能和绑定数据一起用？
使用会报错，这种使用场景是否有其他办法可以满足?
例如：
```html
<template>
    <view wx:for="{{list}}">
        <view>{{moment(item.time)}}</view>
    </view>
</template>
<script>
import moment from 'moment'
export default class List extends wepy.page {
    methods = {
        moment(time) {
            return moment(time, 'YYYY.MM.DD').fromNow();
        }
    }
}
</script>
```

3) 计算属性 computed 是否可以支持 getter、setter?
4) app 中的 globalData 似乎没有实际意义，可以用任意命名的属性代替，因为它并不是全局直接共享的？

**Comment by Gcaufy** [comment]
1. 理论上app也是有this的，如果没有可能是个BUG，明天我测一下。
2. 用computed
3. 没有getter, setter， 不过可以考虑
4. 是的。

**Comment by baijunjie** [comment]
关于问题2，用computed，如果传参的话也会报错，目前我只能先将数据处理好再与，页面绑定了

**Comment by Gcaufy** [comment]
问题2 其实是filter 的用法 如： {{ item.time | moment }} 这一类就需要你先把数据处理好先，小程序本身就不直接这类语法。因此没有办法实现 。

**Comment by DarrenHou1993** [comment]
app上确实没有做this绑定呢。大神。麻烦看一下

**Comment by DarrenHou1993** [comment]
app确实没有做this绑定。 我也是更新了之后发现了问题

**Comment by Gcaufy** [comment]
对的。这个是已知问题。现在请避免使用app中的内容先。

**Comment by DarrenHou1993** [comment]
@Gcaufy 这个问题 以后回修复吗。或者现在有没有暂时能使用全局数据共享的解决方法。麻烦告诉一下。

**Comment by Gcaufy** [comment]
@DarrenHou1993 修复的commit已经提交了。下个版本就没有这个问题了。

**Comment by DarrenHou1993** [comment]
@Gcaufy 好的
