### ISSUE TITLE
实现vue中watch功能了吗？

### ISSUE THREAD

**Issue by webdzq** [wepyjs/wepy#155]
实现vue中watch功能了吗？比如:
watch={
abc:function(){}
}

**Comment by Gcaufy** [comment]
没有，暂不支持的

**Comment by mowenchuxin** [comment]
那就实现啊，还等什么？

**Comment by webdzq** [comment]
实现指令和filter功能了吗？（嘻嘻）加油！

**Comment by SoyMeng** [comment]
如果有watch功能的话，props传递复杂对象的问题也能解决了。

**Comment by wanghaixu** [comment]
期待中...

**Comment by Gcaufy** [comment]
已发布的`1.5.7`中已经支持了`watch`，可以体验测试。

**Comment by wanghaixu** [comment]
使用方式是和vue风格一致吗？
有相关文档吗？ 
更新挺快的，本来我结合compute的特性实现了对props，data的watch功能，不知道官方的使用方式如何

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy/blob/master/packages/wepy-cli/templates/template/src/components/counter.wpy#L48-L52

**Comment by wanghaixu** [comment]
实验可行，点赞。

**Comment by snow798** [comment]
1.5.7版本添加的watch功能在开发者工具上可以， 在真机上没有效果（iPhone）
