### ISSUE TITLE
文件尺寸大的问题

### ISSUE THREAD

**Issue by kainy** [wepyjs/wepy#16]
![image](https://cloud.githubusercontent.com/assets/470729/21808272/97e78efa-d77d-11e6-8d80-fe1f29a0bb75.png)

示例代码，打包压缩后就有近700k，这个有进一步压缩空间么，我看了下主要是 npm 目录占用空间多。

**Comment by Gcaufy** [comment]
wepy提示了压缩插件。压缩后npm目录压缩后只有170k， 示例的700多k可能是因为包含图片。正式版本将图片外链就好了。

目录npm过多主要因为引入了babel-runtime， 后面会考虑使用别的方案代替以进一步减少npm目录大小。

**Comment by kainy** [comment]
已经说明是“示例代码”，没有额外图片和代码，难道作者没亲自用开发者工具编译过么。

**Comment by Gcaufy** [comment]
有两份示例代码，并不知道你指的哪一份。

**Comment by Gcaufy** [comment]
刚去看了一下，wepy new 出来的示例代码也包含300kb的图片，主要是为了演示图片压缩的工具。所以你说的没有图片的示例我就不太清楚了。
