### ISSUE TITLE
使用wepy new project命令生成的项目运行出错

### ISSUE THREAD

**Issue by SoyMeng** [wepyjs/wepy#162]
异常信息:
```
app.js [sm]:34 Uncaught ReferenceError: regeneratorRuntime is not defined(anonymous function) @ app.js [sm]:34(anonymous function) @ app.js [sm]:43(anonymous function) @ app.js [sm]:52require @ WAService.js:8(anonymous function) @ app.js:162
base.js [sm]:134 Uncaught TypeError: Cannot read property '$pages' of undefined$createPage @ base.js [sm]:134(anonymous function) @ index.js:232require @ WAService.js:8(anonymous function) @ index.js:234
appservice:17 Fri May 26 2017 11:00:47 GMT+0800 (中国标准时间) page 编译错误
appservice:18  pages/index 出现脚本错误或者未正确调用 Page()(anonymous function) @ appservice:18
WAService.js:7 Fri May 26 2017 11:01:01 GMT+0800 (中国标准时间) Page route 错误
WAService.js:7 Page[pages/index] not found. May be caused by: 1. Forgot to add page route in app.json. 2. Invoking Page() in async task.
```

**Comment by Gcaufy** [comment]
昨天才测试过，你看看是不是ES6->ES5没关，或者是有依赖没安装成功之类的？

**Comment by lizhisheng** [comment]
@SoyMeng 关了es6-》es5之后重启项目 我已解决

**Comment by SoyMeng** [comment]
是这个问题

**Comment by brooksgod** [comment]
if(__wxRouteBegin) {
        console.group("Thu Sep 07 2017 22:09:28 GMT+0800 (CST) page 编译错误")
        console.error(` pages/index/index.js 出现脚本错误或者未正确调用 Page()`)
        console.groupEnd()

**Comment by brooksgod** [comment]
看了关闭了？还是报

**Comment by CYchenyan** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found)
appservice:1145 Fri Mar 16 2018 14:12:26 GMT+0800 (CST) page 编译错误
appservice:1146 pages/index.js 出现脚本错误或者未正确调用 Page()
console.error
(anonymous) @ appservice:1146
VM224:1 Fri Mar 16 2018 14:12:27 GMT+0800 (CST) 渲染层错误
VM224:2 Uncaught ReferenceError: wx is not defined

请问这个解决了吗？关了es6转es5，重启了项目，还是报错呢

**Comment by lihp2014** [comment]
在微信开发者工具里面关掉了es6转es5之后解决了楼主问题
![image](https://user-images.githubusercontent.com/6766825/49842056-11aa7a00-fdf5-11e8-9988-539c205429e5.png)

**Comment by Young1993** [comment]
更新之后需要删除缓存，多试几次
