### ISSUE TITLE
在<input/>的@input的回调中返回值无法替换输入框的内容

### ISSUE THREAD

**Issue by Atuna** [wepyjs/wepy#164]
```
// index.wepy
<style lang="less">
</style>

<template>
  <input @input="bindReplaceInput" placeholder="连续的两个1会变成2" />
</template>

<script>
import wepy from 'wepy'

export default class ProfileForm extends wepy.page {
  bindReplaceInput (e) {
    var value = e.detail.value
    var pos = e.detail.cursor
    if (pos !== -1) {
      var left = e.detail.value.slice(0, pos)
      pos = left.replace(/11/g, '2').length
    }
    console.log('trigger')
    return {
      value: value.replace(/11/g, '2'),
      cursor: pos
    }
  }
}
</script>
```
今天尝试将input组件里的值进行替换，按照官方的文档里的写法，却无法替换（11变成2）
但是console里有打印出“trigger”（证明回调有触发）。
当尝试将官方的[demo](https://mp.weixin.qq.com/debug/wxadoc/dev/component/input.html)里的js代码替换dist/index.js里编译后的代码，就可以触替换输入框里的内容。

请问这是一个bug吗？还是我的写法有问题？
希望有人可以指导一下，先谢谢了：）

**Comment by dlhandsome** [comment]
事件的方法要放在methods里:
```javascript
methods = {
    bindReplaceInput (e) {
        // ...
   }
}
```

**Comment by Atuna** [comment]
谢谢，按照你修改已经解决问题。
可是我还有一些疑问，希望能帮助解答。之前我在使用<map>原生组件的@markertap事件的回调函数需要写在methods外面。我参考了[这部分的源码](https://github.com/dolymood/wepy/commit/ca4b9e7eb7fe75a65b4b9ffc69ed3d89d6cf2646#diff-f97d79274e80de6bf3826886d1585f0f)，根据我的理解，如果是原生的组件(isKnowTag)就会用bind的prefix而不是vue的v-on。而input是包含在knowTags里的，所以照理<input>的@input的事件回调来说应该是和<map>的@markertap的一样不应该放在methods里面的。
还望指导，谢谢。

**Comment by Atuna** [comment]
谢谢，按照你的修改已经解决问题。
