### ISSUE TITLE
window7下，npm run dev 

### ISSUE THREAD

**Issue by wuchuguang** [wepyjs/wepy#165]
随便改了一下文件，就一直写入，编译，没停止。用webstorm最新版来改代码的。之前开发nodejs时，nodemon会一直监听到文件改变的情况（事实我没改动），想问一下，wepy是不是nodemon来做的？

**Comment by Gcaufy** [comment]
不是，具体的可以看代码。

**Comment by wuchuguang** [comment]
我用Egret Wing全新创建 个小程序，也会发生这问题，好像是小程序web开发工具昨晚刚升级了，的原因。有向小程序官方提交个单了。再看看。
