### ISSUE TITLE
编译就报这个信息

### ISSUE THREAD

**Issue by kxrz123** [wepyjs/wepy#166]
![image](https://cloud.githubusercontent.com/assets/14868398/26519347/43355d0c-42f2-11e7-9933-527b02b6eddf.png)

**Comment by Gcaufy** [comment]
这是一个Warning
看起来像是你写了一个`bindtap="communicate“`方法，但这个方法没在 page 中申明

**Comment by kxrz123** [comment]
我是按照你们的教程操作的。什么都没有改动过。

**Comment by Gcaufy** [comment]
我刚从头到尾测试了一遍，并不存在这个问题，你检查一下dist下生成的文件， 这个 communicate 有没有问题先。

**Comment by kxrz123** [comment]
我有从头重新编译了一遍。现在对了。谢谢
