### ISSUE TITLE
Uncaught Error: module "npm/wepy-async-function/index.js" is not defined

### ISSUE THREAD

**Issue by hyacinthus** [wepyjs/wepy#169]
后端刚开始学前端的小白又来提问啦，现在为什么只要  import 'wepy-async-function'
build后微信开发工具就报这个错：
Uncaught Error: module "npm/wepy-async-function/index.js" is not defined

包也装了  this.use('promisify') 也用了，还有哪里不对啊？

我去dist看了下 npm/wepy-async-function 下只有个 global.js

**Comment by hyacinthus** [comment]
node --verson

7.10.0

**Comment by hyacinthus** [comment]
抱歉，我找到原因了，我用淘宝源就会有问题。 貌似淘宝的源不够同步。
换yarn就好了。

**Comment by Jialufeng** [comment]
yarn add install 
done!
