### ISSUE TITLE
wepy.component的生命周期钩子没有吗？

### ISSUE THREAD

**Issue by wanghaixu** [wepyjs/wepy#176]
有时需要用到组件的生命周期钩子，类似vue的。
目前只有onLoad可用

**Comment by Gcaufy** [comment]
因为组件这里的生命周期并不完善，只能继承page的生命周期，并没有一些类似于destroy之类的生命周期，所以就没有考虑组件的生命周期钩子，不过这里暂时先用mixin 去实现。

**Comment by cytle** [comment]
@Gcaufy 组件构造函数是在执行Page方法的时候，还是在onLoad后？？如果想在组件“挂载”时执行一些语句该怎么做

**Comment by Gcaufy** [comment]
组件构造函数是在最开始JS的加载运行阶段。在onLoad之前。

**Comment by CoderPoet** [comment]
@Gcaufy 请问组件没有销毁的生命周期钩子吗？比如我想在组件销毁的时候清除定时器，应该怎么处理？
