### ISSUE TITLE
wepy编译的时候npm包不会生成

### ISSUE THREAD

**Issue by xiaofeiapis** [wepyjs/wepy#18]
wepy build # 的时候，dist目录的npm包如果删除掉了，这时候不会重新打包生成npm文件夹

**Comment by Gcaufy** [comment]
npm经过编译后会生成cache，这样才不会每次编译npm。
如果删除npm后，请使用`wepy build --no-cache`。这样就可以再次编译npm包。

**Comment by xiaofeiapis** [comment]
可以了多谢
