### ISSUE TITLE
this的绑定问题

### ISSUE THREAD

**Issue by wanghaixu** [wepyjs/wepy#180]
```
// 情况1： 在生命周期钩子函数中无法通过this.XX调用methods中的函数
{
  methods = {
    test() {   console.log(123)  };
  }
  onShow() {
    this.test();    // undefined
  }
}
// 情况2： 通过this.methods.XX访问函数时，函数中的this指向methods
{
  methods = {
    test() {   console.log( this )  };  // this -> methods
  }
  onShow() {
    this.methods.test();    // { test: function }
  }
}

```
目前我的调用方法是this.methods.test().call( this );
 或者在onLoad钩子中把methods中的方法设置为page实例的全局函数，就可以通过this.XX的方式调用
 不知有没有更优雅的方式，或者其他地方也会有this的指向问题（相对于Vue使用习惯）。

**Comment by Gcaufy** [comment]
`onShow` 中是肯定可以调用 `methods` 中的 test 方法的。参考文档中的示例。或者是生成的DEMO项目。

**Comment by wanghaixu** [comment]
在生成的demo项目中，没发现有生命周期钩子调用methods中的函数的例子，我都是在这个demo的基础上进行测试官方API的兼容性的。
实际情况就是生命周期钩子中无法通过this.[methods中的方法名]来调用，而DOM的绑定事件就可以调用到。
这就产生了一种疑惑：在methods的函数中使用this,有可能指wepy.page的实例，也可能指向wepy.page的实例的methods

**Comment by wanghaixu** [comment]
我在生成的demo中，pages/index.wpy加入打印代码，可以测试到
```
onShow() {
      console.log(this.plus)
}
```

**Comment by Gcaufy** [comment]
sorry， 我理解错了。这里和 vue不一样的是，在Vue中，所有的方法和事件都写在methods中。 但在WePY中，methods中只会去写事件，如果是自定义方法那么就需要定义在 onShow 同一层。事件是指bindtap一类的响应事件。这里的规范是，自定义方法不充许直接调用事件，事件中可以调用自定义方法。

所以在你的实例中， 如果 test 是页面响应事件，那就在写methods中， 而且 逻辑代码中不应该直接调用页面响应事件，代码应该是这样的
```
methods = {
   tap () {
       console.log('button tapped');
       this.doSomething();
   }
}
onLoad () {
   this.doSomething();
};

doSomething () {
    console.log('do something');
}

**Comment by wanghaixu** [comment]
的确是被误导了。-_-

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy/issues/221

**Comment by Realybig** [comment]
刷新当前页面可以在方法中调用this.onLoad()吗?
