### ISSUE TITLE
page上config的navigationBarTitleText，无法在onLoad上改吧？

### ISSUE THREAD

**Issue by wuchuguang** [wepyjs/wepy#181]
onLoad () {
      this.config.navigationBarTitleText = "新的title"
      console.log(this)
      this.$apply()
    }

**Comment by Gcaufy** [comment]
config 无法被修改， 必须 使用wx提供的api去修改barTitleText

**Comment by wuchuguang** [comment]
最近忙其它事了，刚来
在onLoad里，可以通过什么this.xxx来获取wx这个原生api呢？
