### ISSUE TITLE
使用 lang="pug" 时，props 传值不生效

### ISSUE THREAD

**Issue by wulunyi** [wepyjs/wepy#186]
当使用 template 默认 lang 时
```
<template>
<view>
    <child :prop="list"/>
</view>
</template>
``` 
子组件能正常接收到 prop 在 child 中使用 this.prop 能获取到值

当使用 template lang="pug"
```
<template>
view
    child(:prop="list")
</template>
``` 
子组件无法接收到 prop this.prop 为 undefined
对比了下生成的 dist 发现少了类似如下的代码片段
```
_this.$props = { "ProductList": { "v-bind:prop.once": "list" } }, _this.$events = {},
```

**Comment by Gcaufy** [comment]
已修复，可以参看上述commit修改本地cli代码或者等待新版本发布修复这个问题。

**Comment by Gcaufy** [comment]
已发布，请升级cli看看这个问题是否还存在。
