### ISSUE TITLE
在wepy如何调用原生api

### ISSUE THREAD

**Issue by wuchuguang** [wepyjs/wepy#188]
如：
wx.onSocketOpen
wx.chooseImage
wx.playVoice
wx.onBackgroundAudioP

**Comment by Gcaufy** [comment]
可以使用`wepy.xxxx`或者是`wx.xxxx`。

**Comment by wuchuguang** [comment]
谢谢。

**Comment by Liqiankun** [comment]
@wuchuguang 你选择照片后怎么显示的？
