### ISSUE TITLE
微信小程序审核坑如何踩过

### ISSUE THREAD

**Issue by wuxinlai** [wepyjs/wepy#189]
1:小程序可用性和完整性不符合规则:
(1):进入小程序，页面报错提示：服务不可用，请稍候重试（wx.request fail）（wifi， Android5.1.1，微信6.5.8，OPPO R9 PlustmA ）
如有疑问，请查看详情与反馈。
针对这类兼容性问题怎么解决！！！谢谢

**Comment by SoyMeng** [comment]
再提交可能就过了，之前也发生过这种情况

**Comment by Gcaufy** [comment]
这个是小程序本身的问题吧。
