### ISSUE TITLE
wx.request基于IOS8下报错，官方的正常解析

### ISSUE THREAD

**Issue by myjf007** [wepyjs/wepy#19]
![qq 20170112174542](https://cloud.githubusercontent.com/assets/16434947/21884593/f3b62080-d8ee-11e6-9994-eed82bc41a9f.png)

**Comment by Phlen** [comment]
我也遇到，然后用回官方的好像不支持呢...接口申请成功了，request success 但没有触发success回调

**Comment by hugh87** [comment]
遇到同样的问题。ios 10.0.1、10.0.2 也遇到。

**Comment by Gcaufy** [comment]
请问还有碰到这个问题吗？如果没有我就关闭这个ISSUE了。
