### ISSUE TITLE
repeat有时候会直接报错，有时候又不会

### ISSUE THREAD

**Issue by ohYobbo** [wepyjs/wepy#191]
<repeat for="{{recommendData.list_item_recommend}}" item="item" wx:key="id">
                <view class="recommend-block" bindtap="clickProduct" data-id="{{item.item_id}}">
                  <image class="head-img" src="{{item['item_imgurl']+'?imageView2/5/w/320/h/320'}}" mode="aspectFit"></image>
                  <view class="recommend-middle">
                      <tips :text="item.tag_img_id"></tips>
                      <text class="brand-line">{{item.brand}}\n</text>
                      <text class="name-line">{{item.sell_point}}\n</text>
                      <view class="price-view">
                        <text class="{{item.price != item.ori_price ? 'price-line' : 'price-line-none'}}">¥{{item['price']}}</text>
                        <text class="oriprice-line" wx:if="{{item['price'] != item['ori_price']}}"> ¥{{item['ori_price']}}</text>
                        <view class="triangle"></view>
                      </view>
                  </view>
                </view>
            </repeat>
  同样的代码，有时候跑起来就会直接报错
<img width="788" alt="wx20170613-122324 2x" src="https://user-images.githubusercontent.com/18694546/27065945-296160c6-5033-11e7-8226-6ddfceb66e4d.png">

  有时候又是正常的，是repeat标签的问题么？

**Comment by Gcaufy** [comment]
把你定义的props 贴出来。

**Comment by ohYobbo** [comment]
<img width="394" alt="wx20170613-143656 2x" src="https://user-images.githubusercontent.com/18694546/27069101-cb6b755c-5045-11e7-8139-e08ee42e3496.png">

**Comment by ohYobbo** [comment]
包含这段repeat代码本身也是组件，相当于组件里面嵌套了循环组价tips

**Comment by Gcaufy** [comment]
这里不对吧，参看一下文档这里是怎么写的。
