### ISSUE TITLE
style标签的lang使用scss报错

### ISSUE THREAD

**Issue by tansj526** [wepyjs/wepy#192]
style标签的lang使用scss报错，内部编译的规则还是以sass来的，希望作者修复下，谢谢。

 3:9  error  Parsing error: Unexpected token, expected }

 1 | <style lang="scss">
 2 | .container {
 3 |   height: 100%;
   |         ^
 4 |   display: flex;
 5 |   flex-direction: column;
 6 |   align-items: center;

 1 problem (1 error, 0 warnings)

**Comment by Gcaufy** [comment]
刚测试了并没有发现问题，可以把你的SCSS代码贴出来么？

**Comment by tansj526** [comment]
那就很奇怪了，我还没自己写代码，只是用的模板里面的代码，就这一段就报错了
<style lang="scss">
.container {
  height: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: space-between;
  box-sizing: border-box;
}
</style>

**Comment by tansj526** [comment]
那就很奇怪了，我还没自己写代码，只是用的模板里面的代码，就这一段就报错了
<style lang="scss"> .container { height: 100%; display: flex; flex-direction: column; align-items: center; justify-content: space-between; box-sizing: border-box; } </style>
配置文件是这样的
module.exports = {
  wpyExt: '.wpy',
  eslint: true,
  compilers: {
    /*less: {
      compress: true
    },*/
    sass: {
      outputStyle: 'compressed'
    },
    babel: {
      sourceMap: true,
      presets: [
        'es2015',
        'stage-1'
      ],
      plugins: [
        'transform-decorators-legacy',
        'transform-export-extensions',
        'syntax-export-extensions'
      ]
    }
  },
  plugins: {
  }
}

**Comment by Gcaufy** [comment]
我拷贝了这一份代码测试是没有问题的。

**Comment by tansj526** [comment]
你好，配置文件要改动吗

**Comment by Gcaufy** [comment]
上面的配置文件是OK的，我在new出来的demo中，也是把less注释掉，把sass打开，然后把你的代码拷贝进index.wpy去测试的。

**Comment by tansj526** [comment]
你的是哪个版本的，我是1.5.6版本的

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy-wechat-demo/blob/master/src/pages/index.wpy

**Comment by Gcaufy** [comment]
你看一下这个Demo能编译了吗？

**Comment by tansj526** [comment]
谢谢，我找到原因了，我为了编辑器不报语法错误，我把.eslintrc.js里面的代码删除了，所以编译的时候报语法错误，但是可以编译成功的，我恢复.eslintrc.js配置就可以了
