### ISSUE TITLE
进入页面后再点击返回再进入，发现data中的数据是上一次进入后修改的值

### ISSUE THREAD

**Issue by wulunyi** [wepyjs/wepy#195]
页面卸载后数据被缓存了，重新进入数据是上一次进入修改后的值

**Comment by wulunyi** [comment]
```
//page A
...
data = {
  pageEnd: fase
}

onLoad() {
  //...
  console.log(this.pageEnd)
  this.getDetail()
}

getDetail() {
  this.pageEnd = true;
  this.$apply();
}
...
```
第一次进入 打印出 false
点击左上角返回按钮，然后再进入 A 页面 打印出 true

**Comment by Gcaufy** [comment]
这个是小程序的特性，并不是框架所赋予的特性。
这时候需要在unload事件中重新清除数据。

**Comment by wulunyi** [comment]
ok 正是使用这种方式做了重置

**Comment by gongzili456** [comment]
亲测使用原生方式并没有这种现象, 严重怀疑是框架的问题; 再者, 在unload方法中重置数据这种方式极不优雅.

**Comment by Gcaufy** [comment]
@gongzili456 之前测试过，原生一样存在同样的问题，根小程序的机制有关。并非框架做了什么我特殊处理。
