### ISSUE TITLE
wepy-config有类似webpack.DefinePlugin的插件么？

### ISSUE THREAD

**Issue by whiskyoo** [wepyjs/wepy#196]
希望在发版的时候可以build出不同环境的版本
```
// config.js
const host = process.env.NODE_ENV === 'production' ?
   'https://prod.xxx.com' :
   'https://dev.xxx.com';
......
......
......
```
或者有其它更好的方式，可以共享一下~~

**Comment by Gcaufy** [comment]
`DefinePlugin`可以考虑，但现在可以通过 replace 插件去实现。

```
if (process.env.NODE_ENV === 'production') {
module.exports.plugins = {
    'replace': {
        filter: /.*\.js$/,
        config: {
            find: /$$HOST/g,
            replace: function (matchs, word) {
                return 'https://prod.xxx.com";
            }
        }
    }
};
}
```

**Comment by whiskyoo** [comment]
good，thx~~

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy/issues/231

**Comment by ystarlongzi** [comment]
@Gcaufy 
`wepy-plugin-replace` 是在 `wepy` 编译后才进执行的，然后如果想在编译前根据环境变量替换 `.wpy` 文件里的 `config` 属性时，就做不到啦🤣，因为在 `wepy` 在编译后，已经提取 `config` 属性，生成对应的 .json 文件了

和这个 issue #400 有一点类似，就是希望在 `wepy` 能暴露出类似 `beforeCompile` 的钩子，然后在允许开发者在编译前可以进行一些操作😁。

**Comment by Charlie-Hua** [comment]
剛找到一個 babel plugin [babel-plugin-transform-node-env-inline](https://github.com/babel/minify/tree/master/packages/babel-plugin-transform-node-env-inline)
 可把 config.js 中
`process.env.NODE_ENV == 'development'`, `process.env.NODE_ENV !== 'production'` 
這類的 comparison 替換成 `true`, `false`

應該比 replace 的做法更好, FYI

**Comment by ystarlongzi** [comment]
好的，谢谢，我先试下看

**Comment by ystarlongzi** [comment]
@Charlie-Hua 

不行哦，我希望的不仅仅是替换 NODE_ENV，还有其它内容

**Comment by ystarlongzi** [comment]
另外 babel 编译应该是在 wepy 编译之后吧 @Gcaufy

**Comment by Charlie-Hua** [comment]
@ystarlongzi 能舉個例子嗎？

**Comment by ystarlongzi** [comment]
@Charlie-Hua 使用场景嘛？就是 `config` 的内容，会根据构建时不同的参数，生成不同的结果

**Comment by Charlie-Hua** [comment]
@ystarlongzi 了解，是我誤會了～
