### ISSUE TITLE
props不能用字面量去传值么

### ISSUE THREAD

**Issue by 525729985** [wepyjs/wepy#197]
`<searchbar :showCancelButton="showSearchCancel"></searchbar>`
这种样式类组件还要去定个变量去写实在很奇怪

**Comment by Gcaufy** [comment]
https://wepyjs.github.io/wepy/#/?id=props-%e4%bc%a0%e5%80%bc

你说的是静态传值吧。

**Comment by 525729985** [comment]
`<searchbar showCancelButton="true"></searchbar>`
`showCancelButton: {
        type: Boolean,
        default: false
      },`
 输出false

`<searchbar showCancelButton="true"></searchbar>`
`showCancelButton: {
        type: String,
        default: false
      },`
 输出true

@Gcaufy type是String到是能顺利传进去,但是type用Boolean就不行

**Comment by Gcaufy** [comment]
对的，这里其实只能写string

**Comment by 525729985** [comment]
好吧了解了,希望以后可以支持别的类型吧,不然component用起来实在很别扭
