### ISSUE TITLE
对微信 内置 api promise封装的问题

### ISSUE THREAD

**Issue by Uheinanba** [wepyjs/wepy#199]
![image](https://user-images.githubusercontent.com/7878971/27175261-305ae48c-51f1-11e7-8f22-ca3f47ae2e00.png)

现在有些更新的API 比如：reportAnalytics 是没有 success的回调，在程序中会报错。
看看有没有办法做下兼容呢。

**Comment by Gcaufy** [comment]
发版本后将支持配置在wepy.config.js中去配置
```
module.exports = {
    build: {},
    compilers: {},
    appConfig: {
        promisifyAPI: {
            'reportAnalytics': true
        }
    }
}
```

**Comment by yoyoyohamapi** [comment]
@Gcaufy 您好，这个配置现在支持了吗

**Comment by Gcaufy** [comment]
@yoyoyohamapi 还没有发布新版本呢，你可以参考这个commit https://github.com/wepyjs/wepy/commit/ee80ec54ca83dbe9052f961c1a3d34d47cd979e7 自行修复一下代码
