### ISSUE TITLE
dist目录生成的.wxml文件不能压缩吗

### ISSUE THREAD

**Issue by xiaofeiapis** [wepyjs/wepy#20]
dist目录生成的.wxml文件不能压缩吗

**Comment by Gcaufy** [comment]
目前的话没有，后面会弄针对wxml进行压缩的插件。

**Comment by xiaofeiapis** [comment]
点赞

**Comment by Gcaufy** [comment]
@xiaofeiapis 已支持wxml压缩，参见： https://github.com/wepyjs/wepy/tree/master/packages/wepy-plugin-filemin
