### ISSUE TITLE
升级1.5.7后页面中使用 this.$wxapp 访问不到在 app.wepy 中声明的 数据了

### ISSUE THREAD

**Issue by wulunyi** [wepyjs/wepy#200]
升级1.5.7后页面中使用 this.$wxapp 访问不到在 app.wepy 中声明的 数据了
使用 wepy.$instance 可以访问

**Comment by Gcaufy** [comment]
这个是合理的。wxapp的本意是指向 wx 原生的 app对象，而这个对象中不应该有 wepy.app 的数据和方法。

最合理的访问方式是
```
页面中： this.$parent.globalData
组件中： this.$root.$parent.globalData
```
