### ISSUE TITLE
子组件写成<nav-tab></nav-tab>这种形式子组件完成不能运行

### ISSUE THREAD

**Issue by tansj526** [wepyjs/wepy#201]
我习惯了写vue，所以引用组件的时候不小心写了这种形式`<nav-tab></nav-tab>`，然后子组件中的data全都变成NaN了。

希望作者修复一下，谢谢

**Comment by Gcaufy** [comment]
这里说的是两个问题还是一个问题。
有个.wepyignore 文件 加入如下内容。
```
*.wpy___jb_tmp___
```

**Comment by tansj526** [comment]
我说的是两个问题，第一个问题是子组件的书写问题，<nav-tab></nav-tab>这种形式组件完全不能工作

**Comment by gitpaladin** [comment]
You should submit two issues to discuss them separately.

### Issue 1:

The wepy compiler translated the name of nav-tab's data as `$nav-tab$subData`, which javascript engine regarded it as an expression with a minus. So the result of this expression will return `NaN` (aka not a  number). To fix this issue, the wepy compiler must translate the component name as a valid javascript variable name such as `$navTab$subData`.
