### ISSUE TITLE
我想问下 wepy 有没有解决原生 setData 一次超过1024kb的问题

### ISSUE THREAD

**Issue by MrKou47** [wepyjs/wepy#202]
rt, 比如小程序里面 infinite scroll , 每次滚动到底部 都会request api后 将数据与data里面的数据合并， 到最后就会导致数据量一次set的太大导致功能无法实现，这个有解决方案吗

**Comment by Gcaufy** [comment]
并没有，一样是用setData去处理的。破不了

**Comment by MrKou47** [comment]
gg
