### ISSUE TITLE
使用sass语法，编译器报错

### ISSUE THREAD

**Issue by zhuowenli** [wepyjs/wepy#208]
wepy@1.5.7 设置 `<style lang="sass">`  使用sass语法，编译器会报错。

```sass
.home
    background: #fff
    .swiper
        width: 100%
        height: 280rpx
        overflow: hidden
        &-image
            width: 100%
```

错误日志：
```
{ Error: Invalid CSS after ".": expected 1 selector or at-rule, was ".home"
    at options.error (/Users/zhuowenli/demo/weapp-demo/node_modules/node-sass/lib/index.js:292:26)
  status: 1,
  file: '/Users/zhuowenli/demo/weapp-demo/src/pages/index.sass',
  line: 1,
  column: 1,
  message: 'Invalid CSS after ".": expected 1 selector or at-rule, was ".home"',
  formatted: 'Error: Invalid CSS after ".": expected 1 selector or at-rule, was ".home"\n        on line 1 of src/pages/index.sass\n>> .home\n   ^\n' }
```

但是代码却仍然可以正常编译到 `index.wxss` 中，应该是 `node-sass` 配置有问题，望解决！

**Comment by zhuowenli** [comment]
#43

**Comment by Gcaufy** [comment]
@zhuowenli 已修复，在未发布版本之前，在`wepy.config.js`中加入配置：
```
sass: {
    indentSyntax: true
}
```
也可以解决这个问题。

**Comment by Gcaufy** [comment]
fixed in 1.5.8

**Comment by jswxwxf** [comment]
到底应该怎么配置啊？怎么我现在用的是1.6.0还是会报这样的错？
<style lang="sass">
  .userinfo {
    display: flex;
    flex-direction: column;
    align-items: center;
    &-avatar {
      width: 80rpx;
      height: 80rpx;
      border-radius: 50%;
    }
    &-nickname {
      color: #aaa;
    }
  }
</style>

[Error] Error: Invalid CSS after " ": expected 1 selector or at-rule, was "{"
    at options.error (/Users/wangxifeng/Programs/VSCProjects/mina/node_modules/node-sass/lib/index.js:291:26)

**Comment by Gcaufy** [comment]
@jswxwxf `lang="scss"`

https://segmentfault.com/a/1190000005646206
