### ISSUE TITLE
页面之间如何 通信?

### ISSUE THREAD

**Issue by gongzili456** [wepyjs/wepy#209]

**Comment by Gcaufy** [comment]
https://wepyjs.github.io/wepy/#/api?id=wepypage-class

看一下这个preload

或者直接使用一个全局模块都是可以 的。

**Comment by SoyMeng** [comment]
调用$navigate方法,跳转页面onLoad(options,params),params中可以得到一个from的参数,这个不是wepy实现的？

**Comment by Gcaufy** [comment]
是wepy封装的，原生 没有

**Comment by WangLeto** [comment]
作者给出的链接失效了，正确的地址：https://tencent.github.io/wepy/document.html#/api?id=wepypage-class

**Comment by UICJohn** [comment]
想问一下wepy2.0应该怎么做页面间的通信？
