### ISSUE TITLE
无法找到依赖

### ISSUE THREAD

**Issue by kiner-tang** [wepyjs/wepy#21]
![image](https://cloud.githubusercontent.com/assets/10286961/21922536/18a0e7ca-d9aa-11e6-88e8-cd597d7fc898.png)
![image](https://cloud.githubusercontent.com/assets/10286961/21922547/28afe1e8-d9aa-11e6-8989-f75f4bfdb631.png)

**Comment by Gcaufy** [comment]
请先执行`npm install`

**Comment by kiner-tang** [comment]
我已经执行过npm install了
![image](https://cloud.githubusercontent.com/assets/10286961/21923144/5a941fdc-d9ad-11e6-8163-d28a37e85882.png)
![image](https://cloud.githubusercontent.com/assets/10286961/21923166/7b5aea3e-d9ad-11e6-851a-e9700f548d40.png)

**Comment by AlbertLiu-Breeze** [comment]
出现了同样的问题，文件好像没有进行拷贝

**Comment by kiner-tang** [comment]
是的，我无论运行你们的demo还是运行
[https://github.com/wepyjs/wepy-wechat-demo](https://github.com/wepyjs/wepy-wechat-demo)
都是报同样的错

**Comment by Gcaufy** [comment]
@AlbertLiu-Breeze @kiner-tang `npm -v`

**Comment by Gcaufy** [comment]
升级`npm`到`3+`

**Comment by ErickHsieh** [comment]
试试
wepy build --watch --no-cache
开启 ES6 转ES5  不打勾
