### ISSUE TITLE
使用wepy.request('xxxx')返回结果undefined

### ISSUE THREAD

**Issue by wangenyong** [wepyjs/wepy#210]
在调用网络接口时
let res = await wepy.request('http://gank.io/api/data/Android/10/1').then((d) => console.log(d));
提示
Cannot read property 'then' of undefined;
打印res也是显示 undefined；

麻烦问下这要怎么解决？

**Comment by Gcaufy** [comment]
```
this.use('promisefy');
```

**Comment by unclexiao** [comment]
拼写错误，应该是：this.use('promisify'); 
另外，为何官方文档没有说明这一点？而且官方DEMO和CLI生成的项目，都是没有这一句的。

**Comment by Gcaufy** [comment]
这个放在wiki里面了：
https://github.com/wepyjs/wepy/wiki/wepy%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8Promise
