### ISSUE TITLE
页面 unload 后, data 数据没有销毁, 请问如何恢复初始值?

### ISSUE THREAD

**Issue by gongzili456** [wepyjs/wepy#212]
页面注销后, data 数据并没有情况. 请问如何清空

**Comment by ochukai** [comment]
同问，但是我暂时用 sync 解决的，莫名其妙的缓存~

```html
 <inputfield
            label="标题"
            :value.sync="title"
            @change.user="bindTitleChange"></inputfield>
<textareafield label="描述" :value.sync="desc" @change.user="bindDescChange"></textareafield>
```

**Comment by gongzili456** [comment]
而且我亲测试用原生小程序方式是没有这种问题的, 如果在 unload 方法中手动重置数据确实反人类

**Comment by ochukai** [comment]
@gongzili456 我也测过，原生是没有问题的，自从我加上 sync 也就没有问题了~

**Comment by gongzili456** [comment]
@ochukai 那你在 page 中的 data 怎么重置的? 你这里组件使用 sync 的能行话, 肯定是因为page 的data数据被重置了. 我就是没找到这个方法.

**Comment by ochukai** [comment]
@gongzili456 page 小程序原生会自动关闭的，只要你不使用 navigateTo，下次打开就是新状态了~

**Comment by Gcaufy** [comment]
@gongzili456 我记得原生也一样存在这个问题吧，因为小程序的机制原因，你即便页面跳转了，内存中的数据都不会清楚。

**Comment by SoyMeng** [comment]
@Gcaufy 确实存在这个问题，原生的页面缓存是不会进入onLoad事件的，这个应是wepy缓存的示例？

**Comment by Gcaufy** [comment]
@SoyMeng 下周我再看看这个问题。

**Comment by hamletfei** [comment]
这个问题现在可有解决方案，这个问题很纠结啊

**Comment by Gcaufy** [comment]
@gongzili456 我刚才用原生测试的，redirect后再回来，页面data，不会销毁，不知道你这里是怎么测试的呢？

**Comment by Gcaufy** [comment]
@hamletfei 先在unload里面手动初始化一次

**Comment by Gcaufy** [comment]
@gongzili456 
在page1中修改`data.list`后，Redirect到page2，再 back 到page1时发现 data.list 还存在，没有清空。
```
bindViewTap: function() {
    console.log(this.data.list);
    wx.startTime = +new Date();
    wx.navigateTo({
      url: '../page2/page2'
    })
  }
```

**Comment by gongzili456** [comment]
我的场景是: 一个表单编辑页, 从详情页进去以后需要初始化数据, navigateBack 到详情页, 然后在通过新建入口进入, 正确情况下应该会将上次由详情页的数据清掉, 但是没有清掉.

**Comment by gongzili456** [comment]
正常的设计逻辑, 页面 unLoad 后不就是已经卸载了吗, 为什么还会缓存它的数据?

**Comment by Gcaufy** [comment]
@gongzili456 这个是小程序的机制问题，也是与我们web开发最大的不同。视图层和逻辑层运行在隔离的环境。
视图层注销后，会调用逻辑层的unLoad生命周期函数。但是逻辑层运行的环境一直存在，并没有被注销的。所以数据还会在，
最简单的测试方式是，你在page1 加一句 
`setInterval(() => {console.log('print sth')})`
然后redirect到page2，可以看到控制台依然会打印数据的。

**Comment by gongzili456** [comment]
那么在 wepy 中是否需要修改这种逻辑呢? 每次 unload 都要手动复位实在是不优雅. 而且也给编码加大了复杂度.

**Comment by Gcaufy** [comment]
@gongzili456 原生的机制问题 wepy 这里暂不会处理，否则对用户的影响会很大，这个问题开发者自己在开发的时候注意一下就好了。

**Comment by ochukai** [comment]
**navigateTo** 是隐藏当前，会执行 onHide， **redirectTo**，** reLaunch**  才会执行 unload @Gcaufy

**Comment by Gcaufy** [comment]
@gongzili456 @ochukai  try this:

```
// page1.js
var somedata = 'emtpy';
Page({
   tap: function () {
      somedata = 'new data';
      setInterval(function () {
          console.log('interval');
      })
      wx.redirectTo({url: '../pages/page2'});
   }
   onLoad: functon () {
      console.log(somedata);
   }
});

// page2.js
Page({
   tap: function () {
      wx.redirectTo({url: '../pages/page1'});
   }
});
```

进入page1时，控制台输出 'empty'，点击页面按钮激活 setInterval, 并且改变 somedata, redirecto page2
在page2页面仍然可以看到 interval，点击按钮 redirectto page1 后， 控制台输出 'new data'。

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy/issues/214

**Comment by li-xianfeng** [comment]
@Gcaufy 这个问题不是原生小程序机制的问题，举个例子
商品详情页，默认data.id='', 第一次进入A商品，设置data.id=id1；此时再跳转B商品，触发onload，在onload中获取data.id还是id1；如果是原生小程序，跳转B页面时触发onload则获取到data.id会是页面默认值，即data.id=''，而不是A页面设置的id1。（A详情和B详情path相同，只是query不一样），建议看下是不是所有打开过的相同路径页面都共享同一个页面实例。

**Comment by Gcaufy** [comment]
@li-xianfeng 版本是？

**Comment by li-xianfeng** [comment]
@Gcaufy  我使用的是v1.5.5，我看changlog没有关于这个问题的更新，所以新版还没试过，如果没修复过麻烦看下能不能修复下这个问题，在小程序页面层级比较复杂时影响挺大的，像我上面举的详情页例子，页面间数据相互影响会造成很多BUG，谢谢了

**Comment by Gcaufy** [comment]
这个应该是在1.5.8中修复了，CHANGELOG上面好像写漏了，你可以升级一下测试看看

**Comment by li-xianfeng** [comment]
@Gcaufy 刚测试OK了   👍

**Comment by Licoy** [comment]
@li-xianfeng  你们上面所指的版本是什么版本？

**Comment by jessjava** [comment]
@li-xianfeng 开发者工具里面是看不出来了。但是 iphone 上问题依旧。残留上一个 id 查询出来的数据。
