### ISSUE TITLE
页面 卸载后数据依然存在，onLoad 时 data 中还保留上一次数据，每次都得手动清除很不爽。。。

### ISSUE THREAD

**Issue by wulunyi** [wepyjs/wepy#214]

**Comment by beierweiwei** [comment]
这是小程序的机制啊，不应该在这里提啊！

**Comment by coolhwm** [comment]
原生的data表现的确和wepy的data表现不一样，原因貌似是wepy的数据不是保存在page中，虽然是小程序的机制，但是还是希望同样是data，wepy和mina能够呈现出一致的表现，或者能够通过配置框架参数实现。
@Gcaufy

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy/issues/212

**Comment by coolhwm** [comment]
感谢作者，等待下个版本

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy/issues/246

**Comment by liujunchina** [comment]
确实不一样 ，整个 page 的数据都会被缓存，原生小程序并不会
所以暂时都是  unload 的时候手动初始化

**Comment by jessjava** [comment]
点击左上角返回（android 点击 back 返回）之后通过 options 传递新的数据进来，查询得到结果之前，页面还是上一次的数据哦。
