### ISSUE TITLE
同一个组件的自定义事件在不同的实例上调用的是同一个方法。

### ISSUE THREAD

**Issue by song0229liu** [wepyjs/wepy#219]
>
 <input class="weui-input" placeholder="{{cellData.placeholder}}" disabled="{{cellData.disabled}}" cursor-spacing="{{cellData.cursorspacing}}" focus="{{cellData.focus}}" confirm-type="{{cellData.confirmtype}}" confirm-hold="{{cellData.confirmhold}}" password="{{cellData.ispassword}}" type="{{cellData.ctype}}" value="{{val}}" bindinput="bindinput" bindblur="bindblur" bindfocus="bindfocus" bindconfirm="bindconfirm"/>
<script>
  import wepy from 'wepy'
  export default class cell extends wepy.component {
    props = {
      cellData: {
        type: Object,
        value: {
          placeholder: '',
          title: '',
          ctype: 'text',
          ispassword: false,
          disabled: false,
          cursorspacing: 0,
          focus: false,
          confirmtype: 'done',
          confirmhold: false
        }
      },
      val: {
        type: String,
        value: ''
      }
    }

    methods = {
      bindinput (e) {
        this.$emit('bindinput', e)
      },
      bindblur (e) {
        this.$emit('bindblur', e)
      },
      bindconfirm (e) {
        this.$emit('bindconfirm', e)
      },
      bindfocus (e) {
        this.$emit('bindfocus', e)
      }
    }

    onLoad(e) {
      console.log('hhhhhh')
    }
  }
</script>

> <template>
      <view class="weui-cells">
        <repeat>
          <cell :cellData="cellphone" @bindinput.user="bindinput"></cell>
          <cell :cellData="cellprice" @bindinput.user="bindconfirm"></cell>
        </repeat>
      </view>
</template>`父组件调用、事件执行的是后一个方法。

**Comment by Gcaufy** [comment]
请宝 cell1, cell2， 组件ID 是组件的唯一标识
