### ISSUE TITLE
onShareAppMessage分享接口报错，不能定制分享

### ISSUE THREAD

**Issue by eshion** [wepyjs/wepy#22]
https://mp.weixin.qq.com/debug/wxadoc/dev/api/share.html#onshareappmessage

<img width="609" alt="wx20170114-100554 2x" src="https://cloud.githubusercontent.com/assets/1287467/21951432/20704260-da41-11e6-9815-a23fa711f841.png">

看源码应该是对Page事件漏加了onShareAppMessage

https://github.com/wepyjs/wepy/blob/master/packages/wepy/src/base.js#L21

**Comment by kiner-tang** [comment]
已经构建好的项目要重新构建才能修复这个问题吗？

**Comment by Gcaufy** [comment]
@kiner-tang 先手动修复吧，下个版本发布后再构建一下就可以解决这个问题了。

**Comment by kiner-tang** [comment]
好的

**Comment by kiner-tang** [comment]
请问该如何手动修复呢？

**Comment by Gcaufy** [comment]
@kiner-tang 参考https://github.com/wepyjs/wepy/commit/13b5094aaa0e4318dd5d6280c9aa88d3ccef87f4

修改node_modules/wepy/lib/base.js

**Comment by Gcaufy** [comment]
已发布更新

**Comment by 957919019** [comment]
我也遇到了这个问题

**Comment by Gcaufy** [comment]
@957919019 参考这个 https://github.com/wepyjs/wepy/issues/52
