### ISSUE TITLE
如何往 runtime 中注入环境变量?

### ISSUE THREAD

**Issue by gongzili456** [wepyjs/wepy#223]
需要在不同环境的 runtime 中使用不同的config, 习惯使用 config 模板, 但是目前貌似无法注入

**Comment by Gcaufy** [comment]
```
if (ENV === 'prod') {
} else {
}
```

**Comment by MinJieLiu** [comment]
Uncaught ReferenceError: ENV is not defined

@Gcaufy

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy/issues/231

**Comment by Gcaufy** [comment]
上面是伪代码。
```
if (process.env.NODE_ENV === 'production') {
} else {
}
```

**Comment by MinJieLiu** [comment]
@Gcaufy Uncaught ReferenceError: process is not defined

**Comment by Gcaufy** [comment]
@MinJieLiu 
在`wepy.config.js`中
