### ISSUE TITLE
wepy 如何渲染 带 <br />  标签的 字符串？

### ISSUE THREAD

**Issue by erbing** [wepyjs/wepy#224]
如题

**Comment by Gcaufy** [comment]
尝试将<br />替换为\r\n试试

**Comment by Gcaufy** [comment]
问题是否已解决？

**Comment by erbing** [comment]
不行噢， \r\n 在  chrome 的控制台中确实 换行了，但是到了 视图，依然没有换行

**Comment by erbing** [comment]
![](http://images2015.cnblogs.com/blog/675289/201706/675289-20170630100501430-101584066.png)

![](http://images2015.cnblogs.com/blog/675289/201706/675289-20170630100509852-506455835.png)

**Comment by erbing** [comment]
建议 wepy 参考，vue 的做法 {{{  }}}  这样来直接解析 带有html标签的 字符串

**Comment by Gcaufy** [comment]
小程序支持不了没办法的，这个超出了wepy的功能范围。

**Comment by ryh** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
使用pre-wrap pre-line  就能换行硬回车
但这个事情好像不该wepy做，而是开发者自己决定
