### ISSUE TITLE
如果使用 setData 修改数据，所做的修改会立刻被重置。

### ISSUE THREAD

**Issue by YaoaY** [wepyjs/wepy#225]
以 wepy-weui-demo 中的 navbar 为例子：
`
import wepy from 'wepy';

    const sliderWidth = 96; // 需要设置slider的宽度，用于计算中间位置

    export default class Toast extends wepy.page {

        data = {
            tabs: ['选项一', '选项二', '选项三'],
            activeIndex: 1,
            sliderOffset: 0,
            sliderLeft: 0
        };

        methods = {
            tabClick (e) {
                //  this.sliderOffset = e.currentTarget.offsetLeft;
                //  this.activeIndex = e.currentTarget.id;
                this.setData({
                    sliderLeft: e.currentTarget.offsetLeft,
                    activeIndex: e.currentTarget.id
                });
            }
        }

        async onLoad () {
            let res = await wepy.getSystemInfo();

            this.sliderLeft = (res.windowWidth / this.tabs.length - sliderWidth) / 2;
            this.sliderOffset = res.windowWidth / this.tabs.length * this.activeIndex;
        }
    }
`

在 tabClick 中，例子中是直接用 this.xxxx = xxx 进行修改的，测试并无问题。
但在有些情况，我并不能采用这样直接赋值的方式，而是需要调用setData进行修改，但这样是不起作用的，或者说，是起了作用但很快就被改回去了。

比如我使用TypeScript的话，在不额外重复声明 activeIndex  的情况下，是无法直接 this.activeIndex = 1; 这样是无法编译的。所以要么声明一下 activeIndex:any，要么采用 setData({activeIndex:1); 然而……

**Comment by Gcaufy** [comment]
不建议直接使用setData，setData会触发额外的数据通信，影响本身性能。
另外  ```this.xxxx = yyyy```  ！== ```this.setData({xxxx: yyyy})```
一定要用的话可以尝试
```
var obj = {};
obj[this.$prefix + 'xxxx'] = yyyy;
this.setData(obj);
```
