### ISSUE TITLE
某种情况下子组件props接收不到值

### ISSUE THREAD

**Issue by tansj526** [wepyjs/wepy#226]
你好，我使用子组件用这种方法传值过去，props接收不到title这个值，一定要把title写在data中才可以成功接收
<tab :title="'标题文字'"></tab>
这种情况下只是传字符串过去不是很方便

**Comment by Gcaufy** [comment]
有简单的代码说明么

**Comment by tansj526** [comment]
不好意思，我记得我写了代码的，怎么不见了，
代码是这样子的： <tab :title="'这是标题'"></tab>
然后我在子组件tab中收不到title这个值

**Comment by tansj526** [comment]
不好意思，我记得我写了代码的，github不能写html标签了
代码是这样子的： `<tab :title="'这是标题'"></tab>`
然后我在子组件tab中收不到title这个值

**Comment by Gcaufy** [comment]
```
<tab title="'这是标题'"></tab>
```

参见文档中的静态传值。

**Comment by zhongziqi** [comment]
同问 ，请问这个问题解决了吗，急急急
