### ISSUE TITLE
关于sass在app.wpy中定义变量的问题

### ISSUE THREAD

**Issue by coolhwm** [wepyjs/wepy#227]
在app.wpy文件中定义了sass变量，目前无法在页面或子页面中获取到，提示未定义，必须要将需要的变量定义在一个scss文件中，然后在需要使用的wpy文件中引用，才可以编译通过。
不知道是不是打开方式不对，有没办法让在app.wpy中定义的sass变量在全局都可以读到？

**Comment by coolhwm** [comment]
另外，传递参数到组件中时，无法使用展开操作符（...），是有其他方法吗？

**Comment by Gcaufy** [comment]
没有办法，试想一下，在Web开发时，我在index.scss里定义的变量如果能在page.scss中使用呢？

唯的办法就是把公用的变量提取出来`variable.scss`，然后在不同的文件中分别引入这个变量定义文件

**Comment by coolhwm** [comment]
了解，谢谢
