### ISSUE TITLE
关于向组件传递回调函数的问题

### ISSUE THREAD

**Issue by coolhwm** [wepyjs/wepy#228]
- 现在页面可以向组件传递回调函数吗？
- 是否建议使用`$broadcast`，`$emit`，`$invoke`实现组件与页面间通讯，而不是回调函数？

**Comment by Gcaufy** [comment]
1. 可以
2. 这三个函数就是用来做组件间的通讯的，页面也是组件。

**Comment by coolhwm** [comment]
谢谢！
