### ISSUE TITLE
关于拦截器 intercept 能否在方法执行前拦截

### ISSUE THREAD

**Issue by coolhwm** [wepyjs/wepy#229]
如题，能否在方法执行前拦截，修改调用方法的参数

**Comment by Gcaufy** [comment]
```
config (p) {
    return p;
}
````

**Comment by coolhwm** [comment]
好的，谢谢

**Comment by wangquanxin** [comment]
可否留个微信或者qq，leshare-weapp 连不上服务需要请教下

**Comment by Gcaufy** [comment]
@wangquanxin 可以扫码加微信群聊

**Comment by wangquanxin** [comment]
二维码在哪里

**Comment by Gcaufy** [comment]
首页

**Comment by BoleLee** [comment]
需要在success/fail里使用到config返回的信息，比如url和dada, 怎么做比较好？如果在config里先把数据赋值给一个变量，再在success/fail时使用，在同时多个请求的情况下，感觉数据可能会不对应；

需求是希望在请求出错的情况下，将请求的url/data/response等信息收集起来，方便查找原因；我感觉应该是用拦截器实现比较好的，但是就遇到了上面说的这个问题，求教

**Comment by surfingtomchen** [comment]
aysnc config (p) {
    await something;
    return p;
}

为什么上面的写法，会报url找不到错误

**Comment by Gcaufy** [comment]
@surfingtomchen 

建议再了解一下async
这种写法等同于
```
config () {
return new Promise((resolve, reject) => something().then(res => resovle(res));
}
```

**Comment by CoderPoet** [comment]
@Gcaufy 
aysnc config (p) {
await something;
return p;
} 
以及
config () {
return new Promise((resolve, reject) => something().then(res => resovle(res));
}
都报错:request:fail parameter error: parameter.url should be String instead of Undefined;
意思是这里不能返回一个promise 只能返回p么？
那如果这里想实现类似async /await 的功能应该怎么做呢？即能不能异步返回一个p？

**Comment by CoderPoet** [comment]
@Gcaufy 请问，比如我想为每一个请求的头加上token。但是这个token第一次必须得请求服务器认证（这个过程是异步的）获得。如果使用拦截器，能否阻塞请求直到token获取成功（异步请求完成）之后再进行？

**Comment by Leexin1001** [comment]
@CoderPoet  你好，我跟你遇到了同样的问题，也是一直报 parameter.url should be String instead of Undefined; 请问这个问题你解决了吗
