### ISSUE TITLE
sass报错

### ISSUE THREAD

**Issue by jeodiong** [wepyjs/wepy#23]
`{ Error: Invalid CSS after "": expected 1 selector or at-rule, was ".container"
    at options.error (/Users/biangbiang/Documents/_project/vcsmart/front-cx/node_modules/.4.3.0@node-sass/lib/index.js:286:26)
  status: 1,
  file: '/Users/biangbiang/Documents/_project/vcsmart/front-cx/src/app.vue',
  line: 1,
  column: 1,
  message: 'Invalid CSS after "": expected 1 selector or at-rule, was ".container"',
  formatted: 'Error: Invalid CSS after "": expected 1 selector or at-rule, was ".container"\n        on line 1 of src/app.vue\n>> \n   ^\n' }`

`<style lang="sass">
.container
  height: 100%
</style>

<script src='app.js'>
</script>`

只有一句话

**Comment by Gcaufy** [comment]
语法不对。
```
<style lang="sass">
.container {
    height: 100%
}
</style>
```
