### ISSUE TITLE
使用 pug 语法，使用 slot 组件，生成后外层 view 不在了

### ISSUE THREAD

**Issue by wulunyi** [wepyjs/wepy#230]
child
```javascript
<template lang="pug">
view.test
  slot(name='title') title
  view
    text test
</template>
```
parent
```javascript
<template lang="pug">
Child
  view(slot='title')
    text 店长推荐
</template>
```
期望结果
```javascript
view.test
  view
      text  店长推荐
  view
      text test
```
实际结果
![image](https://user-images.githubusercontent.com/15170275/27766305-4a254442-5efe-11e7-96fc-61eaee7cd526.png)
父容器 view.test 并没有生成出来

**Comment by Gcaufy** [comment]
如果使用 wxml 去写也会出现这个问题么？

**Comment by wulunyi** [comment]
demo 里面用 wxml 写的是可以的

**Comment by Gcaufy** [comment]
好的，稍后我去看看

**Comment by Gcaufy** [comment]
初步定位到是因为 PUG 编译后生成的HTML是压缩的，然后由于xmldom本身的原因导致替换出错。
现在解决方案是，PUG 编译默认不压缩。后面再看是否能从根本解决这个问题。
未发版本之前，可以先在config文件中指定 PUG 不压缩即可：
```
// wepy.config.js
compilers: {
    pug: { 
        pretty: true
    }
}
```

**Comment by Gcaufy** [comment]
fixed in 1.5.8
