### ISSUE TITLE
脚手架初始出来连.gitignore都没有？！

### ISSUE THREAD

**Issue by FrendEr** [wepyjs/wepy#237]

**Comment by XylitolLin** [comment]
自己加一个很难？

**Comment by Gcaufy** [comment]
.gitignore文件一直都有，你说的是 .wepyignore 么？ 刚加上了。

**Comment by HADB** [comment]
.wepyignore有啥用？git认的是.gitignore啊，.wepyignore可以删吗？

**Comment by HADB** [comment]
另外，.wepycache文件是否应该在git中排除？
脚手架最好默认把.gitignore文件生成

**Comment by Gcaufy** [comment]
@HADB 
https://github.com/wepyjs/wepy/blob/master/packages/wepy-cli/templates/template/.gitignore
1. .gitignore默认会自动生成
2. .wepyignore是指有些文件不希望通过wepy编译，因此这个文件属于项目的一部分，不能在git中排除

**Comment by HADB** [comment]
@Gcaufy 比较奇怪的是，我用脚手架生成的项目中并没有.gitignore
<img width="631" alt="qq20171113-104621 2x" src="https://user-images.githubusercontent.com/1836701/32707602-0a396aea-c860-11e7-89f7-a6906c53b2c8.png">
<img width="632" alt="qq20171113-104638 2x" src="https://user-images.githubusercontent.com/1836701/32707603-0b78d788-c860-11e7-9b67-562ed98ed548.png">

**Comment by Gcaufy** [comment]
刚测试一下是没有问题的。
![image](https://user-images.githubusercontent.com/2182004/32707739-efba5976-c860-11e7-89cc-efadd8f26cab.png)

**Comment by NoraGithub** [comment]
mac下的确是没有的。

**Comment by NoraGithub** [comment]
而且 多了一个 .wepycache

**Comment by Gcaufy** [comment]
```
[20:36:33] [完成] 代码编译完成
[20:36:33] [完成] 项目初始化完成, 可以开始使用小程序。
➜  test cd demo161
➜  demo161 ls
dist              package-lock.json src
node_modules      package.json      wepy.config.js
➜  demo161 ls -la
total 264
drwxr-xr-x   15 gcaufy  staff    480 Jan 10 20:36 .
drwxr-xr-x    3 gcaufy  staff     96 Jan 10 20:35 ..
-rw-r--r--    1 gcaufy  staff    147 Jan 10 20:35 .editorconfig
-rw-r--r--    1 gcaufy  staff      7 Jan 10 20:35 .eslintignore
-rw-r--r--    1 gcaufy  staff    694 Jan 10 20:35 .eslintrc.js
-rw-r--r--    1 gcaufy  staff     28 Jan 10 20:35 .gitignore
-rw-r--r--    1 gcaufy  staff     26 Jan 10 20:35 .prettierrc
-rw-r--r--    1 gcaufy  staff   1509 Jan 10 20:36 .wepycache
-rw-r--r--    1 gcaufy  staff     46 Jan 10 20:35 .wepyignore
drwxr-xr-x   11 gcaufy  staff    352 Jan 10 20:36 dist
drwxr-xr-x  304 gcaufy  staff   9728 Jan 10 20:36 node_modules
-rw-r--r--    1 gcaufy  staff  97586 Jan 10 20:36 package-lock.json
-rw-r--r--    1 gcaufy  staff   1203 Jan 10 20:36 package.json
drwxr-xr-x    7 gcaufy  staff    224 Jan 10 20:35 src
-rw-r--r--    1 gcaufy  staff   1615 Jan 10 20:35 wepy.config.js
```

**Comment by NoraGithub** [comment]
@Gcaufy 那可能是我本地环境有问题了，例如用了nave之类的？。谢谢回复

**Comment by xiaomizhou66** [comment]
> 而且 多了一个 .wepycache

您好，请问一下这个文件是用来干嘛的？

**Comment by Gcaufy** [comment]
@xiaomizhou66 
npm 只会编译一次，会cache到已编译的npm文件，第二次不会编译，除非该文件被删除或者执行了
`wepy build --no-cache`

**Comment by codenamenebula** [comment]
> @xiaomizhou66
> npm 只会编译一次，会cache到已编译的npm文件，第二次不会编译，除非该文件被删除或者执行了
> `wepy build --no-cache`

所以 wepycache 是可以加到 gitignore  里是吗?

**Comment by Gcaufy** [comment]
@codenamenebula  对的，是应该加到.gitignore里面
