### ISSUE TITLE
关于组件缓存的问题

### ISSUE THREAD

**Issue by chenyuanluck** [wepyjs/wepy#246]
作者，你好！
1、现有页面A,A是详情页面，里面有列表能再跳转到A页面，只是页面参数不一样。A页面有多个组件，当A1跳转到A2后**两个页面的组件是同一个实例**，导致从A2返回到A1时页面上组件里的数据与A2一致。这个问题比较难饶过去。
2、在列表里，遍历一个组件时，这个组件被遍历多次，但这些组件是同一个实例。

这两个问题都是出在组件的实例是同一个实例上。
当然，wepy的机制是这样的，我是想说如果这样，很多业务无法实现，很多业务实现的有问题。
求大神解决或解答。

**Comment by coolhwm** [comment]
目前我是手动清理缓存，貌似没什么问题

```
// 定义默认数据
def = {
  order:  {},
};

// data 
data = {...this.def};

// 页面卸载时清理
onUnload() {
    Object.assign(this, this.def);
}
```

**Comment by chenyuanluck** [comment]
@coolhwm 你这些代码是定义在页面里的还是组件里的，其实我更希望的是组件里的很多数据与页面无关，少偶合的那种
![image](https://user-images.githubusercontent.com/13072539/27991014-e847e0ec-649b-11e7-9fec-44d67651342a.png)
就说onUnload这个方法，在组件里好像就没有，这样就要在页面上的onUnload方法里去遍历执行组件里的onUnload方法才能清除吧？

**Comment by Gcaufy** [comment]
如果不想手动清除的话，可以先参考这个commit 手动修改一下页面代码。

**Comment by jessjava** [comment]
参考哪个 commit?

**Comment by Gcaufy** [comment]
已release

**Comment by jessjava** [comment]
您说的是1.6.0吗

**Comment by jessjava** [comment]
弃了吧
