### ISSUE TITLE
$apply()只能更新data.属性1，但data.属性1.属性2这种，当更新属性2时，$apply()不能重新渲染页面

### ISSUE THREAD

**Issue by chenyuanluck** [wepyjs/wepy#248]
如题，如果出于性能考虑，只更新到属性1，建议给$apply()加个参数，让其在特殊情况下可以data任何一个结点修改都能渲染到页面。

**Comment by Gcaufy** [comment]
能给出具体代码示例么？

**Comment by chenyuanluck** [comment]
![image](https://user-images.githubusercontent.com/13072539/28000826-ec0de428-655a-11e7-9491-de7291cc793f.png)
像这种，页面上用了author.test,这时修改test,修改不成功

**Comment by Gcaufy** [comment]
不存在这种情况， 你改变了test, apply 也会重新渲染数据的，只要你在data中有声明
```
data = {
    author: {}
}
```

**Comment by Juliazlj** [comment]
今天我也遇到了，当$apply方法写在mixin里的时候，三级是不生效的，数据变了，页面没变

**Comment by yucopowo** [comment]
同样遇到  这个问题 不过是事件传递来的对象不能直接修改 需要传递索引去data 里去找 然后修改这个对象就ok了
