### ISSUE TITLE
组件模板可以使用pug编译器吗

### ISSUE THREAD

**Issue by yyyyu** [wepyjs/wepy#25]
![image](https://cloud.githubusercontent.com/assets/15168529/21976110/35eb8494-dc0b-11e6-903d-2788315d1996.png)
组件模板使用pug，但是当做普通文本处理了
![image](https://cloud.githubusercontent.com/assets/15168529/21976172/830fc82a-dc0b-11e6-9902-8213f02e69d6.png)
请问现在组件模板是不是不支持pug，还是需要配置，我已经安装了wepy-compiler-pug，page可以正常渲染

**Comment by Gcaufy** [comment]
刚测试了一下，的确是有这个问题，现在修复一下。

**Comment by Gcaufy** [comment]
已修复，等待版本发布
