### ISSUE TITLE
Q: How to use weui together with wepy?

### ISSUE THREAD

**Issue by hatelove85911** [wepyjs/wepy#252]
如何用wepy 和其他小程序 UI 库一起使用? 例如 [weui-wxss](https://github.com/weui/weui-wxss)?

**Comment by brucx** [comment]
https://github.com/wepyjs/wepy-weui-demo 
https://github.com/wepyjs/wepy-zanui-demo
这里有两个示例

**Comment by Liqiankun** [comment]
我看了这两个例子 只是写死的UI没有和外部交互的东西。@brucx @hatelove85911
