### ISSUE TITLE
执行 npm run build 找不到插件

### ISSUE THREAD

**Issue by biu0w0** [wepyjs/wepy#254]
提示找不到插件，自动安装后 package.json 成功添加 `"wepy-plugin-uglifyjs": "^1.3.6"`，和手动执行 `npm install wepy-plugin-uglifyjs --save-dev` 的效果一样。

但是似乎只是 package.json 中的依赖更新了，无论怎么执行 `npm install` 都在 node_modules 里找不到 `wepy-plugin-uglifyjs`。

另外试了下注释掉 wepy.config.js 中的 uglifyjs 部分，另一个插件 imagemin 依然会报错「找不到插件」，也是自动安装持续失败死循环。

```
> cross-env NODE_ENV=production wepy build --no-cache

[WARNING] 找不到插件：wepy-plugin-uglifyjs。
[00:27:45] [信息] 检测到有效NPM包资源，正在尝试安装，请稍等。
up to date in 2.818s
[00:27:48] [完成] 已完成安装 wepy-plugin-uglifyjs，重新启动编译。
[WARNING] 找不到插件：wepy-plugin-uglifyjs。
[00:27:49] [信息] 检测到有效NPM包资源，正在尝试安装，请稍等。
up to date in 2.789s
[00:27:52] [完成] 已完成安装 wepy-plugin-uglifyjs，重新启动编译。
[WARNING] 找不到插件：wepy-plugin-uglifyjs。
[00:27:53] [信息] 检测到有效NPM包资源，正在尝试安装，请稍等。
up to date in 2.713s
[00:27:56] [完成] 已完成安装 wepy-plugin-uglifyjs，重新启动编译。
[WARNING] 找不到插件：wepy-plugin-uglifyjs。
[00:27:57] [信息] 检测到有效NPM包资源，正在尝试安装，请稍等。
up to date in 2.691s
[00:28:00] [完成] 已完成安装 wepy-plugin-uglifyjs，重新启动编译。
[WARNING] 找不到插件：wepy-plugin-uglifyjs。
......
```

**Comment by biu0w0** [comment]
os: macOS
node: v7.10.0
npm: v5.2.0
wepy: v1.5.7

**Comment by biu0w0** [comment]
已解决，请不要用垃圾淘宝的 CNPM。
很久很久以前添加了 CNPM 的 registry，刚刚想起来了然后恢复为 `https://registry.npmjs.org/`。

然后就好了。

**Comment by yicone** [comment]
这里有个恢复 registry 为 https://registry.npmjs.org/ 也没解决同样问题的情况。

```sh
$ npm config get registry  
https://registry.npmjs.org/
npm cache clean --force
NODE_ENV wepy build
```

node: v7.10.0
npm: v5.3.0
wepy: v1.5.8
