### ISSUE TITLE
运行新建工程报错

### ISSUE THREAD

**Issue by everfire130** [wepyjs/wepy#259]
1. 按文档新建了工程
![image](https://user-images.githubusercontent.com/11308837/28235461-661edd42-6940-11e7-8c5a-e5b4e86587d5.png)

2. 也做了相应的设置
![image](https://user-images.githubusercontent.com/11308837/28235452-4a3e25ce-6940-11e7-8bac-ab522857cee2.png)

3. 用微信开发工具打开dist目录后编译报错
```
WAService.js:9 Uncaught Error: module "node_modules/promise-polyfill/promise.js" is not defined
base.js:133 Uncaught TypeError: Cannot read property '$pages' of undefined
pages/index 出现脚本错误或者未正确调用 Page()
```
![image](https://user-images.githubusercontent.com/11308837/28235475-d1bc1d9e-6940-11e7-8e90-27ef1141bcf0.png)

> 是我哪里弄错了吗，还是环境有问题？已经试过重装与重新编译、重新打开等操作，求指点
环境：
系统 macOS 10.12.5
node v5.7.0
微信开发工具 0.19.191100

**Comment by Gcaufy** [comment]
看起来像是ES6转ES5的问题，但是你的截图是关过的。那你尝试重启开发者工具试试，有可能是缓存问题。

**Comment by everfire130** [comment]
@Gcaufy 不是缓存问题，我换了node版本就好了，原本用v5.7.0，现在用v6.10.3
![image](https://user-images.githubusercontent.com/11308837/28254203-21c926c2-6add-11e7-8888-677174be364a.png)

**Comment by Gcaufy** [comment]
奇怪，5的版本应该是没有问题的。不过解决了就好
