### ISSUE TITLE
如何拥有下拉刷新功能的商品列表制作成一个组件

### ISSUE THREAD

**Issue by kiner-tang** [wepyjs/wepy#26]
因为组件没有对应的json,如果需要将拥有下拉刷新功能的商品列表制作成一个组件该如何实现呢

**Comment by Gcaufy** [comment]
不了解这里的需求是什么？或者你期望的实现的是什么功能，可以用伪代码表示。

**Comment by kiner-tang** [comment]
哦哦，我的意思是，如果想将一个拥有下拉刷新功能的列表做成一个公共组件的话，该如何实现。因为按照官方所给的文档，组件中是没有相对应的json文件的，那么，也就意味着，我们没办法配置：
![image](https://cloud.githubusercontent.com/assets/10286961/22005834/5d00e308-dca1-11e6-8421-44d3f1c9756a.png)
来实现下拉刷新。

我现在采用了组件的$broadcast的方式，在page中配置下拉刷新的选项，当用户做了下拉刷新操作时，在page中通过广播的形式通知组件，让组件访问接口执行刷新操作。不过，这种实现方式，如果逻辑简单还好，如果逻辑复杂了，就没办法提现组件的随意组装的优势了。
![image](https://cloud.githubusercontent.com/assets/10286961/22005879/c5c3c55e-dca1-11e6-8f60-2af2c1e96818.png)
![image](https://cloud.githubusercontent.com/assets/10286961/22005890/d9cff5ea-dca1-11e6-87a2-8d16e671b2c9.png)
不知是否有更好的方式实现，达到组件与页面尽可能分离

**Comment by Gcaufy** [comment]
了解， 不过下拉刷新应该是页面配置吧，组件并不存在配置项。
当前如果加入mixin的话，可以在mixin内写onPullDownRefresh方法。
所以你希望组件本身能触发onPullDownRefresh是吗？

**Comment by kiner-tang** [comment]
恩恩，我试了一下，如果用mixin和广播结合在一起的话，确实也能够达到我的需求。
