### ISSUE TITLE
如何捕获全局错误（未处理rejection与error）？

### ISSUE THREAD

**Issue by everfire130** [wepyjs/wepy#264]
由于经常使用async/await的写法，有时调用async方法很容易忘记await将错误处理，而且也很需要一个统一处理错误与异常的地方。请问如何捕获这些异常与错误呢？

**Comment by Gcaufy** [comment]
养成良好习惯，写 catch 吧。

**Comment by everfire130** [comment]
@Gcaufy async还是很容易将error吞掉的，刚才发现Promise原本就有方法

```
Promise._setUnhandledRejectionFn(function(err){
  console.log('handle', err);
});
```
