### ISSUE TITLE
当list组件数据绑定改变时，PC开发工具有效果，真机没有效果

### ISSUE THREAD

**Issue by lsyqp** [wepyjs/wepy#266]
list组件定了一个props如下：
  export default class RelativeList extends wepy.component {
    props = {
      list: {}
    }
在index.wpy中list组件绑定代码如下：

      -<view class="title" slot="title">相关列表1</view>
      -<relativelist :list.sync="list"></relativelist>

当rlist改变时，在开发工具中有效果，真心上无法刷新界面，请教朋友们，这是什么原因啊？

**Comment by Gcaufy** [comment]
是不是没有关掉开发者工具自带的压缩功能。

**Comment by lsyqp** [comment]
@Gcaufy 谢谢回复啊，关闭了就可以了，文档里没到有这上要求，请问为什么要关闭？如果后面要压缩需用什么方式？

**Comment by Gcaufy** [comment]
开发者工具使用压缩库在压缩我的代码时似乎会出现某种BUG。
