### ISSUE TITLE
子组件更改数据后，真机调试时，父组件的watch和computed均无法检测到

### ISSUE THREAD

**Issue by smart-Jenny** [wepyjs/wepy#268]
我直接在官方代码里加了一些测试代码，大体如下：
父组件index.wpy:
<img width="603" alt="2017-07-20 4 20 42" src="https://user-images.githubusercontent.com/16362473/28407873-4bf25864-6d68-11e7-8286-e230da3c7db0.png">
<img width="641" alt="2017-07-20 4 25 18" src="https://user-images.githubusercontent.com/16362473/28407880-5591882c-6d68-11e7-8f1f-707566cc8930.png">

子组件counter.wpy:(prop加个test，plus方法里加一行代码更改test：
<img width="346" alt="2017-07-20 4 25 47" src="https://user-images.githubusercontent.com/16362473/28407909-72141e74-6d68-11e7-831f-7f8ac73386d6.png">

<img width="448" alt="2017-07-20 4 25 59" src="https://user-images.githubusercontent.com/16362473/28407904-6b1a1b5a-6d68-11e7-81a4-858228ef0307.png">

在模拟器上点击计数器，可以看到控制台打印myTest旧值：xxx，myTest新值：xxx。但是真机调试（Iphone7及其他机器）都没有看到打印。
请指教，阿里嘎多！

**Comment by Gcaufy** [comment]
@smart-Jenny #270
