### ISSUE TITLE
component组件无法响应onReady、onShow、onReachBottom等微信原生事件

### ISSUE THREAD

**Issue by shellteo** [wepyjs/wepy#269]
想做一个下拉刷新组件，但是component无法响应onReachBottom事件，分析了你的源码没有找到解决办法，请问这个怎么解决？

**Comment by landn172** [comment]
看了下源码，只响应onLoad事件。
推荐你用事件广播来实现
https://wepyjs.github.io/wepy/#/?id=%e7%bb%84%e4%bb%b6%e9%80%9a%e4%bf%a1%e4%b8%8e%e4%ba%a4%e4%ba%92

**Comment by Gcaufy** [comment]
@shellteo 页面响应 onReachBottom, 然后再通知到子组件

**Comment by shellteo** [comment]
恩，我也是在page中的onReachBottomn事件通知component
/page.wpy
```
onReachBottom() {
      this.$invoke('scrollView','reachBottom');
 }
```
在用组件的自定义事件配合slot做组件的内容分发
```
<scrollView title="mytitle" @toBottom.user="lower">
</scrollView>
```

/.scrollView.wpy
组件中需要响应reachBottom事件
```
reachBottom(){
      this.$emit('toBottom');
};
```
