### ISSUE TITLE
picker-view阻止冒泡

### ISSUE THREAD

**Issue by HughDai** [wepyjs/wepy#28]
page用到scroll-view，嵌套了picker-view组件，但是在滑动picker-view时报异常Unable to preventDefault inside passive event listener due to target being treated as passive，也尝试给picker-view绑定了各种catch开头的事件阻止冒泡，请问大牛这种情况怎么处理

**Comment by HughDai** [comment]
已解决

**Comment by agoodcoolman** [comment]
@HughDai  朋友怎么解决的啊
