### ISSUE TITLE
wepy new project之后build --watch并不能实时更新

### ISSUE THREAD

**Issue by 18601673727** [wepyjs/wepy#285]
该关的都关了，目前只能通过在开发者工具中重新导入项目才行

**Comment by Gcaufy** [comment]
并没有出现过这种问题。

**Comment by 18601673727** [comment]
那你们真得多测测了。

**Comment by Genuifx** [comment]
@18601673727 偶尔也会遇到这个问题，一般是微信开发者工具的缓存，注意下升级开发者工具的别中途取消了，会引发这个问题，另外尽量先watch再打开开发者工具

**Comment by 18601673727** [comment]
首先顺序和取消两种情况在我这里没有，其次清缓存是没有用的两种都清过，错误提示依然是xxx.wxml文件编译失败

**Comment by Genuifx** [comment]
@18601673727 上一次我发生这种情况下是因为mac更新一半被我强退了工具，后来我重装了开发者工具就好了～

**Comment by lx307697527** [comment]
我也遇到了,编译后并没有报错,但是样式没有作用,只有退出后,重启wepy的build才行.有什么好的解决办法吗?

**Comment by Gcaufy** [comment]
@lx307697527 
我并没有遇到类似问题，可以看一下dist内是否生成正确文件，如果dist里的文件都正确那可以是开发者工具的一些问题。

**Comment by lx307697527** [comment]
dist里面没有变,还是原来的文件

**Comment by Gcaufy** [comment]
@lx307697527 是否在讨论群中？可以在群里@我。

**Comment by lx307697527** [comment]
没有 我加一下吧

**Comment by Gcaufy** [comment]
@lx307697527 添加微信`gcaufy_helper`

**Comment by Chaunjie** [comment]
@lx307697527 你解决了吗，我也碰到类似的问题
