### ISSUE TITLE
build之后npm 包的文件很大怎么优化

### ISSUE THREAD

**Issue by qfgyd2004** [wepyjs/wepy#29]
编译为小程序代码后，npm的依赖文件包比较大，请问如何优化？

**Comment by Gcaufy** [comment]
开启压缩

**Comment by qfgyd2004** [comment]
npm包是压缩过的，压缩以后在1.6M太大了

**Comment by Gcaufy** [comment]
不会压缩以后还是1.6M的。你看看是哪里出问题了？或者发我你的NPM包。

**Comment by Gcaufy** [comment]
1.4.1版本大幅减少npm体积。
参见1.4.1 [CHANGELOG](https://github.com/wepyjs/wepy/blob/master/CHANGELOG.md#141-2017-01-26)

**Comment by Gcaufy** [comment]
1.43版本减少约200多kb的npm体积。
