### ISSUE TITLE
请问为什么叫做WePY呢

### ISSUE THREAD

**Issue by maple5233** [wepyjs/wepy#290]
好奇了很久 难道是Wechat Page Yeah？

**Comment by Gcaufy** [comment]
最初想定义一个后缀，第一个出现在脑海里的文件后缀为 *.cpp，于是想取名为 *.wpp，百度一下，发现wpp内容太多，于是便改为 *.wpy。于是框架名就叫 WePY。取名没想那么多，简单，好记，没被注册，仅此而已。唯一的遗憾就是PY结尾老让人误解与Python有关。

**Comment by maple5233** [comment]
原来是这样 感谢科普 不过确实比较尴尬的是有个叫webpy的框架。。。
