### ISSUE TITLE
目前版本可以把项目 build 成 web 版了吗？

### ISSUE THREAD

**Issue by baijunjie** [wepyjs/wepy#298]
看到初始化生成的 wepy.config 中有这个选项了，但是文档中还是没有提到这个功能，不清楚如何实现？
![06e89ec7-be16-432d-8bf0-cca3b56f3056](https://user-images.githubusercontent.com/7956480/28952551-7e84e89e-7904-11e7-97a3-bd25bce6c64d.png)

**Comment by Gcaufy** [comment]
目录有预览版，
可以尝试 `wepy build --output web`
