### ISSUE TITLE
js 不能外联代码

### ISSUE THREAD

**Issue by shinlyli** [wepyjs/wepy#3]
.wpy文件中的script中的src不可用    一用就报错

**Comment by Gcaufy** [comment]
看到了，明天修复。先暂且用内联的哈~

**Comment by shinlyli** [comment]
谢谢

**Comment by Gcaufy** [comment]
fixed: https://github.com/wepyjs/wepy-cli/commit/6523351ff005ba2a1e971abaf49d3512e560208a 

下一个版本`1.1.8`发布时会解决这个问题，留意最新CHANGELOG

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy-cli/commit/b0a8b1f8f1b962bb8428c3b099dc53d880374524
