### ISSUE TITLE
typeError 在IOS 上, JSON.stringify can not  serialize cyclic structures

### ISSUE THREAD

**Issue by wangrqsh** [wepyjs/wepy#301]
图片贴不上来，
所以我贴了图片七牛链接，一个微信系统版本一个错误，没有调用接口请求，也没有处理json的代码，就是有这个错误
http://otkmn6s46.bkt.clouddn.com/image/debug/IMG_0863.PNG
http://otkmn6s46.bkt.clouddn.com/image/debug/IMG_0864.PNG

**Comment by Gcaufy** [comment]
找找看看代码中是不是有打一些console.log

**Comment by cz848** [comment]
webpack有自动清除console.log的插件，目前wepy有考虑加吗？

**Comment by Gcaufy** [comment]
有个replace插件可以实现这个的。

**Comment by Gcaufy** [comment]
@wangrqsh 解决了？怎么解决的？

**Comment by wangrqsh** [comment]
@Gcaufy 按你说的删掉console.log(),就不报这个错了，但是这样就没法打印日志调试了

**Comment by Gcaufy** [comment]
@wangrqsh 找出来哪个console.log 的问题，应该那个console.log打印了一个循环引用的Object.
console.log还可以用，你只要避免打印循环引用的Object就没有问题。

**Comment by wangrqsh** [comment]
@Gcaufy 好的，我稍后再排除看看确定一下是哪里打印了 循环引用的Object
