### ISSUE TITLE
需要多次执行的animation只会执行一次

### ISSUE THREAD

**Issue by vhyme** [wepyjs/wepy#302]
在点击事件或在setInterval()回调中，用wepy.createAnimation()设置执行某个animation，如果每次animation的数据相同，动画将只会执行一次，从第二次点击或者第二次interval到来时开始，动画将不会执行（即使每次都调用`$apply()`）。

这个代码本来在小程序原生没有问题，移植到wepy的过程中发现问题。个人感觉应该跟脏数据检查有关吧，对于animation数据没有变化的情况，微信的逻辑应该是在setData()中强制触发动画重新运行，但是wepy这里因为脏数据检查不通过，不会触发setData，导致动画不会重新运行。

<img width="1440" alt="wx20170805-210621 2x" src="https://user-images.githubusercontent.com/5051300/28995682-45683cd6-7a22-11e7-9651-269e34a0eb16.png">

**Comment by Gcaufy** [comment]
在wepy中，没有改变的数据不会做setdata处理。
有两种办法解决
1. 故意改变一点无关紧要的数据，让脏检查运行。
2. 用this.setData(this.$prifix + k, value) 试试

**Comment by vhyme** [comment]
emmm，我目前是用第二种方法暂时解决的，不过还是希望wepy对animation单独做判断处理吧

**Comment by Gcaufy** [comment]
刚用你的代码测试了一下，
加一句代码 就可以解决问题。
```
this.animationData = animation.export();
this.animationData.t = +new Date();
this.$apply();
```

如果从框架层面去解决这个问题不太好弄，animation.export() 就是一个数组，没有很好的办法去判断这个数组就是动画数组。
能想到比较合理的办法就是我自己单独封装一个animation方法，但这样实现起来比较复杂。所以暂时先不从框架层面去解决这个问题了。或者你有比较好的办法么？

**Comment by Hideer** [comment]
TypeError: this.animation.rotate is not a function，在wepy中使用animation出现这个错误，ps（将animation使用使用在组件中不行么）
