### ISSUE TITLE
有没有文件清除和copy的npm包？

### ISSUE THREAD

**Issue by cz848** [wepyjs/wepy#304]
以前经常用于在dist目录里清除和copy文件，在wepy里面没有发现，所以现在只能手动copy目录了。请问目前有没有这样的插件？

**Comment by Gcaufy** [comment]
手动copy目录是什么意思 ？

**Comment by cz848** [comment]
指images和icons这样的资源目录，要手动copy到dist里面

**Comment by Gcaufy** [comment]
images, icons 都是会自动copy进dist的。不需要手动Copy

**Comment by cz848** [comment]
那应该没有自动clean吧，我记得我把文件换个目录，dist就没有清掉。
