### ISSUE TITLE
脚手架生成的文件没有默认对小程序提供的api做promise处理

### ISSUE THREAD

**Issue by xiaomingplus** [wepyjs/wepy#305]
文档里：
使用Promise： 框架默认对小程序提供的API全都进行了 Promise 处理，甚至可以直接使用async/await等新特性进行开发。

实际上需要显式的在app.wpy的constructor里面：

            this.use('promisify');
才可以。
建议修改文档或者修改脚手架的模板吧

**Comment by cmzz** [comment]
😆 感谢提醒，被坑了一下午。。

**Comment by Gcaufy** [comment]
@xiaomingplus 
模板里的代码默认是使用了callback形式。
