### ISSUE TITLE
globalData 在别的文件里怎么用？

### ISSUE THREAD

**Issue by xueenda** [wepyjs/wepy#31]
如题
给个例子 谢谢

**Comment by Gcaufy** [comment]
this.$wxapp 可以取到app
所以this.$wxapp.globalData 就是你定义在 app里面的globalData

**Comment by jiayx** [comment]
我在测试的时候发现其他页面里 this.$wxapp.globalData 取不到，要这样才行 this.$wxapp.$app.globalData
是新版有改动吗？this.$wxapp 下只有方法，没有属性。

**Comment by delayhsiao** [comment]
@jiayx 少年，你试试this.$parent.globalData

**Comment by jiayx** [comment]
这个可以。。回复好快，多谢了！

**Comment by delayhsiao** [comment]
@jiayx 怪github，给我推邮件……我也不想的（摊手）

**Comment by Gcaufy** [comment]
@jiayx 
如果当前组件是page，那么`this.$parent`是$app
如果当前组件是component, 那么`this.$parent`是父层component，`this.$root`是顶层的page，所以你可以这么写`this.$root.$parent`

另外还有一种方法：`wepy.$instance` 也可以

**Comment by jiayx** [comment]
@Gcaufy OK，了解了，回答的很详细，非常感谢！

**Comment by farzer** [comment]
$instance 的api我在官网文档找不到
