### ISSUE TITLE
使用最新版本打包上传后，系统默认启动页不对

### ISSUE THREAD

**Issue by hareluya** [wepyjs/wepy#310]
在app.json的pages数组看到的是A，
但是在手机端看到的 On app route却是B路径，
求解。。。

**Comment by Gcaufy** [comment]
版本号？
问题描述可以更具体一些么？给出一些示例代码参考

**Comment by coolhwm** [comment]
预览版首页的话，可以在发布页面配置一下首页

**Comment by BranceLee** [comment]
app.wpy 中
config ={[
  // 将调整的页面放在第一个位置就行
]}
