### ISSUE TITLE
.wpy文件中注释掉一个view不生效

### ISSUE THREAD

**Issue by aben1188** [wepyjs/wepy#312]
.wpy文件中wxml部分，注释掉一个view，dist目录对应的wxml文件中发现也确实注释掉了，但实际上并不生效，在开发者工具中调试发现wxml中依然存在这个view。重启开发者工具、在开发者工具中删除项目再重建该项目都不能解决。

只能通过ctrl+c退出命令行自动编译，然后再重新执行wepy build --watch后才生效。

据深大的树洞开发者Jason说，在component嵌套较多的情况下，这种情况就会存在。

还望能尽快修复该问题。

**Comment by Gcaufy** [comment]
1. 无法复现问题。
2. 如果dist目录生成不对，那是wepy问题，如果dist目录内容是对的，但是小程序依然存在这个问题，那这就是小程序本身的问题了。
3. 如果wepy在编译生成dist时把注释全去掉，这样是不是能解决问题呢？不过这是另外一个问题。

**Comment by aben1188** [comment]
在less嵌套较深的情况下，也存在类似的问题

**Comment by Gcaufy** [comment]
能给出复现代码么？

**Comment by wut1** [comment]
我也遇到了这种问题,有解决方案吗
