### ISSUE TITLE
多入口配置方式

### ISSUE THREAD

**Issue by jyear** [wepyjs/wepy#314]
作为第三方小程序开发商，很多时候组件这些会公用，然后具体小程序在src目录下，打包生成的文件里面按小程序不同入口进行打包npm文件夹生成到项目下，这个如何配置，我查找config没法配置，看源码，会在compolier-script里面 因为不清楚作者打包依赖的具体流程，不好改动

**Comment by Gcaufy** [comment]
抱歉，暂没有支持的打算
