### ISSUE TITLE
bug: npm安装组件依赖时会出现路径问题

### ISSUE THREAD

**Issue by afeiship** [wepyjs/wepy#315]
我项目中依赖这个组件：https://github.com/afeiship/wepy-uploader
wepy-uploader，依赖于wepy-removeable

> 利用npm run dev运行项目，有问题的路径如下：
my-project-/dist/npm/wepy-uploader/dist/index.wxss

> wepy-cli版本：1.5.7

```scss
@import "./../../../src/npm/wepy-removeable/dist/index.wxss";
```

**Comment by Gcaufy** [comment]
See: https://github.com/wepyjs/wepy/issues/303

**Comment by starzhy** [comment]
hello ，1.7.2-alpha2 使用过程中依然遇到这个问题。

举例：单文件组件 wepy-popup-picker  依赖  单文件组件 wepy-popup  ， 编译后会出现wxss路径出错的情况（注：组件均是以npm安装 引入的方式，用本地路径的情况不会）
