### ISSUE TITLE
建议：官方出一个template的项目

### ISSUE THREAD

**Issue by afeiship** [wepyjs/wepy#316]
我现在写了个generator，是用来开发组件的，
> 现在还只是内测，大家不要去使用

https://github.com/afeiship/generator-wepy-component

不过，有个问题，如果官方升级了wepy里的template，我这个也不能及时同步，建议官方出一个template的项目，这样，我们这种就可以直接git clone那个template项目

**Comment by Gcaufy** [comment]
666
https://github.com/wepyjs/wepy-weui-demo
https://github.com/wepyjs/wepy-wechat-demo
这两个可以么
