### ISSUE TITLE
组件传值真机测试出现问题

### ISSUE THREAD

**Issue by CNJSer** [wepyjs/wepy#317]
`<comment :show.sync="comment" eventName="comment">`
`----<view class="comment-header" slot="header">`
`-------<icon></icon>XXXXXXXXX`
`----</view>`
`----<view class="comment-cont" @tap.stop="changeStar">`
`--------<view wx:for="{{commentStar}}" wx:key="{{index}}" wx:for-index="indexs" wx:for-item="items" class="comment-cont-item">`
 `--------<text>{{items.text}}</text>`
` --------<view>`
`------------<icon data-id="{{indexs}}" data-index="{{index}}" wx:for="{{items.star}}"  wx:key="{{index}}" class="comment-full"></icon>`
`------------<icon data-id="{{indexs}}" data-index="{{index + items.star}}" wx:for="{{5 - items.star}}" wx:key="{{index}}" class="comment-empty"></icon>`
`--------</view>`
`----</view>`
`---</view>`
`</comment>`
这是调用的一个弹窗组件

`<template>`
`<view class="popup-mask" wx:if="{{show}}" @tap="hide" @touchmove.stop="stopPropagation">`
`---<view class="popup-middle" @tap.stop="stopPropagation">`
`------<view class="popup-header">`
` ---------<slot name="header"></slot>`
`------</view>`
`------<slot></slot>`
`------<view class="popup-footer">`
`--------<button @tap="hide" plain class="popup-cancel">取消</button>`
`--------<button @tap="sure" class="popup-sure">确定</button>`
`------</view>`
`---</view>`
`</view>`
`</template>`

`<script>`
`import wepy from 'wepy'`
`export default class ModalPopup extends wepy.component {`
`---props = {`
`------show: {`
`--------type: Boolean,`
`--------default: false,`
`--------twoWay: true`
`------},`
`------eventName: {`
`--------type: String,`
`--------default: 'king-popup-sure'`
`------}`
`---}`
`---methods = {`
`------hide () {`
`---------this.show = !this.show`
`------},`
`------sure () {`
`---------this.$emit(this.eventName)`
`------},`
`------stopPropagation () {`
`---------return false`
`------}`
`---}`
`}`
`</script>`

这是弹窗组件

`showComment () {`
`----this.comment = !this.comment`
` },`
通过设置调出弹窗。

在开发者工具里面是正常的，但是在真机上面测试无法正常显示出弹窗。打印出来的控制值是正常的，但是页面没有渲染。默认传的值可以显示或隐藏，但是动态设置的就不能控制弹窗的显示和隐藏。传值的地方也设置了.sync了。

在组件中点击按钮 通过$emit通知页面  在开发者工具里面是正常的  但是在真机测试的时候，会报错。
`thirdScriptError
Converting circular structure to JSON; at "page/company" page $comment$sure function
TypeError: Converting circular structure to JSON at Object.b [as publish] (X5JavaBridge:24:5776)`

求问是这是什么情况

**Comment by CNJSer** [comment]
。。代码怎么调缩进

**Comment by Gcaufy** [comment]
根据经济，工具OK真机上不行通常中没有关闭压缩上传导致的。
`Converting circular structure to JSON` 通常是由于 console.log 导致 的。
