### ISSUE TITLE
dirty checking的一个bug

### ISSUE THREAD

**Issue by jiahao1889** [wepyjs/wepy#319]
目测不是很常见的需求所以close了吧

**Comment by Gcaufy** [comment]
有没有具体的示例？

**Comment by jiahao1889** [comment]
嗯，使用类似leancloud这样的封装了js sdk的后端服务，他们query回来的object实际attr是存在obj.attributes里，但是显示时候会按照toJSON之后的方法写在Mustache里
具体可以看这里
https://leancloud.cn/docs/weapp.html#数据绑定
正常访问这个obj的content应该是写todo.get('content')，在小程序的mustache里只需要写toJSON后的{{todo.content}}

也就是js里面的obj是
{
attributes:{title:..., content:...},
objectId:...,
get:function...,
...
}
而调试工具里appdata里的obj是
{
title:...,
content:...,
objectId:...,
...
}

**Comment by Gcaufy** [comment]
如果这个Object 无法被 dirty check 识别， 那可以把他转化一下转成可以识别的啊。

**Comment by jiahao1889** [comment]
这个obj里面有一些继承的方法在toJSON之后就没有了，而这些方法是很常用的
我想说的主要是，只依赖原本的object的diff来构造传给setData的data变化是不妥的
因为小程序的渲染引擎会把data里的object转成toJSON之后在渲染线程里画
这样如果有object本身结构和toJSON之后结构有差异的按理说都会出现这个问题

上面举的例子，如果我在原生写法里需要修改其中的数据（以及在服务器上的数据）
直接
this.data.myobj.set('title', 'newtitle')
this.data.myobj.save()
this.setData({myobj:this.data.myobj})    //其实等同于this.setData({'myobj.title':'newtitle'})
是可以刷新显示的
但是用wepy
this.myobj.set('title', 'newtitle')
this.myobj.save()
this.$apply()
就不会刷新显示出新的title

**Comment by Gcaufy** [comment]
明白你的意思，何不换一种方式
this.myobj = myobj.toJSON();
这样myobj改变后，还是会触发脏检查的。

**Comment by jiahao1889** [comment]
嗯，如果这样写了下次我想写this.myobj.set('title', 'anothertitle');this.myobject.save();时候就没有这些方法了。。。
