### ISSUE TITLE
组件获取不到传入的prop是原始类型Boolean的值

### ISSUE THREAD

**Issue by LukeLin** [wepyjs/wepy#320]
`<com a="{{true}}"></com>`
或者
``<com :a="{{true}}"></com>``
这两种方式在组件里都获取不到值

**Comment by Gcaufy** [comment]
```
<com a="true"></com>
```

**Comment by LukeLin** [comment]
试过了，这种方式也不行

**Comment by Gcaufy** [comment]
https://wepyjs.github.io/wepy/#/?id=props-%e4%bc%a0%e5%80%bc

**Comment by Gcaufy** [comment]
type定义为String, 静态类型传值只能为String， 没有Object, Number, Boolean之类 的。

**Comment by krimeshu** [comment]
按照 demo 里的组件写法，可以这样写：

```javascript
  props = {
    a: {
      type: [Boolean, String],
      coerce(v) {
        return typeof v === 'string' ? JSON.parse(v) : v;
      }
    }
  };
```

**Comment by booboom** [comment]
问题没有解决啊，还是这个问题，上面的方法都试过了，子组件里还是取不到父组件data里默认的Boolean值，是undefined。
