### ISSUE TITLE
两级页面为同一路由时，后者数据覆盖前者

### ISSUE THREAD

**Issue by bluesky12** [wepyjs/wepy#322]
问题示例：
    商品详情页A -> 商品详情页B -> 返回A -> 点击购买，下单数据为B的数据，而不是A的数据

问题描述：
    使用navigateTo打开新页面时，若有两级页面路由相同，则后打开的页面实例会覆盖前者，导致返回前者
    时，虽然样式上仍保留离开时的模样，但data已经完全被覆盖，交互时数据异常。

简易演示demo：
```javascript
<template>
  <view>{{param}}</view> <!--数据在页面中的展现-->
  <button @tap="onBtn">go</button>  <!--打开一个新的同路由页面-->
</template>
<script>
  import wepy from 'wepy';
  export default class extends wepy.page {
    data = {
      param: '' //页面数据
    }
    computed = {}
    methods = {
      onBtn(){
        wx.navigateTo({
          url: '/pages/index/index?param=modified'  //打开一个新的同路由页面，但指定不同的数据初始值
        })
      }
    }
    onLoad(options) {
      this.param = options.param || 'default';  //原页面数据值为'default'，新页面值为'modified'
    }
    onShow(){
      console.log('onShow this.param', this.param); //打印数据
    }
  }
  /**
   * 操作过程：              打开本页面 -> 点击go按钮，打开一个新的本页面->点击返回
   * 实验现象：
   *   页面数据展示依次为：   default -> modified -> default，符合逻辑
   *   控制台数据打印结果为： default -> modified -> modified，表明返回时，数据并未恢复离开时状态！
   */
</script>
```

**Comment by Gcaufy** [comment]
navigateTo 到同一页面的时候， onLoad不会执行吧。所以数据也会是一样的。

**Comment by bluesky12** [comment]
@Gcaufy navigateTo到同一页面时，onLoad是会重新执行的，用代码检验过了。
而且issue中示例代码用小程序原生方式实现时，返回时样式和控制台打印的数据都能正常保持原样。

**Comment by Gcaufy** [comment]
@bluesky12 你的wepy版本是？如果是1.5.8以下的才会出现上述问题。

**Comment by bluesky12** [comment]
@Gcaufy 就是1.5.8额。
```cmd
npm ls --depth=0
+-- babel-eslint@7.2.3
+-- babel-plugin-syntax-export-extensions@6.13.0
+-- babel-plugin-transform-decorators-legacy@1.3
+-- babel-plugin-transform-export-extensions@6.2
+-- babel-preset-es2015@6.24.1
+-- babel-preset-stage-1@6.24.1
+-- cross-env@5.0.1
+-- eslint@3.19.0
+-- eslint-config-standard@7.1.0
+-- eslint-friendly-formatter@2.0.7
+-- eslint-plugin-html@2.0.3
+-- eslint-plugin-promise@3.5.0
+-- eslint-plugin-standard@2.3.1
+-- wepy@1.5.8
+-- wepy-async-function@1.4.4
+-- wepy-com-toast@1.0.2
+-- wepy-compiler-babel@1.5.1
+-- wepy-compiler-less@1.3.10
+-- wepy-eslint@1.5.2
`-- wepy-plugin-uglifyjs@1.3.6
```

**Comment by Gcaufy** [comment]
我刚用生成出来的测试demo测试 没有问题的额。

**Comment by bluesky12** [comment]
@Gcaufy 我刚把所有包更新为最新版，问题还是出现额

操作过程：
1. 升级wepy-cli为1.5.8
2. wepy new demo新建一个空项目
3. 把src/pages/index.wpy替换为issue中代码，并将第15行navigateTo路径'/pages/index/index'改为'/pages/index'
4. 在wepy.config.js中eslint设为false
5. npm run dev

环境：
1. 微信开发者工具 0.20.191900，基础库版本1.4.3，关闭“ES6转ES5”、“样式自动补全”、“代码压缩上传”，开启“不校验证书”
2. node v6.9.1， npm 3.10.9
3. windows  7

**Comment by Gcaufy** [comment]
复现步骤很详细，感谢。

> 打开本页面 -> 点击go按钮，打开一个新的本页面->点击返回

点击返回时不会执行onLoad， 也就不会初始化数据。所以page的数据还保持为modified.

每个page都是一个实例，在小程序运行时实例化的，并且只有一个，进入页面后，在onLoad中初始化数据。再打开页面时，page实例还是那一个，只是在onLoad中重新初始化了一下数据。但当你点返回时，回到的还是那个page实例，不过返回没有执行onLoad, 所以数据还在。

这里建议写onUnload处理一下吧。个人认为这个应该不算是一个BUG吧。而且没有好的应对措施。

**Comment by bluesky12** [comment]
@Gcaufy 辛苦，谢谢。

目前我们修改路由策略，避免出现两级页面路由相同，暂时规避了这个问题。

只是同样的代码，以小程序原生方式实现，返回时也不触发onLoad，但打出来的数据却能正常恢复为default。个人感觉页面单实例似乎不是小程序的限制，更像是ES6模块符号链接特性带来的问题。

并且这类需求是实际存在的，比如：商品详情页-猜你喜欢-另一个商品详情页，他人估价结果页-我也要测-自己估价结果页（此时“我也要测”按钮改为“我要分享”，避免路由循环）等。

所以，如果条件允许的话，感觉还是可以优化一下的。

**Comment by Gcaufy** [comment]
与小程序不一样的是wepy中有个全局的page实例，原生小程序中没有，现在数据挂在这个全局实例下的。。
一定要解决这个问题，就加个onUnload也不会很复杂的。

**Comment by bluesky12** [comment]
好的，辛苦解答，谢谢。

**Comment by LewisLZ** [comment]
@Gcaufy 跳转到第二个详情页的时候，会执行第二个详情页的 onLoad，但不会执行第一个详情页的 onUnload。
还有什么好办法可以解决吗？

多谢

**Comment by DSKcpp** [comment]
这是一个很严重的问题，请问有想好解决方案吗？

**Comment by Gcaufy** [comment]
@DSKcpp 明白这里的问题，在这个版本中page是在一开始就实例化好了的。如果要解决这个问题就是需要修改page 的实例化的时间点，这个改动影响太大了。因此在这个版本里不会去对这里做调整。在2.x的新版本里是完全没有这个问题的。

**Comment by jswxwxf** [comment]
我也遇到了这个问题，太严重了~

**Comment by bluesky12** [comment]
getCurrentPages可以拿到原生页面实例，从原生页面实例的data中可以恢复出wepy实例的data。
参考代码：
```js
/**
 * 从原生页面实例中恢复wepy页面实例数据
 * @param wxPage 原生页面实例
 */
export function pageRestoreHandler(wxPage) {
  let path = wxPage.route || wxPage.__route__;
  let wepyPage = wepy.$instance.$pages[path];
  dataRestoreWx2Wepy(wepyPage, wxPage.data);
}

/**
 * 从原生页面数据中恢复wepy页面/组件实例数据
 * @param {object} compThis wepy页面/组件根实例
 * @param {object} data  原生页面数据
 * @param {string} compPrefix  根实例数据在原生页面数据中的前缀，如： ''(页面实例）、'$PageFrame$'(页面下的PageFrame组件）、'$PageFrame$BackHome$'（PageFrame组件下的BackHome组件）
 * @return void 会将根实例及其所有后代组件实例 数据恢复为与原生页面数据保持一致的状态
 */
function dataRestoreWx2Wepy(compThis, data, compPrefix='') {
  //恢复组件自身的数据
  let selfData = {};
  for (let prop in data) {
    if (prop.startsWith(compPrefix) && !prop.substring(compPrefix.length).includes('$'))
      selfData[prop.substring(compPrefix.length)] = data[prop];
  }

  Object.assign(compThis, selfData);
  compThis.$apply();

  //恢复后代组件的数据
  for (let childName in compThis.$com) {
    dataRestoreWx2Wepy(compThis.$com[childName], data, (compPrefix || '$')+childName+'$');
  }
}
```
有个工具封装了这个过程，有兴趣可以看下：https://github.com/zhuanzhuanfe/fancy-mini/blob/master/docs/%E6%97%A0%E9%99%90%E5%B1%82%E7%BA%A7%E8%B7%AF%E7%94%B1%E6%96%B9%E6%A1%88.md
