### ISSUE TITLE
watcher对于“object内指定key”及view内部控件value变动的监听

### ISSUE THREAD

**Issue by sherllochen** [wepyjs/wepy#324]
1. https://wepyjs.github.io/wepy/#/?id=watcher 此处范例只演示了对于integer的监听。未说明对于object内部指定key的监听方式。我尝试了以下方式：
'order.language' (newVal,oldVal){}  并没有成功实现监听。

2. https://github.com/wepyjs/wepy/blob/master/packages/wepy-cli/templates/template/src/components/counter.wpy#L48-L52 此处范例演示的变量监听流程是view中定义tap事件，tap事件被触发修改变量。
view中控件value直接绑定为变量，然后用户在控件中输入值改变变量值，按照我自己的实验，watcher无法直接监听到该变量的变动，只能通过类似范例的方式，在中间在加一层bindchange来修改变量值。

是否watcher无法实现以上两种情况的监听？或者是文档不全没有说明具体的使用方式？

**Comment by Gcaufy** [comment]
1. 支持Object，不过是直接写`order`而不是`order.language`
2. 不存在又向绑定机制，所以你的输入值无法感知到，需要自己写bindchange
