### ISSUE TITLE
模板slot实现内容分发

### ISSUE THREAD

**Issue by sheweichun** [wepyjs/wepy#33]
wepy貌似不支持slot功能 这样组件化受到很大的限制 不知道是不是我用的不对

**Comment by Gcaufy** [comment]
暂时不支持，slot功能可以被实现，后面版本会考虑实现。

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy/commit/03b872b221de95fb9f038c500298fa628b0d1ff2

已实现，等待1.4.2版本发布

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy#组件内容分发slot
