### ISSUE TITLE
template lang="pug" 时，wx:if="{{index < 5 }}" 编译会报 Error

### ISSUE THREAD

**Issue by wulunyi** [wepyjs/wepy#330]
![image](https://user-images.githubusercontent.com/15170275/29365524-eec7492a-82c9-11e7-95b1-5d1b883b1cb4.png)
![image](https://user-images.githubusercontent.com/15170275/29365538-f5bdb98a-82c9-11e7-95ba-6ce2dc3c599c.png)

**Comment by scott-leung** [comment]
我也遇到了……只能暂时换成!(a>=b)这种方式解决先
