### ISSUE TITLE
安卓手机预览请求时报错：{errMsg:request:fail ssl hand shake error}

### ISSUE THREAD

**Issue by SuperJolly** [wepyjs/wepy#331]
iphone预览项目时请求正常，也没有报ssl证书方面的错误，安卓手机预览就报了握手失败，请问wepy的request的GET请求是严格大写的‘GET’ ？

**Comment by SuperJolly** [comment]
@sonicG

**Comment by Gcaufy** [comment]
这个自己尝试一下不就知道？
不过你这个错误应该跟 GET 无关吧。应该是服务证书问题。

**Comment by SuperJolly** [comment]
#### 该问题已解决。原因是请求站点Nginx服务器未配置到中间证书，安卓手机不能通过此url获取到comodo中间证书。
![image](https://user-images.githubusercontent.com/13775060/29458919-00ec5eac-8454-11e7-860f-42f9903f96f4.png)
#### `Windows、IOS、MAC都支持这种证书获取方式，但Android不支持这种方式，所以，如果我们仅依靠这种方式来获得中间证书，就无法在Android系统上建立可信连接。`
配置完成后安卓手机便可以正常访问了(此时ssl_certificate 设置的为(xxxx.ca-bundle),即包含根证书+中间证书的证书文件)，但是安卓5.0及以下版本的手机还是不成功，用浏览器访问站点，会提示“该证书来自并非可信的授权中心”，所以我们少加了域证书，所以我们需要把完整的证书链(或域证书)提供给ssl_certificate，可以设置为.pem或者.p7b。
![.pem文件生成地址]( https://www.myssl.cn/tools/merge-pem-cert.html)
![.p7b文件生成地址](https://www.myssl.cn/tools/merge-p7b-cert.html)

下面安利下小程序真机预览请求时ssl证书方面如何跳坑：![真机预览跳坑指南](http://www.wxapp-union.com/forum.php?mod=viewthread&tid=1909)、![ssl证书相关问题](http://www.wxapp-union.com/forum.php?mod=viewthread&tid=2980&fromuid=2)

![ssl证书与协议详细检测](https://www.ssllabs.com/ssltest/analyze.html)
![中间证书介绍](https://www.myssl.cn/home/article-0406-42.html)
![站点服务器和证书配置检测](https://www.qcloud.com/product/tools#userDefined12)
![ssl证书检测](https://www.myssl.cn/tools/check-server-cert.html)
![中间证书生成工具](https://www.myssl.cn/tools/downloadchain.html)
![TLS & SSL 快速进阶](https://www.villainhr.com/page/2016/10/26/TLS%20&%20SSL%20%E5%BF%AB%E9%80%9F%E8%BF%9B%E9%98%B6#CA 链式验证)
