### ISSUE TITLE
wepy.request在安卓机上返回值为null

### ISSUE THREAD

**Issue by sonicG** [wepyjs/wepy#332]
wepy.request在安卓机上返回值为null，请问是什么问题

**Comment by Gcaufy** [comment]
看一下WIKI

**Comment by sonicG** [comment]
是需要加
constructor () {
    super()
    this.use('requestfix')
 }
这段代码吗？但是我加了之后也没有生效，console.log(wepy.request)的值是还是null

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy/wiki/wepy%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8Promise

**Comment by sonicG** [comment]
首先谢谢您，我按照您说的修改了，也使用了promise的形式，但是问题还是没解决，在安卓机上wepy.request根本没有这个方法，返回值为null
我的代码是
wepy.login().then((res) => {
        console.log(wepy.request)
        if (res.code) {
          wepy.request({
            url: 'https://gy.lede.com/login.html',
            data: {
              code: res.code
            }
          })
          .then((res) => {
            console.log('login success')
          })
        } else {
          console.log('获取用户登录态失败！' + res.errMsg)
        }
      })
这样，这里的wepy.request在安卓机调试这里返回的是null，所以根本没有执行request请求，您能帮我看一下是什么问题吗？

**Comment by sonicG** [comment]
import wepy from 'wepy'
import Promise from 'promise-polyfill'

export default class extends wepy.app {
  constructor () {
    super()
    this.use('promisify')
  }
}
这段代码已经引入了

**Comment by sonicG** [comment]
ios是没有问题的

**Comment by sonicG** [comment]
问题已经解决了，多谢 @Gcaufy

**Comment by Gcaufy** [comment]
什么问题

**Comment by sonicG** [comment]
好像是我版本的问题，我刚刚升级了一下wepy的版本就可以了
