### ISSUE TITLE
希望适配支付宝小程序的打包

### ISSUE THREAD

**Issue by markalex25** [wepyjs/wepy#334]
支付宝小程序
https://mini.open.alipay.com/channel/miniIndex.htm

希望适配支付宝小程序的打包生成。

**Comment by Gcaufy** [comment]
有点方

**Comment by yale8848** [comment]
个人觉得wepy将来一定会打通微信、支付宝小程序的，这样wepy的价值会更高

**Comment by Gcaufy** [comment]
@yale8848 已经支持了。
https://segmentfault.com/a/1190000010741601?_ea=2403008

**Comment by yale8848** [comment]
:thumbsup::thumbsup::thumbsup:

**Comment by yunfengsa** [comment]
@Gcaufy 
新版本中 （2017-10-13）
Error in (undefined) ./npm/wepy-async-function/index.js
Module build failed: TypeError: Cannot read property 'length' of null
 @ ./app.js 51:0-45
 @ ./.tea/entryFiles-development/index$.worker.js
