### ISSUE TITLE
使用新版打包支付宝小程序，部分接口不兼容

### ISSUE THREAD

**Issue by BEIBEI123** [wepyjs/wepy#337]
如题，使用新版打包支付宝小程序，部分接口不兼容，比如我使用了缓存，提示未识别wx，要是能建立一个接口对应文档，在编译时自动替换就好了

**Comment by Gcaufy** [comment]
参考DEMO，使用wepy.getStorage

**Comment by hareluya** [comment]
请问会考虑支持支付宝小程序吗？

**Comment by Gcaufy** [comment]
https://segmentfault.com/a/1190000010741601?_ea=2403008

**Comment by hareluya** [comment]
@Gcaufy 
向你致敬！
