### ISSUE TITLE
watcher 无法监听 props 中的数据变化

### ISSUE THREAD

**Issue by wulunyi** [wepyjs/wepy#338]
能否支持在 watcher 在组件中能监听 props 中数据的变化呀

**Comment by Gcaufy** [comment]
不能，需要你把props赋值给data

**Comment by liuzhenji** [comment]
props在什么时候赋值给data呢？如果父组件传给子组件的props变化了，子组件不监听属性，怎么去赋值呢？要父组件再触发一个更新事件给子组件吗？

**Comment by agoodcoolman** [comment]
[other answer](https://github.com/Tencent/wepy/issues/647)
