### ISSUE TITLE
调试的时候引入外部scss报错：Error: Invalid CSS after "...eClamp($line) {": expected "}", was "{"

### ISSUE THREAD

**Issue by youpinyao** [wepyjs/wepy#339]
// 下面是我scss 文件的部分内容
@mixin lineClamp($line) {
  display: -webkit-box;
  -webkit-line-clamp: $line;
  -webkit-box-orient: vertical;
  overflow: hidden;
  white-space: normal;
}

**Comment by Gcaufy** [comment]
你的版本是？如果是1.5.8是存在一些问题，建议升级成1.5.9-0

**Comment by liujunchina** [comment]
@Gcaufy 升级 1.5.9-0 之后可以保证build的时候不报错，不过watch状态下不能实时编译了，需要重新运行 wepy build

**Comment by Gcaufy** [comment]
那个版本没有修改watch相关的代码，理论上不会出现问题的。
