### ISSUE TITLE
原生template如何转wepy组件？

### ISSUE THREAD

**Issue by grusirna** [wepyjs/wepy#343]
像wxparse使用template，想对它进行二次封装，像wepy组件一样调用。可以吗，怎么做

**Comment by grusirna** [comment]
经过研究是可以的，虽然没有很完善但是可以用了

**Comment by webKity** [comment]
请问下要怎么处理，能提供下思路吗，谢谢

**Comment by hou000123** [comment]
有没有小程序原生TEMPLATE作組件，反向編譯為WEPY 組件COMPONENT組件，這樣就不用重寫原生TEMPLATE，這樣不能重用之前的原生TEMPLATE的組件很不科學
