### ISSUE TITLE
希望可以支持 scss 背景图片自动base64

### ISSUE THREAD

**Issue by liujunchina** [wepyjs/wepy#344]
希望可以支持 scss 背景图片自动base64，不然背景图片很不方便

**Comment by Gcaufy** [comment]
这个是可以考虑用plugin的形式支持的。
已有一种实现：
https://github.com/xwxtwd/wepy-plugin-img2base64

**Comment by liujunchina** [comment]
@Gcaufy  插件的方法试过，会导致其他问题，后面改成专门一个 icon.less  ，通过 data-uri 转了

**Comment by holycharles** [comment]
为什么我的用不了 图片没有任何变化~

**Comment by EdwardZZZ** [comment]
我刚写了一个，带自动前缀和base64，可以参考一下

https://github.com/EdwardZZZ/wepy-plugin-parsecss
