### ISSUE TITLE
开启 async await 后热更新失效

### ISSUE THREAD

**Issue by zaxlct** [wepyjs/wepy#346]
最新的 wepy 版本，按照示例启用 async 和 await 后热更新失效

**Comment by Gcaufy** [comment]
不存在这个问题吧，这个我天天在用。

**Comment by zaxlct** [comment]
额，也许不是因为启用了 async 和 await 。总之热更新确实失效了。
代码变动的时候，终端打打印了监测日志，失效的原因很可能是我用了小程序开发工具的最新 beta 版。

**Comment by SuperJolly** [comment]
小程序最新版本热更新确实是有问题的

**Comment by Gcaufy** [comment]
什么问题？关闭原因是？

**Comment by SuperJolly** [comment]
可能是工具的问题，而不是wepy的问题，所以关闭了
