### ISSUE TITLE
编译后的内容太大，能否压缩一下啊

### ISSUE THREAD

**Issue by wangxiaochuang** [wepyjs/wepy#347]
编译后的内容已经快超过1M了，可不可以压缩一下啊

**Comment by ChenZerong** [comment]
1. 排查一下项目里面是不是包含太多静态文件，建议去除无用的静态文件，并把静态文件都传到CDN上直接引用。
2. 注意是用 `npm run build` 进行编译而不是使用 `npm run dev` 的版本，这两者在配置上是有一定区别的。

你提供的信息太少，暂时只能提供这些以供参考

**Comment by wangxiaochuang** [comment]
用npm run build 编译后确实小了很多，我是用wepy build编译的，非常感谢

**Comment by ChenZerong** [comment]
@Gcaufy close need.
