### ISSUE TITLE
支持async/await是否需要修改配置

### ISSUE THREAD

**Issue by SoyMeng** [wepyjs/wepy#35]
使用默认配置异常
![image](https://cloud.githubusercontent.com/assets/6083582/22683311/52a5333e-ed52-11e6-9b4a-0c849c41ece5.png)

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy/wiki/wepy%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8async-await
