### ISSUE TITLE
this.$invoke

### ISSUE THREAD

**Issue by KingJeason** [wepyjs/wepy#350]
能不能在 pageA页面中的a组件 调用 PageB页面的b组件呢?
相对路径该怎么写呢?
不管我怎么写都报这个错误
thirdScriptError
Cannot read property '$com' of undefined;at pages/query page $search$queryBook function
TypeError: Cannot read property '$com' of undefined``

**Comment by KingJeason** [comment]
我是这样写的 
this.$invoke('./index/index','hello');想调用 index页面的index方法.
刚看了下  $getComponent的实现
`
 path.forEach((s, i) => {
                    if (i === 0) {
                        if (s === '') {   //   /a/b/c
                            com = this.$root;
                        } else if (s === '.') {
                            // ./a/b/c
                            com = this;
                        } else if (s === '..') {
                            // ../a/b/c
                            com = this.$parent;
                        } else {
                            com = this.$getComponent(s);
                        }
`
为什么当s=== '.'的时候 com等于this呢?也就是这个组件本身么?

**Comment by Gcaufy** [comment]
跨页面是无法进行组件通信的。
