### ISSUE TITLE
遇到的一些小问题

### ISSUE THREAD

**Issue by krimeshu** [wepyjs/wepy#354]
尝试用 WePY 重构了现有小程序的某个界面，发现组件开发的体验已经很接近 vue.js 了，比原生小程序开发方便了很多。
但可能只是转译的关系，会受小程序原有的语法限制，有些地方略显繁琐或者奇怪。
有些小问题需要解答，不过问题比较散，不知道取什么主题好，就在这个 issue 里一个个列出来了。
希望作者有空时能看看，期待得到作者大大的回复~

**Comment by krimeshu** [comment]
### @customEvent.user 修饰符警告问题

在 `vs code` 内，`vetur` 会对 `.user` 的修饰符标注红色波浪线，提示错误：

```
message: ''v-on' directives don't support the modifier 'user'.'
at: '18,42'
source: 'vue-language-server'
```

是否有能做类似 `.eslintrc.js` 的配置，关闭这个规则的检测呢？

**Comment by krimeshu** [comment]
### 不同组件实例需要在 `components` 内反复声明

由于业务需要，我们某个界面上会有近10个组件实例，各自有些不同的实例属性，数据需要互相独立不干扰。

目前的写法需要这样处理：

```html
<template>
  <view>
    <child1 />
    <child2 />
    <child3 />
    <child4 />
    <child5 />
    <child6 />
    <child7 />
    <child8 />
    <child9 />
  </view>
</template>

<script>
  import wepy from 'wepy';
  import Child from './child';

  export default class Index extends wepy.page {
    components = {
      'child1': Child,
      'child2': Child,
      'child3': Child,
      'child4': Child,
      'child5': Child,
      'child6': Child,
      'child7': Child,
      'child8': Child,
      'child9': Child
    };
  }
</script>
```

其中 `components` 部分较为冗余，如果有另一个 `anotherChild` 也需要创建 10 个实例的话就更混乱了。

能否根据 `template` 内的声明，加入 `name` 属性来创建相关实例呢？个人认为会方便很多：

```html
<template>
  <view>
    <child name="child1"/>
    <child name="child2"/>
    <child name="child3"/>
    <child name="child4"/>
    <child name="child5"/>
    <child name="child6"/>
    <child name="child7"/>
    <child name="child8"/>
    <child name="child9"/>
  </view>
</template>

<script>
  import wepy from 'wepy';
  import Child from './child';

  export default class Index extends wepy.page {
    components = {
      'child': Child
    };
  }
</script>
```

**Comment by krimeshu** [comment]
### 组件属性的动态赋值不支持字面量绑定

这种情况暂不支持，需要手动从 String 转换，可能会有一定问题：

```html<template>
  <view>
    <child1 :descFields="['fieldA', 'fieldB']" />
    <child2 :descFields="['fieldA']" />
    <child3 :descFields="['fieldC']" />
    <child4 />
  </view>
</template>

<script>
  import wepy from 'wepy';
  import Child from './child';

  export default class Index extends wepy.page {
    components = {
      'child1': Child,
      'child2': Child,
      'child3': Child,
      'child4': Child
    };
  }
</script>
```

**Comment by SuperJolly** [comment]
同一组件实例引入过多时，可以用<repeat>标签来解决吧？

**Comment by Gcaufy** [comment]
感谢建议
>@customEvent.user 修饰符警告问题
这个我也没想到有什么好办法去解决，=。=

>不同组件实例需要在 components 内反复声明
这个点不错，实现起来成本也不高，后面我考虑一下看看能不能实现 。

>组件属性的动态赋值不支持字面量绑定
可以借助computed 来实现

**Comment by krimeshu** [comment]
感谢关注~

期待能采纳第二点的处理方案

> @customEvent.user 修饰符警告问题

关于这个问题，刚才发现使用 `pug` 编写的话，就不会出现告警提示了。

`pug` 应该是 `html` 的超集？直接修改 `lang="pug"` 暂时没发现什么问题。

> 组件属性的动态赋值不支持字面量绑定

是的，这个问题可以通过动态绑定 `data`/`computed` 来实现。但有些展示相关的常量属性放在 `template` 内会比较直观，也方便后期直接修改 `template` 调整显示内容，所以并不想放在下面的 `data`/`computed` 内。

目前是在组件内，对应 `props` 接受 `String` 参数后，`JSON.parse` 反序列化解析出字面量数据的，暂时没有太大问题。

**Comment by krimeshu** [comment]
### `wepy.mixin` 只会混合关键字，不会混合自定义方法？

```javascript
// mixin-test.wpy

import wepy from 'wepy';

export default class MixinTest extends wepy.mixin {
  foo() {
    console.log('MixinTest.prototype.foo');
  }
}
```

```javascript
// index.wpy

import wepy from 'wepy';

import MixinTest from 'mixin-test';

export default class Index extends wepy.page {
  mixins = [MixinTest];
  onLoad() {
    this.foo(); // => error: this.foo is not function
  }
}
</script>
```

**Comment by Gcaufy** [comment]
> 组件属性的动态赋值不支持字面量绑定

这个支持起来太复杂了，不一定能实现，所以先不考虑支持，有需要用 computed 替代。

> route

类似于PHP 的 __FILE__ 属性，可以调用，理论上后面不会废弃或者修改， $route 方法都依赖于这个属性

**Comment by Gcaufy** [comment]
@krimeshu 
> 不同组件实例需要在 components 内反复声明

刚才研究了一下，发现这个问题实现起来难度很大。
因为目前来说，template和script是分开编译的，我在初始化script中的组件时，我无法知道template中存在哪些组件。因此我需要在script中事先声明。

所以解决办法可能是
1. 扫描template中所有标签，发现非小程序官方标签的都标记为组件，并且根据name注入到script中。
2. script初始化时根据注入信息初始化组件。

这样就存在一个问题，我需要一个标签字典，来标记哪些是官方组件。如果官方有所更新后，那么使用wepy就会产生直接影响。

所以权衡实现难度与可维护性，暂时还是不考虑这个的实现。
还是让用户重复声明去避免这个问题吧。

**Comment by Gcaufy** [comment]
这里ISSUE比较多，如果还有其它建议，新开ISSUE讨论吧，这个就先关闭了。

**Comment by Zeus-Iqd** [comment]
@krimeshu 老铁加上lang="pug" ,报错是不报错了，可是代码高亮的效果不好，请问有其他解决方案吗？

**Comment by krimeshu** [comment]
@Zeus-Iqd 因为一些原因，这边后来没有采用 wepy 了，所以不知道有没有其他解决方案，Sorry

**Comment by YardWill** [comment]
@Zeus-Iqd 
替换Vetur使用这个插件可以解决这个问题
![image](https://user-images.githubusercontent.com/16497201/37078550-a870c708-221a-11e8-9361-b63a2c267090.png)

**Comment by LanCat** [comment]
在 vs code 内，vetur 会对 .user 的修饰符标注红色波浪线，提示错误： 你怎么解决的？？ 为啥我的其他文件没有  .user 但是在那一行还是会提示

**Comment by Zeus-Iqd** [comment]
在 2018-03-10 18:18:37，"LanCat" <notifications@github.com> 写道：


在 vs code 内，vetur 会对 .user 的修饰符标注红色波浪线，提示错误： 你怎么解决的？？ 为啥我的其他文件没有 .user 但是在那一行还是会提示

**Comment by Carrotzpc** [comment]
> 在 vs code 内，vetur 会对 .user 的修饰符标注红色波浪线，提示错误：

如果 vue 高亮插件用的是 `vetur` 的话，在对应项目的 `Workspace Settings` 中把 `vetur.validation.template` 设置为 `false` 就好了:

![image](https://user-images.githubusercontent.com/10265417/38451045-0dcaa6de-3a5b-11e8-84b6-51d003b18ac4.png)

**Comment by kamechb** [comment]
Linting for <template>
Vetur automatically uses eslint-plugin-vue for linting <template>. Linting configuration is based on eslint-plugin-vue's essential rule set.

To turn it off, set vetur.validation.template: false.

To configure linting rules:

1. Turn off Vetur's template validation with vetur.validation.template: false
2. yarn add -D eslint-plugin-vue
3. Set ESLint rules in .eslintrc. An example:
```
{
  "extends": [
    "eslint:recommended",
    "plugin:vue/recommended"
  ],
  "rules": {
    "vue/html-self-closing": "off"
  }
}
```

https://vuejs.github.io/vetur/linting-error.html#linting-for-template

**Comment by dengying3939** [comment]
> ### `wepy.mixin` 只会混合关键字，不会混合自定义方法？
> Sorry，误报，其实是后面有遗留的 `mixins = [];` 把前面的给覆盖了……
> 
> 不过发现另一个小问题，微信小程序新的 API 中，`Page` 内的 `route` 属性暂时没有封装到 `wepy.page` 内。
> 
> 最后找到 `this.$parent.__route__` 和 `this.$wxpage.route` 属性，不过从名字看来似乎是临时/内部字段的样子，不确定之后是否会有变动？

我的mixin中的自定义的方法，无法在页面中被调用，methods中的方法就可以

**Comment by axolo** [comment]
> > 在 vs code 内，vetur 会对 .user 的修饰符标注红色波浪线，提示错误：
> 
> 如果 vue 高亮插件用的是 `vetur` 的话，在对应项目的 `Workspace Settings` 中把 `vetur.validation.template` 设置为 `false` 就好了:
> 
> ![image](https://user-images.githubusercontent.com/10265417/38451045-0dcaa6de-3a5b-11e8-84b6-51d003b18ac4.png)

这样做所有的错都不会报了，包括v-for的:key
