### ISSUE TITLE
官方文档 参数传递

### ISSUE THREAD

**Issue by KingJeason** [wepyjs/wepy#355]
// wepy 1.1.8以后的版本，只允许传string。
<view bindtap="tapName({{index}}, 'wepy', 'otherparams')"> Click me! </view>

这样写 编辑器会出红色波浪线
经实验, 
<view bindtap=" 'tapName({{index}}'', 'wepy', 'otherparams')"> Click me! </view>
这样写也可以进行参数传递,并且不会有警告.

**Comment by ChenZerong** [comment]
请提供一下`代码段`  `编辑器版本`  `编辑器使用高亮插件`

**Comment by Gcaufy** [comment]
没太看明白问题的意思，先关闭了。有问题可以reopen
