### ISSUE TITLE
路径问题

### ISSUE THREAD

**Issue by Stevenzwzhai** [wepyjs/wepy#356]
自组件image引入的图片，然后手机预览看不到图片，在手机上打印错误发现是路径不对，应该是build项目的时候直接把路径放过去了，导致路径不对。比如
图片
static/images/a.png
子组件
component/home/header.wpy 引入路径为../../static/images/a.png
父组件
pages/home.wpy 引入子组件路径为../component/home/header
在手机上显示图片路径为pages/static/images/a.png，不应该有前面的pages

**Comment by ChenZerong** [comment]
#345

**Comment by Gcaufy** [comment]
相同ISSUE， 先关掉这个，处理好了在那个ISSUE下更新。
