### ISSUE TITLE
style中尺寸空格问题

### ISSUE THREAD

**Issue by grusirna** [wepyjs/wepy#357]
例如：
<style lang='scss'>
height: 100rpx; //有效
</style>
<style lang='scss'>
height: 100 rpx; //无效
</style>
开启代码自动格式化会对其格式化出空格。

这个问题查找了很久才发现，不知道是代码格式化出了问题，还是编译器出了问题

**Comment by ChenZerong** [comment]
**如图**

![image](https://user-images.githubusercontent.com/16299018/29739229-3e9fd518-8a6b-11e7-8e4f-a5e1109a9a91.png)

一直都是这样的噢，和wepy无关，就算是浏览器上的css解析也是不允许`数值`和`单位`中间有空格的

**Comment by grusirna** [comment]
@ChenZerong 原来这个样子啊，不知道怎么修改代码格式化对这部分忽略格式化

**Comment by ChenZerong** [comment]
@grusirna 提供一下`编辑器`, `编辑器高亮插件`等信息这样比较好帮你解决问题

**Comment by grusirna** [comment]
@ChenZerong 组合是webstore + vue.js + esline

**Comment by ChenZerong** [comment]
@grusirna 提供一下eslint的配置文件和一个代码案例看看，我好像没遇到你这个问题

**Comment by grusirna** [comment]
@ChenZerong 
`{
  "_args": [
    [
      "babel-eslint@7.2.1",
      "W:\\proj\\snxcx"
    ]
  ],
  "_development": true,
  "_from": "babel-eslint@7.2.1",
  "_id": "babel-eslint@7.2.1",
  "_inBundle": false,
  "_integrity": "sha1-B5Qi63O6gR48oIZc6Hrykyf4xS8=",
  "_location": "/babel-eslint",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "babel-eslint@7.2.1",
    "name": "babel-eslint",
    "escapedName": "babel-eslint",
    "rawSpec": "7.2.1",
    "saveSpec": null,
    "fetchSpec": "7.2.1"
  },
  "_requiredBy": [
    "#DEV:/"
  ],
  "_resolved": "http://r.cnpmjs.org/babel-eslint/download/babel-eslint-7.2.1.tgz",
  "_spec": "7.2.1",
  "_where": "W:\\proj\\snxcx",
  "author": {
    "name": "Sebastian McKenzie",
    "email": "sebmck@gmail.com"
  },
  "bugs": {
    "url": "https://github.com/babel/babel-eslint/issues"
  },
  "dependencies": {
    "babel-code-frame": "^6.22.0",
    "babel-traverse": "^6.23.1",
    "babel-types": "^6.23.0",
    "babylon": "^6.16.1"
  },
  "description": "Custom parser for ESLint",
  "devDependencies": {
    "babel-eslint": "^7.0.0",
    "eslint": "^3.18.0",
    "eslint-config-babel": "^6.0.0",
    "eslint-plugin-flowtype": "^2.30.3",
    "espree": "^3.4.0",
    "mocha": "^3.0.0"
  },
  "engines": {
    "node": ">=4"
  },
  "files": [
    "index.js",
    "babylon-to-espree"
  ],
  "homepage": "https://github.com/babel/babel-eslint",
  "license": "MIT",
  "main": "index.js",
  "name": "babel-eslint",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/babel/babel-eslint.git"
  },
  "scripts": {
    "changelog": "git log `git describe --tags --abbrev=0`..HEAD --pretty=format:' * %s (%an)' | grep -v 'Merge pull request'",
    "fix": "eslint index.js babylon-to-espree test --fix",
    "lint": "eslint index.js babylon-to-espree test",
    "preversion": "npm test",
    "test": "npm run lint && npm run test-only",
    "test-only": "mocha"
  },
  "version": "7.2.1"
}
`
`<style lang="less">
  .tip {
    background-color: #FFFFFF;
    padding: 30rpx;
    margin: 20rpx;
  }

  .tab_item {
    height: 100%;
  }

  page, .body {
    height: 100%;
    background-color: #f0eff5;
  }
</style>`

**Comment by ChenZerong** [comment]
`.eslintrc` 有吗

**Comment by grusirna** [comment]
`module.exports = {
  root: true,
  parser: 'babel-eslint',
  parserOptions: {
    sourceType: 'module'
  },
  env: {
    browser: true
  },
  // https://github.com/feross/standard/blob/master/RULES.md#javascript-standard-style
  extends: 'standard',
  // required to lint *.wpy files
  plugins: [
    'html'
  ],
  settings: {
    'html/html-extensions': ['.html', '.wpy']
  },
  // add your custom rules here
  'rules': {
    // allow paren-less arrow functions
    'arrow-parens': 0,
    // allow async-await
    'generator-star-spacing': 0,
    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0,
    'space-before-function-paren': 0
  }
}
`

**Comment by ChenZerong** [comment]
抱歉，暂时看不出来什么问题，看看后续有没有人也遇到这样的问题吧。:monkey:

**Comment by grusirna** [comment]
@ChenZerong 谢谢热情帮助

**Comment by zhuweiyou** [comment]
webstorm 是有这个问题，格式化后数字和 rpx 之间会出空格

**Comment by scott-leung** [comment]
@grusirna 可以用以下方法，稍作改变
<style lang="stylus">
  rpxf()
    1rpx

  rpx = rpxf()

  .container
    width 100 * rpx
</style>

这里用了stylus，可自行改成其他的，如sass、less。
这样webstorm就不会被格式化rpx前空格了。

**Comment by scott-leung** [comment]
@grusirna 可以用以下方法，稍作改变
```js
<style lang="stylus">
  rpxf()
    1rpx

  rpx = rpxf()

  .container
    width 100 * rpx
</style>
```
这里用了stylus，可自行改成其他的，如sass、less。
这样webstorm就不会被格式化rpx前空格了。

**Comment by cz848** [comment]
这样不是更麻烦了吗？可不可以wepy自动处理掉呢？

**Comment by grusirna** [comment]
@scott-leung 这不失是个好办法。

**Comment by Gcaufy** [comment]
解决方案：
1. 如果只是开发工具不支持rpx单位，那么想办法找工具去支持rpx。
2. 自动格式化存在问题那么就不用自动格式化代码。习惯手动格式化代码，个人比较推崇。
3. 使用replace插件把生成的wxss代码中的数字与rpx之间的空格给替换掉。
