### ISSUE TITLE
组件初始化问题

### ISSUE THREAD

**Issue by caibirdme** [wepyjs/wepy#358]
我有1个组件A，其作用假设是根据给定的数据绘制表格。我的某个page需要展示多个组件A，于是代码如下：
```
<view
  <repeat for={{list}} index="index" key="key" item="item">
    <coma :somedata="item"></coma>
  </repeat>
</view>

...
import ComA from '../components/somecomponent'

export default class SomePage extends wepy.page {
  components = {
    coma: ComA,
  }
  data = {
    list: [{}, {}, ...]
  }
}
```
但这样无法实现我上面说的效果：
由于repeat写法只有一个文档中所谓的component-id，所以coma的onLoad只被调用一次。（通过在coma内部onLoad中console观察得出）这样就没办法使每个组件在各自的onLoad阶段根据props进行chart绘制

**Comment by Gcaufy** [comment]
没有办法，受小程序的限制，组件是静态编译进去的，不是动态生成的，所以只存在一个coma。
