### ISSUE TITLE
app onLaunch 方法异步不管用么

### ISSUE THREAD

**Issue by KingJeason** [wepyjs/wepy#359]
async onLaunch() {
        await  this.setTime()
        await console.log('appLaunch')
    }
   setTime(){
        setTimeout(function() {
            console.log('hello');
        }, 2000);
    }
为什么 结果是 先输出 appLauch  然后加载 index首页,最后2s后输出 hello

为什么不是 等2s后输出 hello  然后输出 appLauch 最后加载index首页

**Comment by Gcaufy** [comment]
你的setTime方法并不是一个promise方法，建议再系统的看一下async/await的使用。
