### ISSUE TITLE
wepy数组变动检测规则

### ISSUE THREAD

**Issue by SoyMeng** [wepyjs/wepy#36]
使用哪些操作可以检测到数组变动？

**Comment by Gcaufy** [comment]
因为采用的是脏检查模式，所以只要数组改动就能检测到。

**Comment by SoyMeng** [comment]
使用splice删除数据组中的元素,界面并没有刷新啊？

**Comment by Gcaufy** [comment]
是不是在异步流程里面？没有$apply?

**Comment by SoyMeng** [comment]
对。。忘记了。。这么看基本上都需要调用$apply?大部分函数都是异步调用对
