### ISSUE TITLE
循环列表组件引用的数据更新问题

### ISSUE THREAD

**Issue by F-loat** [wepyjs/wepy#360]
相关代码：
``` pug
view.car-list
  repeat(for="{{cars}}", key="_id")
    carcard(:car="item")
```
问题描述：
- carcard组件被点击时，会调用组件内的turn方法，进行权限判断及页面跳转
- 列表渲染首次完成后，组件template内（即显示内容）正确，js内props值也正确，跳转是没问题的，可以跳转到对应的详情页
- 列表数据刷新后，组件template内（即显示内容）依然正确，但若此时点击的是与上一次点击index相同的列表项，则js内props的值仍为上一条数据，会跳转到之前的详情页

举例（列表页有搜索功能）：
1. 进入页面，列表渲染完成
2. 点击第二项（`{  _id: 'a', name: 'old' }`）
3. 进入详情页
4. 后退刷新数据（修改搜索条件）
5. 点击第二项（`{  _id: 'b', name: 'new' }`，显示正确）
6. 进入了 `_id` 为 `a` 的详情页（应该进入的是 `_id` 为 `b` 的详情页）
7. 后退刷新数据（修改搜索条件）
8. 点击第二项之外的一项
9. 进入了正确的详情页

线上小程序：平行进口报价内参
问题页面：进入首页后点击搜索按钮进入的那个页面

**Comment by F-loat** [comment]
原本是在js中获取的 `_id`
``` pug
view.car-info(@tap="turn")
```
修改为在template中获取，暂时解决了问题
``` pug
view.car-info(@tap="turn({{car._id}})")
```

**Comment by Gcaufy** [comment]
感谢如此详细的描述。。
但是没有具体示例代码我还是比较难重现问题。

**Comment by F-loat** [comment]
嗯。。那补个[demo](https://github.com/F-loat/wepy-demo)
简单说就是第一次点击后console输出的值是没问题的，但是下拉刷新后，不论点击哪一项，输出的都是刷新前最后一次点击的值

**Comment by F-loat** [comment]
不知道上午这个 90e07911398ee7eac9f88c72f43da07e7b6eba40 有没有修复这个问题

**Comment by Gcaufy** [comment]
![image](https://user-images.githubusercontent.com/2182004/30307857-f0882ac8-97b3-11e7-97dc-e9d1f32ff2c5.png)
![image](https://user-images.githubusercontent.com/2182004/30307873-0e122260-97b4-11e7-89a0-abe753ca4bc6.png)

**Comment by F-loat** [comment]
我本地用1.5.8这个版本是有问题的

**Comment by Gcaufy** [comment]
1.5.8我也测试过。没有问题的。

**Comment by F-loat** [comment]
又试了下，上次的描述有问题，应该是第一次点击任意一项，然后刷新后点击同一项就会出错

**Comment by F-loat** [comment]
例如你一直点第二项，不论刷新几次，输出的值都是同一个

**Comment by Gcaufy** [comment]
这里之前有做一个判断，如果选择相同的项，那么就不会重新初始化数据。。忽略了数据被改变的情况。。刚改了这里的判断。

**Comment by F-loat** [comment]
嗯，等下次发版我再测下

**Comment by Gcaufy** [comment]
这个测过了，应该是没有问题，或者你可以直接参照那个commit修改  npm/wepy/lib/component.js 中的一行代码 就行。

**Comment by F-loat** [comment]
👌测过了，没问题
