### ISSUE TITLE
微信开发者工具-->项目-->关闭ES6转ES5，这个在哪？

### ISSUE THREAD

**Issue by JakeWoki** [wepyjs/wepy#361]
微信开发者工具-->项目-->关闭ES6转ES5。重要：漏掉此项会运行报错。
微信开发者工具-->项目-->关闭上传代码时样式自动补全 重要：某些情况下漏掉此项会也会运行报错。
微信开发者工具-->项目-->关闭代码压缩上传 重要：开启后，会导致真机computed, props.sync 等等属性失效。

没找到

**Comment by Gcaufy** [comment]
这个ISSUE。。。。

**Comment by Gcaufy** [comment]
windows开始 --> 关机。

竟然如此，那就关机休息休息吧。

**Comment by JakeWoki** [comment]
无语。。。不想回答就关闭

**Comment by JakeWoki** [comment]
谢谢
