### ISSUE TITLE
wepy循环遍历操作class有顺序BUG

### ISSUE THREAD

**Issue by jiaoxuebing2014** [wepyjs/wepy#364]
![image](https://user-images.githubusercontent.com/8436801/29854595-82820eac-8d79-11e7-9148-a89795a4a754.png)
![image](https://user-images.githubusercontent.com/8436801/29854671-11fdba68-8d7a-11e7-8e2c-015a760cd6be.png)

**Comment by Gcaufy** [comment]
这个是原生BUG还是WePY的BUG？

**Comment by Gcaufy** [comment]
测试了一下，并不能复现。
