### ISSUE TITLE
wepy new 跑起来的项目,this.$parent.getUserInfo, 我打印this.$parent里面没有getUseInfo方法

### ISSUE THREAD

**Issue by fantasthu** [wepyjs/wepy#367]
wepy new 跑起来的一个项目,this.$parent.getUserInfo, 我打印this.$parent里面没有getUseInfo方法

**Comment by fantasthu** [comment]
获取头像相关的信息,估计是和网络有关系还是什么,我现在可以获取了,真的好无解

**Comment by byk04712** [comment]
+1 ，我的还没解决

**Comment by fantasthu** [comment]
先理解吧,其实我当时是没太理解小程序是怎么调用信息的
