### ISSUE TITLE
vscode 有专门的插件吗

### ISSUE THREAD

**Issue by saybabi** [wepyjs/wepy#368]
如题

**Comment by saybabi** [comment]
找到了 vetur ，点击编辑器底部右下角 -> 配置‘选择语言模式’ -> '.wpy配置文件关联 ' -> vue -> done

**Comment by skyFi** [comment]
但是没有语法提醒

**Comment by teng520** [comment]
![image](https://user-images.githubusercontent.com/26139057/41591325-fcc884bc-73eb-11e8-9b7a-06b9bf174d5e.png)
但是关联之后.wpy里面使用sass语法会报错该怎么解决
