### ISSUE TITLE
Scoped 不支持 @tap

### ISSUE THREAD

**Issue by biu0w0** [wepyjs/wepy#370]
使用 scoped 时，如果带 class 的 view 使用了 @tap 等绑定，编译时会报错：

`[Error] [xmldom error]	element parse error: Error: invalid attribute:@tap
@#[line:undefined,col:undefined]`

**Comment by Gcaufy** [comment]
![image](https://user-images.githubusercontent.com/2182004/30103154-63025126-9324-11e7-9d4e-553f230cc3da.png)
在DMEO上测试并没有发现问题。

**Comment by biu0w0** [comment]
@Gcaufy 不好意思，我之前没讲清楚。

1. 不是小程序组件，是 wepy 的 components

2. 我用的是 SASS，不知是否有关

**Comment by Gcaufy** [comment]
与sass无关，这个就是wepy的components
