### ISSUE TITLE
await in async onLoad  无效？

### ISSUE THREAD

**Issue by focuspace** [wepyjs/wepy#372]
把新建项目的 `onLoad` 改成这样：

```
async onLoad() {
    const data = await wepy.login()
    console.log(data)
}
```

输出的是 `undefined`

用的是最新的小程序的开发工具

**Comment by Gcaufy** [comment]
有效的。是不是少写了个use
https://github.com/wepyjs/wepy/wiki/wepy%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8async-await

**Comment by focuspace** [comment]
是的，没有写 use， 👍
