### ISSUE TITLE
给子组件属性传值，只能定义到父附件的变量或属性上面，不能直接传常量

### ISSUE THREAD

**Issue by lucas-luzj** [wepyjs/wepy#373]
例如默认的Counter组件，属性num, 在父页面上， 
<counter2  :num="10"></counter2>
num不能传入，
component.js 文件  line:178
val = $parent[binded]  修改为  val = $parent[binded] || binded
可解决该问题

**Comment by Gcaufy** [comment]
传常量用静态传值

<counter :num="mynum" staticnum="50" />
