### ISSUE TITLE
建议：把引用组件时候附加的attribute，传入、合并、替换到组件rootElement上面

### ISSUE THREAD

**Issue by lucas-luzj** [wepyjs/wepy#374]
例如：我定义了一个rater组件，没有定义style,或者定义了自己的style, 或者class
在页面上引用rater组件的时候，我指定了自己的style或者class, 如果何以用引用时传入的style替换（或合并）子组件rootElement上的对应属性就更好了
例如：<rater style="background: #009cff;" :num="10" :char="★" />
如果这样， 可以方便的更新背景、字体、自定义class，设置属性。就会方便很多

**Comment by Gcaufy** [comment]
与 props 的功能冲突了。
