### ISSUE TITLE
新开一份项目，然后在微信开发者工具中运行，提示“渲染层网络层错误”

### ISSUE THREAD

**Issue by lamjack** [wepyjs/wepy#376]
<img width="1551" alt="2017-09-07 11 00 25" src="https://user-images.githubusercontent.com/8164447/30169802-fd882bca-941f-11e7-9189-171809ba2485.png">

<img width="377" alt="2017-09-07 11 00 49" src="https://user-images.githubusercontent.com/8164447/30169824-0af91dbe-9420-11e7-9e18-724cd6e240f8.png">

nodejs版本和npm版本,

<img width="229" alt="2017-09-07 11 01 44" src="https://user-images.githubusercontent.com/8164447/30169884-2a9a0606-9420-11e7-963e-91de67749e86.png">

**Comment by Gcaufy** [comment]
什么叫“渲染层网络层错误”
我看到的就是一个fail to load image的错误啊。。看看代码哪里有<image>之类的，删掉看看还会报错么？

**Comment by lamjack** [comment]
问题就是..完全新建的项目..我还没开始写代码..然后我看init出来的代码都没有加载图片的地方..

**Comment by Gcaufy** [comment]
DEMO中唯一加载的图片就是自己的头像。没有其它图片加载。而且我的没有报这个错。

**Comment by lamjack** [comment]
头像加载出来了，我再看看，谢谢啦。

**Comment by guxuehua** [comment]
![image](https://user-images.githubusercontent.com/18044466/33116590-4edc9c66-cfa0-11e7-80a5-0ac99fd1c5de.png)
