### ISSUE TITLE
询问关于eslint的一条规则引起的问题

### ISSUE THREAD

**Issue by cz848** [wepyjs/wepy#378]
用了airbnb的JS规范（团队规定），其中有一条`class-methods-use-this`，意思是方法里应该要用this。可是有些方法真的用不上this。要不然就得加`static`关键字。但是加了之后构建出来又会报错找不到此方法。所以除了禁用这条规则，或强行给这条方法里加个`console.log(this)`这种不得已的办法外，还有没有更优雅的处理方式？

**Comment by Gcaufy** [comment]
严格来说这个规则是何理的，class method 就是这个class提供的方法，如果这个method 与class没为任何关联，那么这个method还有在这个class的必要么？还是指他仅仅只是一个common function呢。可以好好审视一下自己对class的设计。。

如果非这么做不可，可以这么写：
```
/*eslint class-methods-use-this: ["error", { "exceptMethods": ["foo"] }] */
```

**Comment by cz848** [comment]
嗯，一开始还不是很理解，不过现在我突然想明白了，确实这个method没有与这个class有关联，可以写成模块单独去引入。感谢，你的话使我茅塞顿开。

**Comment by dongchunhai** [comment]
但是有些方法是从html模版里直接引用的，这样的方法也写成工具方法就不合适里。
