### ISSUE TITLE
使用mockjs模拟数据出现问题

### ISSUE THREAD

**Issue by fanzihui** [wepyjs/wepy#379]
我 ，`yarn add mockjs --save `后，运行`wepy build --watch`命令，然而这个`npm`包并没有复制到`dist/npm/`里，并且会出现`module "npm/mockjs/dist/mock.js" is not defined `.......

另外我把`mockjs`里面的`dist`文件夹复制到 `dist/npm/`里面，然后在调用出现
```
Uncaught TypeError: Cannot read property 'split' of undefined
```

**Comment by Gcaufy** [comment]
删掉`./node_module/mockjs/dist/mock.js:1476`
```
var Canvas = module.require('canvas')
```
删掉后再执行`wepy build --no-cache` 试试

**Comment by fanzihui** [comment]
去掉你说的那个 没有 canvas 的错误了，但是
`Uncaught TypeError: Cannot read property 'split' of undefined` 
这个错误依旧在

**Comment by fanzihui** [comment]
已解决这个问题了，谢谢.

**Comment by Gcaufy** [comment]
怎么解决的？

**Comment by fanzihui** [comment]
定义数据的时候:
`
const M = require('mockjs')
let res = M.mock({
   'article|1-10': [{
       'id|+1': '@id', //问题出现在这里 @id 改为 1
       'title': '@title(30)'
   }]
})
`
然后就没有报错了,
