### ISSUE TITLE
wepy.request有无中止请求的方法？

### ISSUE THREAD

**Issue by dearhulu** [wepyjs/wepy#391]
wx.request可以返回requestTask
然后通过abort终止请求
wepy.request有无中止请求的方法

**Comment by Gcaufy** [comment]
原生有则有，原生无则无。

**Comment by Gcaufy** [comment]
> 返回一个 requestTask 对象，通过 requestTask，可中断请求任务。

新的改动啊。那对于需要中止的请求继续使用`wx.request`就好了

**Comment by mangoooooo** [comment]
@Gcaufy  请问  有加入此功能到 wepy.request 的计划吗？
