### ISSUE TITLE
您好我刚刚看到了介绍里有请求队列文档里有提到吗

### ISSUE THREAD

**Issue by JourneyL** [wepyjs/wepy#392]
我现在是有个这样的问题，我首页里请求的参数需要token，token 是在app.wpy里得到的，wepy.app里也没有事件订阅之类的api都是在component里有的，所以我想问一下这个请求队列相关的内容该怎么做

**Comment by Gcaufy** [comment]
```

    constructor () {
        super();
        this.intercept('request', {
            config (p) {
                p.token = mytoken;
                return p;
            }
        });
    }
```

**Comment by JourneyL** [comment]
@Gcaufy  可是这并不能保证第二个请求的时候是在第一个结束的以后进行的啊 ，
我现在是app.wpy请求登录获取token,   page1.wpy是首页在onload里面请求了一个列表 虽然有先后顺序 但几乎可以说是同时请求 然后列表先返回接口之后登录接口才请求成功

**Comment by Gcaufy** [comment]
这个是封装request方法实现的，通常由业务自己去做。类似以下流程图。

![image](https://user-images.githubusercontent.com/2182004/30540712-e1be35a4-9caa-11e7-8d18-508def4d0db5.png)

**Comment by JourneyL** [comment]
谢谢大大 我再自己研究研究
