### ISSUE TITLE
两次await操作,只执行await 的第一个方法

### ISSUE THREAD

**Issue by fantasthu** [wepyjs/wepy#393]
## 代码
```
app.wpy中
async onLaunch() {
    await this.ceshi()        
    await this.testA();
 }

testA() {
    return new Promise((res, rej) => {
      setTimeout(function() {
        console.log('test1', '1111')
      }, 5000)
    })
  }

  ceshi(){
    return new Promise((res, rej) => {
      setTimeout(function() {
        console.log('ceshi', '1111')
      }, 4000)
    })
  }
```

## 测试结果:
```
ceshi 111
```

**Comment by Gcaufy** [comment]
第一个promise没有resovle掉。

**Comment by lyh2668** [comment]
对于没有resove这个问题能否给予一个简单的说明，不是
```
    try {
      await wepy.getUserInfo().then(res => {
        console.log('userinfo: ', res.userInfo)
        this.userinfo = res.userInfo
      })
      await wepy.login().then(res => {
        console.log('login: ', res)
      })
    } catch (err) {}
```
我这样写同样只会打印出第一个userinfo的内容

**Comment by Gcaufy** [comment]
你的第一种写法看起来完全没有问题的。

你的问题与1楼说的不是一个问题。他是new的Promise对象，但是没resolve。那就不是一个合理的Promise对象了。

**Comment by Gcaufy** [comment]
![image](https://user-images.githubusercontent.com/2182004/32203602-4aa6e65c-be1f-11e7-8927-238cc9417585.png)

拷贝你的代码，直接可运行。

**Comment by lyh2668** [comment]
@Gcaufy 我再次尝试了一次，这次可行，我猜测可能是watch的原因，导致有时会没有更新。谢谢作者大大的解答。还有个问题就是async/await异步加载的数据是需要this.$apply()吗？数据总是无法渲染上去，是在组件内部操作的。

**Comment by lyh2668** [comment]
sorry我又犯了大小写错误的问题...微信小程序的data能够对未定义的变量直接进行赋值操作，总是会引起一些小错误...在vue里面的data则能检测出data里的变量是否申明，大概这就是为什么vue是采用
```
data () {
  return {}
}
```
如此的方式吧...我有必要去看一下源码...打扰了...

**Comment by Gcaufy** [comment]
@lyh2668 异步处理的数据需要 this.$apply()

**Comment by ccccccmd** [comment]
@Gcaufy 

> 你的第一种写法看起来完全没有问题的。
> 
> 你的问题与1楼说的不是一个问题。他是new的Promise对象，但是没resolve。那就不是一个合理的Promise对象了。

没理解这句话，他的两个promise看起来都是一样的啊
