### ISSUE TITLE
less外部 文件如何引用?

### ISSUE THREAD

**Issue by huike1989** [wepyjs/wepy#4]
1.如果是纯less文件，直接在style里使用@import(类似 @import '../style/test.less')报错
是我使用的方式不对吗？

2. less文件中如果定义变量 #444这样井号开头的，编译的时候也会报错。

**Comment by Gcaufy** [comment]
![1](https://cloud.githubusercontent.com/assets/2182004/21010170/9c1d255a-bd85-11e6-97ce-a0cf0d0e03a7.png)
![2](https://cloud.githubusercontent.com/assets/2182004/21010168/9c18516a-bd85-11e6-964e-289a2c8ddccc.png)
![3](https://cloud.githubusercontent.com/assets/2182004/21010169/9c18d1e4-bd85-11e6-918a-c3ed38a0e23e.png)

1. @import 时需要import相对于根目录的全路径。
2. 定义#444并没有报错。
