### ISSUE TITLE
wepy-cli 在根据组件内的 config 属性生成 .json 文件后，并没有运行 plugins 插件

### ISSUE THREAD

**Issue by ystarlongzi** [wepyjs/wepy#403]
此问题源自于 [#196](https://github.com/wepyjs/wepy/issues/196#issuecomment-331045144)，想根据在构建时的环境参数，动态修改 `config`  的部分属性值。

然后看了下和文件编译相关的代码，发现 
- [compile-style.js#L134](https://github.com/wepyjs/wepy/blob/master/packages/wepy-cli/src/compile-style.js#L134)
- [compile-script.js#L224](https://github.com/wepyjs/wepy/blob/master/packages/wepy-cli/src/compile-script.js#L224)
- [compile-style.js#L134](https://github.com/wepyjs/wepy/blob/master/packages/wepy-cli/src/compile-style.js#L134)
- [compile-template.js#L515](https://github.com/wepyjs/wepy/blob/master/packages/wepy-cli/src/compile-template.js#L515) 

都有执行 plugins 相关的代码，如下：
```javascript
let plg = new loader.PluginHelper(config.plugins, {
  // ....
});
```
然后，发现在 [compile-config.js](https://github.com/wepyjs/wepy/blob/master/packages/wepy-cli/src/compile-config.js) 并没有执行 plugin 相关的代码，然后就导致了 [#196](https://github.com/wepyjs/wepy/issues/196#issuecomment-331045144) 这个问题

**Comment by Gcaufy** [comment]
这个需要使用replace插件没有办法实现么？

**Comment by ystarlongzi** [comment]
@Gcaufy 
没办法实现吧。我在这个[issue 402#issuecomment-331332930](https://github.com/wepyjs/wepy/issues/402#issuecomment-331332930) 里解释我有这样需求的原因

**Comment by ystarlongzi** [comment]
@Gcaufy `wepy-cli` 升级到  v1.5.9-2 后， `/wepy-cli/lib/compile-config.js` 还是旧的代码

**Comment by ystarlongzi** [comment]
@Gcaufy 是这样的嘛？

**Comment by Gcaufy** [comment]
刚发了个`1.5.9-3`，你再试试

**Comment by ystarlongzi** [comment]
@Gcaufy 可以啦，威武~~
