### ISSUE TITLE
安装卡了好久，还是失败了

### ISSUE THREAD

**Issue by coolicer** [wepyjs/wepy#405]
![image](https://user-images.githubusercontent.com/811078/30783001-f45433a8-a16e-11e7-8f89-9b948895aae4.png)

**Comment by Gcaufy** [comment]
try cnpm

**Comment by coolicer** [comment]
我就是用cnpm

**Comment by Gcaufy** [comment]
那你就把那行命令copy下来，单独执行一次就好了

**Comment by coolicer** [comment]
@Gcaufy 我才发现wepy new用的是npm。。
