### ISSUE TITLE
关于父子组件onLoad函数的调用顺序的疑问？

### ISSUE THREAD

**Issue by hudongyang** [wepyjs/wepy#406]
我的实验是先调用子组件，再调用父组件的onLoad函数，假设：
父组件有个data变量叫type，在onLoad里初始化，并且作为prop传给子组件，那么，我在子组件的onLoad里就拿不到父组件初始化之后的值了。因为父组件的onLoad执行太迟了。
如果我想对父组件传过来对数据进行操作的话都不可以了。

**Comment by edison1105** [comment]
问同

**Comment by ystarlongzi** [comment]
先触发子组件的 onLoad，然后在触发父组件的 onLoad，这个是合理的。
@hudongyang @edison1105 看下这里的文档 [Props 传值](https://wepyjs.github.io/wepy/#/?id=Props-%e4%bc%a0%e5%80%bc)
