### ISSUE TITLE
如何动态的向components中添加组件

### ISSUE THREAD

**Issue by 1035901787** [wepyjs/wepy#409]
我需要多次引用同一个组件，每个组件需要有独立的状态。现在情况是wepy需要在components中事先声明好需要的组件，但是我的数据是动态的，请教一下作者。@Gcaufy

**Comment by tanjibo** [comment]
同问

**Comment by irispastal** [comment]
同问

**Comment by Gcaufy** [comment]
一定要事先声明组件，没有办法动态添加组件的。

**Comment by github-libra** [comment]
有类似于 Vue.js 中的 `<component :is="name"></component>` 这样的动态组件么？@Gcaufy

**Comment by alinjiajun** [comment]
我也遇到这个需求了 为什么不独立状态呢
