### ISSUE TITLE
组件中有子组件是列表时，初始值为空会报错的解决【bug】

### ISSUE THREAD

**Issue by useryu** [wepyjs/wepy#410]
修改component.js中的  binddata = binddata[t]; 为 if (binddata[t]){
                                          binddata = binddata[t];
                                        }else{
                                          binddata = [{}];
                                        }

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy/commit/fd3fdf2a2308591626aaa617efcab958dbee2c72
