### ISSUE TITLE
找不到编译器：wepy-compiler-less

### ISSUE THREAD

**Issue by mosade** [wepyjs/wepy#413]
运行wepy build --watch 
出现:[WARNING] 找不到编译器：wepy-compiler-less。
        [11:22:54] [信息] 检测到有效NPM包资源，正在尝试安装，请稍等。
就这样无限循环这是什么情况,突然就这样了,以前没有这个问题

**Comment by Gcaufy** [comment]
CTRL+C后手动安装`wepy-compiler-less`

**Comment by mosade** [comment]
重新安装还是提示这个

**Comment by Gcaufy** [comment]
看一下node_modules里面是否存在这个文件夹呢？

**Comment by mosade** [comment]
有wepy-compiler-less 文件夹存在

**Comment by Gcaufy** [comment]
这个问题还没有解决吗？

**Comment by mosade** [comment]
没有,所有新建的项目也都是报这个错.我不知道是什么情况

**Comment by Gcaufy** [comment]
可以了？

**Comment by implement** [comment]
windows下同样的问题： wepy build --watch
[WARNING] 找不到编译器：wepy-compiler-sass。
[14:57:17] [信息] 检测到有效NPM包资源，正在尝试安装，请稍等。
wm-mp-notice@0.1.0 D:\DevWorkspace\weimob\comb-mp-notice
`-- wepy-compiler-sass@1.3.7

[14:57:31] [完成] 已完成安装 wepy-compiler-sass，重新启动编译。
[14:57:31] [编译] 入口: src\app.wpy
[14:57:31] [写入] JSON: dist\app.json
[14:57:32] [编译] 组件: src\components\avatar.wpy
Error: %1 is not a valid Win32 application.
\\?\D:\DevWorkspace\weimob\comb-mp-notice\node_modules\node-sass\vendor\win32-x64-48\binding.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (D:\DevWorkspace\weimob\comb-mp-notice\node_modules\node-sass\lib\binding.js:19:10)
    at Object.<anonymous> (D:\DevWorkspace\weimob\comb-mp-notice\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
[WARNING] 找不到编译器：wepy-compiler-sass。
[Error] 未发现相关 sass 编译器配置，请检查wepy.config.js文件。

Node version:  v6.10.1
node_modules下有wepy-compiler-sass

**Comment by Gcaufy** [comment]
@implement sass的问题吧。
建议单独安装`npm install node-sass` 试试看是否成功。
sass在windows上问题太多，建议使用less

**Comment by implement** [comment]
@Gcaufy 不好意思，是sass的锅，手动装node-sass报下面错，貌似是没有兼容Microsoft.NET Framework4.0
===============================================
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
生成启动时间为 2017/10/18 15:08:30。
MSBUILD : error MSB4132: 无法识别工具版本“2.0”。可用的工具版本为 "4.0"。
============================

**Comment by implement** [comment]
@Gcaufy 不好意思，是sass的锅，手动装node-sass报下面错，貌似是没有兼容Microsoft.NET Framework4.0

gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args '/nologo',
gyp info spawn args '/p:Configuration=Release;Platform=x64' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
生成启动时间为 2017/10/18 15:08:30。
MSBUILD : error MSB4132: 无法识别工具版本“2.0”。可用的工具版本为 "4.0"。

**Comment by guxuehua** [comment]
![image](https://user-images.githubusercontent.com/18044466/33073297-6e6a67be-cefd-11e7-97e2-2fb50f1fd9d3.png)

**Comment by Gcaufy** [comment]
@guxuehua 没有eslint的配置文件。。不知道你是因为失误删过文件还是什么 情况 。
你可以再new一个项目 ，然后把eslint的相关文件copy过来，也可以关闭eslint功能。

**Comment by supwjm** [comment]
![3b50922a-dced-42e3-8092-aec899d4f80c](https://user-images.githubusercontent.com/9331095/38191472-6dd57086-369b-11e8-9a88-ba699753d4db.png)

用cnpm安装，我看提示已经安装成功，但编译的时候还是提示：找不到编译器：wepy-compiler-sass

**Comment by linkdesu** [comment]
等等！这个问题都还没有解决，就 close 了？Mac 也有这问题啊，另外像是 wepy-eslint、wepy-plugin-uglifyjs 等也出现命名安装了却说未找到的问题。

**Comment by yxhuangCH** [comment]
mac 新建项目， 有这两个问题
[WARNING] 找不到编译器：wepy-compiler-less。
[Error] 未发现相关 less 编译器配置，请检查wepy.config.js文件。

**Comment by amyfeng** [comment]
笔记本windows7安装了无数软件,oracle,vmware等等开发所需要的软件。也是报这个错误。
后来找一个比较干净的虚拟机win2008，就没有报这个错误了。不知道跟什么有冲突还是不兼容。

**Comment by ccbbhh** [comment]
1.在windows下使用管理员打开命令窗口后执行以下两个命令
npm install node-sass
npm install wepy-compiler-sass --save-dev
可以参考:https://blog.csdn.net/weixin_42754418/article/details/81144069

**Comment by JIJL** [comment]
npm install less less-loader --save-dev 解决

**Comment by lvao813** [comment]
> npm install less less-loader --save-dev 解决

感谢，mac上用这个方法成功了

**Comment by lvao813** [comment]
> npm install less 后再 npm install wepy-compiler-less 解决

感谢，mac上用这个方法完美解决

**Comment by evannalikeyou** [comment]
遇到了一样的问题，重新安装less和wepy-compiler-less之后可能因为版本过高提示cannot find module 'mime'，然后改低了less和mime版本重新安装就好了。

**Comment by ximendatie** [comment]
> npm install less 后再 npm install wepy-compiler-less 解决

亲测可用，good

**Comment by Windancer** [comment]
直接npm install 就好了，或者 npm install wepy-compiler-less

**Comment by kapop** [comment]
> npm install less less-loader --save-dev 解决

我的mac上也是用这个完美解决，谢谢

**Comment by gezhiwei8899** [comment]
我一个后端写前端代码就像是瞎子摸鱼一样的
