### ISSUE TITLE
watch模式下，在app.wepy的<style></style>中和@import外部的scss文件中定义的@mixin，在页面中使用时报错。

### ISSUE THREAD

**Issue by leonwebdever** [wepyjs/wepy#416]
![1506654096690](https://user-images.githubusercontent.com/9197721/30999116-b004ccc6-a498-11e7-9859-63d2beef33f6.jpg)

* 独立建一个base.scss在页面中引入，如果只是定义变量没有报错，但是如果用了@function和@mixin语法就会报错。（ps: 我是用scss语法的，不是sass）

* 版本号："wepy": "^1.5.8"，"wepy-compiler-sass": "^1.3.7",

**Comment by Gcaufy** [comment]
试试
```
npm install wepy-cli@1.5.9-1 -g
```

**Comment by leonwebdever** [comment]
ok  升级了wepy-cli之后问题解决了
