### ISSUE TITLE
之前反映过的一个issue（#312）：“.wpy文件中注释掉一个view不生效”，可以按如下方法复现

### ISSUE THREAD

**Issue by aben1188** [wepyjs/wepy#418]
issue #312 

以该文件为例：https://github.com/wepyjs/wepy-weui-demo/blob/master/src/example/searchbar.wpy
在开启了watch的情况下(wepy build --watch)，在ide（我用的是phpstorm）中可以注释掉如下两行（第23行、第24行）：
![qq 20171001114051](https://user-images.githubusercontent.com/9190887/31051619-f9f80336-a69e-11e7-9072-f14050603bee.png)

然后按ctrl-s保存，开发者工具（已设置为文件保存时则自动编译）中可以看到小程序已经被重新编译（说明wepy的自动监听文件改动在起作用）。但编译完成之后界面上实际没有任何变化，而重新手动再执行一次wepy build --watch，界面才发生变化。

**Comment by Gcaufy** [comment]
按照你的步骤也无法重现问题。
看一看是否是IDE导致的问题。
