### ISSUE TITLE
新人求助，报错，块不能用空格填充块

### ISSUE THREAD

**Issue by sipei97** [wepyjs/wepy#420]
### 虽然报错但没有中止
  157:48  error  Block must not be padded by blank lines  padded-blocks

✖ 1 problem (1 error, 0 warnings)

[22:23:00] [写入] WXML: dist\pages\index.wxml
[22:23:00] [写入] JS  : dist\pages\index.js
[22:23:00] [写入] WXSS: dist\pages\index.wxss

### 目标代码是

  153 import wepy from 'wepy'
  154 import qcloud from './../mixins/wafer2-client-sdk/index'
  155 import config from './../mixins/config'
  156 
  157 export default class Index extends wepy.page {
  158 
  159 data = {......}

**Comment by ystarlongzi** [comment]
你这是 eslint 错误，代码风格不符合 eslint 的配置。

如果对代码风格无要求，可以在 wepy.config.js 里把 `eslint: true` 给注释掉

**Comment by sipei97** [comment]
@ystarlongzi 不好意思，过节回家没看，谢谢
