### ISSUE TITLE
ios 预览 正常 安卓 有问题

### ISSUE THREAD

**Issue by YouthBaby** [wepyjs/wepy#421]
ios 是正常的 ，在安卓上 会提示 当前页 page not found ,May be caused by : 1. Forgot to add page route in app.json 2. invoking page() in asynv=c task .我把es6 转 es5 、自动压缩 、样式自动补全 全部关了。ios 是可以正常显示的

**Comment by YouthBaby** [comment]
问题已解决，是因为我把腾讯云给的wafer组件放到了dist目录下，直接在app.wpy 中引用dist目录中的文件，但是还是很奇怪，ios是正常的，安卓就不正常了，把wafer放到src，安卓就好了

**Comment by Autumnwater** [comment]
我刚好遇到这个问题

**Comment by Autumnwater** [comment]
但是按照你的方法没有解决

**Comment by jas0ncn** [comment]
@YouthBaby 使用了 wafer 哪个组件呢？麻烦提供一下，我这里帮你看看啥问题。

**Comment by YouthBaby** [comment]
@jas0ncn 是用的 wafer2-client-sdk 小程序 增强sdk url: https://github.com/tencentyun/wafer2-startup
我把 vendor/wafer2-client-sdk 全部放到 dist 目录下 ,在app.wpy 文件中访问,安卓就报错了

**Comment by Autumnwater** [comment]
解决了，不够是官方小程序的问题。。。。太扯淡了
