### ISSUE TITLE
数组深拷贝如何处理？

### ISSUE THREAD

**Issue by xmsz** [wepyjs/wepy#422]
`
const list = [
        {
          name : 1
        },
        {
          name : 2
        }
      ];

      const test1 = list.slice(0);
      const test2 = list.slice(0);

      test1[0]['name'] = ‘123’ ;

`

按道理说
我改变的只是 test1 。
但是实际上
test2 甚至 list 都变化了

---
这是为什么

**Comment by YouthBaby** [comment]
可能是因为 你改变的是数组里的对象，对象是按共享传递（看成引用）的，所以相当于改变的是list[0]这个对象，访问的时候也是访问的这个
