### ISSUE TITLE
华为荣耀6 wepy.showLoading()和wepy.hideLoading()方法报错

### ISSUE THREAD

**Issue by sonicG** [wepyjs/wepy#427]
您好， wepy.showLoading()和wepy.hideLoading()方法 在 华为荣耀6 安卓版本4.4.2 报错 is not a function，
请问这是什么问题？

**Comment by Gcaufy** [comment]
那你试试`wx.showLoading()`看看有没有问题

**Comment by sonicG** [comment]
刚刚试了一下，不行，应该是官方的api问题，多谢解答

**Comment by CaptainLiao** [comment]
借楼一下，如何在wepy内配置typescript，看了wepy文档，直接跳转到这里了https://www.tslang.cn/docs/handbook/declaration-files/introduction.html

**Comment by sonicG** [comment]
@CaptainLiao 这个我也不太清楚。。
