### ISSUE TITLE
style标签的lang属性不支持scss

### ISSUE THREAD

**Issue by hpyer** [wepyjs/wepy#43]
虽然lang属性支持sass，但是实际上却是支持的scss的语法，这两种还是[有区别的](http://sass.bootcss.com/docs/scss-for-sass-users/)。
如果把lang写成scss，会导致找不到编译器的错误
如果写成sass则会导致代码高亮插件提示错误语法有误
建议优化一下，谢谢！

**Comment by Gcaufy** [comment]
已修复，等待下一个版本。

**Comment by hpyer** [comment]
感谢～
