### ISSUE TITLE
关于sass的autoprefixer

### ISSUE THREAD

**Issue by xing00** [wepyjs/wepy#434]
上次群里有人说起关闭代码自动补全，才想起来一直用sass没有使用autoprefixer进行自动补全，麻烦群主弄一下啦，辛苦了。

**Comment by Gcaufy** [comment]
在提交npm时才发现这个已经有人做好了。
https://github.com/li-xianfeng/wepy-plugin-autoprefixer

**Comment by xing00** [comment]
哈，我昨晚在github上搜，我以为你已经知道这个了，既然这个能用那就用这个吧，嘿嘿

**Comment by liuxingzhijian1320** [comment]
> 在提交npm时才发现这个已经有人做好了。
> https://github.com/li-xianfeng/wepy-plugin-autoprefixer

使用了 https://github.com/li-xianfeng/wepy-plugin-autoprefixer 但是在dist的对应文件查看，没有发现添加前缀上去？？？
