### ISSUE TITLE
wepy.mixins 类里无法声明 components 属性嘛？

### ISSUE THREAD

**Issue by ystarlongzi** [wepyjs/wepy#438]
如题，正在写一个 mixins，默认会挂一些 components，然后在编译时并没有报错，但实际上产出的文件并没有被编译

**Comment by Gcaufy** [comment]
mixins中不支持components

**Comment by ystarlongzi** [comment]
@Gcaufy 嗯嗯，谢谢

还有一个疑问，mixins 声明的方法以 `on` 开头的会被过滤掉？

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy/blob/master/packages/wepy/src/mixin.js

看这里最直接

**Comment by ystarlongzi** [comment]
嗯嗯，谢谢
