### ISSUE TITLE
mixin 中定义的方法，不能在 page 的 this 中访问。

### ISSUE THREAD

**Issue by shenqihui** [wepyjs/wepy#44]
```javascript
export default class extends wepy.mixin {
  func1 = function () {}

  func2 () {}
}
```

如上的 `mixin` ，在 `pages` 的 `this` 中，只能调用 `this.func1`, 不能调用 `this.func2` ，`func2` 没有挂载到 `this` 上。具体原因，初步推断为 `class` 的 `prototype` 属性不能枚举造成的。而实例属性能枚举，因此能挂载，所以 `this` 上能调用。

**Comment by Gcaufy** [comment]
已修复。https://github.com/wepyjs/wepy/commit/532bcd323fe75beeafce2536262e2750cd5cedc6#diff-2e8f61a24923c497c1695aa78eba09e2R59

**Comment by meng-Macbook** [comment]
现在可以在page访问，不过会报一个Missing files 的錯誤
