### ISSUE TITLE
style 接收动态的样式，部分样式无法解析！

### ISSUE THREAD

**Issue by guoooofu** [wepyjs/wepy#440]
话不多说，直接上代码：
style：
`
.test {
    width: 200rpx;
    height: 200rpx;
    margin-bottom: 20rpx;
    background: red;
    transition: all 0.6s;
  }
`
template:
`
<view class="test " style="font-size: {{size}}rpx; transform: translateY({{testY}}rpx);" @tap="test">test</view>
`
methods:
`
test () {
        this.size = 60
        this.testY = 60
      }
`
效果：
![image](https://user-images.githubusercontent.com/22878237/31753270-23d2671e-b455-11e7-8477-4936b353ed74.png)
![image](https://user-images.githubusercontent.com/22878237/31753278-301b20c4-b455-11e7-9597-356dbe8db87c.png)
只有font-size有效果，而将translateY的尺寸单位换成px就好使了，但是在各手机上偏移量不一样。
 translateY({{testY}}rpx -->  translateY({{testY}}px后的效果：
![image](https://user-images.githubusercontent.com/22878237/31753350-afe61a52-b455-11e7-80fc-1273138f1a51.png)
![image](https://user-images.githubusercontent.com/22878237/31753353-b36e5d06-b455-11e7-9649-801eb2fae97c.png)
ps: 是因为小程序动画的translate方法只接受px尺寸单位么？有没有办法使用rpx？

**Comment by Gcaufy** [comment]
这个问题不是WePY的问题，建议在[官方开发者社区](https://developers.weixin.qq.com/)提问。
