### ISSUE TITLE
redux 展开符报错

### ISSUE THREAD

**Issue by jielanglang** [wepyjs/wepy#442]
最新的wepy-cli1.5.9-5 中在redux状态中不可以使用展开符...state  一直在浏览器中包错

**Comment by Gcaufy** [comment]
看看是不是babel配置错了呢？

**Comment by jielanglang** [comment]
默认是这样的
babel: {
      sourceMap: true,
      presets: [
        'env'
      ],
      plugins: [
        'babel-plugin-transform-class-properties',
        'transform-decorators-legacy',
        'transform-export-extensions',
        'syntax-export-extensions'
      ]
    }

**Comment by Gcaufy** [comment]
加上这句试试
```
        'transform-object-rest-spread',
```

**Comment by jielanglang** [comment]
Unknown plugin "transform-object-rest-spread" specified in "base" at 4

**Comment by Gcaufy** [comment]
```
npm install babel-plugin-transform-object-rest-spread --save-dev
```

**Comment by jielanglang** [comment]
Very nice！ I love your project
