### ISSUE TITLE
求助，出错了： 11 not found

### ISSUE THREAD

**Issue by cmzz** [wepyjs/wepy#444]
wepy build --watch 编译正常。

开发者工具： 1.01.171018

版本及依赖： 

  "dependencies": {
    "wepy": "^1.5.7",
    "wepy-async-function": "^1.4.4",
    "wepy-cli": "1.5.7",
    "wepy-com-toast": "^1.0.2",
    "weui-wxss": "^1.1.1"
  },
![2017-10-20 at 1 36 am](https://user-images.githubusercontent.com/6111715/31785312-59299ee0-b537-11e7-8e4f-a3b9f521d029.png)

**Comment by Gcaufy** [comment]
报错已经说明， wxss文件错误，检查一下你的wxss文件吧。

**Comment by cmzz** [comment]
@Gcaufy  应该不是，这个项目已经发布了。什么都没动，昨晚启动就这样，而且比较怪异的是我用wepy new 一个新的项目，也无法运行。最新版 微信开发工具。错误如下： 

过程如下：
![image](https://user-images.githubusercontent.com/6111715/31802698-28386bea-b582-11e7-9e3d-ebe62d1d0e9c.png)
![image](https://user-images.githubusercontent.com/6111715/31802778-a94ff11c-b582-11e7-9f80-69fa4fb925c2.png)
![image](https://user-images.githubusercontent.com/6111715/31802838-fa3ece4a-b582-11e7-80e6-be651b67740a.png)

![image](https://user-images.githubusercontent.com/6111715/31802819-e85f72ce-b582-11e7-8390-0a0341e8c346.png)

**Comment by Gcaufy** [comment]
是不是该关的没关

**Comment by cmzz** [comment]
![image](https://user-images.githubusercontent.com/6111715/31802897-4ce453d6-b583-11e7-9938-e91d30f51f1b.png)
关了的。

**Comment by Gcaufy** [comment]
```
rm dist/* && wepy build --no-cache
```

**Comment by cmzz** [comment]
![image](https://user-images.githubusercontent.com/6111715/31802979-b1aa2cdc-b583-11e7-97d1-7106a89a99f4.png)

![image](https://user-images.githubusercontent.com/6111715/31802988-c50347a0-b583-11e7-9e91-dcea4250c503.png)

没变化

**Comment by cmzz** [comment]
➜  demo npm -v
5.3.0

➜  demo node -v
v8.1.2

**Comment by cmzz** [comment]
![image](https://user-images.githubusercontent.com/6111715/31814537-90e1837c-b5bc-11e7-9a23-7134ecdb2c9c.png)


下载https://github.com/Thunf/wepy-demo-bookmall 这个项目，也无法运行。怀疑是我系统的问题，但没思路。

我重装了 node npm yarn ，都不行。。

求助，给点思路，比较着急，不至于要重装系统吧

**Comment by Gcaufy** [comment]
好的。我测试一下这个项目

**Comment by Gcaufy** [comment]
按该repo的README上的指引就把项目给跑起来了
![image](https://user-images.githubusercontent.com/2182004/31815070-2f894b4e-b5be-11e7-906f-2bcb815c2749.png)

**Comment by cmzz** [comment]
无解。。  逼迫我最后重装系统，解决了

**Comment by Gcaufy** [comment]
重装电脑系统？

**Comment by lzf0402** [comment]
win10 相同问题 mac党表示没问题
不能重装系统啊

**Comment by mygoodidea** [comment]
我也遇到过新工程.wxss编译问题,我的解决办法是:

1.开发者工具控制台输入 : openVendor()
2.输入后在打开的目录中删除那两个.exe文件
3.重启开发者工具

我是通过以上步骤解决的,希望对各位有用

**Comment by sumaolin** [comment]
@mygoodidea 按你的办法解决了，请教下是啥原因啊？也是window的问题
