### ISSUE TITLE
cli对绝对路径引用出错

### ISSUE THREAD

**Issue by guday** [wepyjs/wepy#446]
比如，我的项目中，有个文件utils 在providers目录下 （providers与pages同级）

1. 在 pages/main.wpy 中引用 import X from 'providers/utils'

2. 这个路径会被解析成 './../npm/providers/utils.js'

3. 我希望的路径是：'./../providers/utils.js'

看了cli的代码 ，问题在compile-script.js 里面 [https://github.com/wepyjs/wepy/blob/master/packages/wepy-cli/src/compile-script.js](https://github.com/wepyjs/wepy/blob/master/packages/wepy-cli/src/compile-script.js)

1. 源码
```
else { // require('babel-runtime/regenerator')
                let o = resolve.walk(lib);
                source = path.join(o.modulePath, lib);
                target = path.join(npmPath, lib);
                ext = '';
                needCopy = true;
            }
```

2. 改成如下，就ok了

```
 else { // require('babel-runtime/regenerator')
                tmp = 4
                let o = resolve.walk(lib);
                source = path.join(o.modulePath, lib);
                if (type === 'npm') {
                    target = path.join(npmPath, lib);
                    needCopy = true;
                } else {   // 非npm包，不用解析npm路径
                    target = util.getDistPath(source);
                    needCopy = false;
                }
                target = path.join(npmPath, lib);
                ext = '';
            }
```

建议作者看下原因，是改下，还是我改哪里

**Comment by Gcaufy** [comment]
```
import X from './../providers/utils'
```

请使用相对路径

**Comment by guday** [comment]
明白使用相对路径是没问题的。
但是相对路径的可移植性变差。

所以我才使用绝对路径，  看CI中的代码实现，处理绝对路径的逻辑，是有欠缺的。
目前我自己修改本地代码在跑，建议看下这里的优化

**Comment by Gcaufy** [comment]
这里不会处理绝对路径的。
建议参考一些这篇文章：http://www.ruanyifeng.com/blog/2015/05/require.html

**Comment by jingxinxin** [comment]
@Gcaufy 导入第三方包也有这样的问题，要相对到node_modules文件夹吗。。。。给个配置文件来自定义也好吧

**Comment by Gcaufy** [comment]
@jingxinxin node_modules 中的包直接 用 `import xxx from 'xxxx'`
不用相对路径。。
另外，可以用`resolve`选项去设置 node_modules的路径 
自行google`webpack resolve`
