### ISSUE TITLE
unexpected attribute name, near 'data-wp...'

### ISSUE THREAD

**Issue by wulunyi** [wepyjs/wepy#448]
```xml
<view class="minus f-c-c" @tap="modifyCartFromCartPanel({{item.data}}, 'minus')">-</view>
```
这样写就报错了，发现把 modifyCartFromCartPanel 改为 aa 就顺利通过

**Comment by wulunyi** [comment]
改成 mdCartFromCartPanel 也可以是不是名字长度问题啊

**Comment by Gcaufy** [comment]
这个是小程序报错不是编译工具报错是吧？
参数会被编译进data-wpy-中。所以不要写太长的function name。
这里我后面看看是否可以在编译的时候给他加一个Warning吧

**Comment by wulunyi** [comment]
好的，这个确实是小程序的报错

**Comment by MinJieLiu** [comment]
实测：1.5.8版本正常，升级到1.6.0，就报错了
