### ISSUE TITLE
error  'wx' is not defined  defined

### ISSUE THREAD

**Issue by crazykay** [wepyjs/wepy#451]
在使用createSelectorQuery等wepy还没有封装的原生小程序api, 推荐使用wx直接调用, 但是build的时候一直报错让人很不舒服啊,怎么在wepy里面使用wx呢?

**Comment by Gcaufy** [comment]
你说的是eslint报错吧。禁用eslint或者给eslint加上全局变量`wx`

**Comment by Chaunjie** [comment]
怎么加全局变量wx @Gcaufy

**Comment by crazykay** [comment]
@Chaunjie 在.eslintrc.js 加入
 `  globals: {
    wx: true
  },`

**Comment by Chaunjie** [comment]
@crazykay 谢谢

**Comment by zhuyiif** [comment]
谢谢，需要重新 watch下，不是realtime 的

**Comment by zhou1992zg** [comment]
问题还是没有解决！

**Comment by LxHubei** [comment]
加了后工程重启就行了。
