### ISSUE TITLE
config.resolve.alias 没有用  ，   报错

### ISSUE THREAD

**Issue by githbq** [wepyjs/wepy#452]
wepy.config.js 配置
module.exports = {
resolve: {
alias: {
'@': path.join(__dirname, 'src')
},
},

使用的时候 import Panel from '@/components/panel'
一直在报错，
[Error] 找不到组件：@/components/panel
我很好奇, 这么明显 的问题，难道从来没有人发现，难道是wepy根本就没有人用？
作者凭什么说自己已经支持 还说与 wepack resolve-alias 功能一致，连最基本运行都是错的
还有 既然打算做这个功能，为什么不直接在最新版直接给一个指向src的别名，然后写在介绍里，
这种需求是每一个项目都必需的好吧，
完全要使用者自己来配不说，还找不到任何相关文档，只能查看源码

**Comment by githbq** [comment]
看了作者写的用例, 要挨个针对 每一个 库作别名，而不支持 使用 @ 或 其他字符 作为 import时的路径前缀，
这么重要的功能，都没做出来。为何要说自己已经实现了，与webpack.resolve.alias 一样的功能呢

**Comment by looch** [comment]
其实正确的打开方式，应该是封装webpack或者直接做成一个webpack的插件。心好累

**Comment by wulunyi** [comment]
@ 符号与私有库文件的引用会有冲突吧

**Comment by Gcaufy** [comment]
```
npm install wepy-cli@1.5.9-6 -g
```
重试一下看看

**Comment by Gcaufy** [comment]
首先，感谢发现问题并且提ISSUE，这里我都会在第一时间去修复问题。
其次，resolve/alias并非正式版本的功能，1.5.9中才加入，因此并没有写进文档，这个功能只在内部讨论群里有说过，如果一定要用体验版的内容那只能自己踩坑了。
另外，作者并没有义务要去满足任何一个人的喜好，开发者也没有义务一定要使用我的东西去写小程序。喜欢就用，不喜欢别用。请尊重一下开源，也请尊重一下作者的劳动。

**Comment by Gcaufy** [comment]
@githbq 还有问题吗？

**Comment by githbq** [comment]
更新后正常了，确实好用了，谢谢

**Comment by Gcaufy** [comment]
已经加入到template中了，开发者需要就自己用。
