### ISSUE TITLE
使用 wepy-cli 1.5.9-5 发现事件出现问题

### ISSUE THREAD

**Issue by wulunyi** [wepyjs/wepy#454]
使用 wepy-cli 1.5.9-5 
老项目中写的子组件用到了 @tag.stop = bannerTap({{item}) 的事件绑定写法 使用 这个版本编译后
在 bannerTap 方法中获取到的item 值为 event 的值

**Comment by Gcaufy** [comment]
看看编译成的xml的相关的内容。

**Comment by xwxtwd** [comment]
一样的问题   1.5.9-6

**Comment by xwxtwd** [comment]
1.5.9-4编译data-wepy-params-a的参数，到了1.5.9-6data-wpy[函数名]-a

@Gcaufy

**Comment by Gcaufy** [comment]
抱歉，1.5.9-6的新版本事件依赖于新版本的wepy库，我稍后统一更新一下版本。
