### ISSUE TITLE
wepy 上有事件的捕获阶段吗?

### ISSUE THREAD

**Issue by bearRoe** [wepyjs/wepy#457]
原生的小程序文档有，但套用上去没有效果。而且只能使用事件修饰符（@）才能触发到方法，用原生的bind触发不了方法

**Comment by jimmyrogue** [comment]
catchtouchmove="xxx" 我这样就可以捕获到。

**Comment by bearRoe** [comment]
还是不行

**Comment by Gcaufy** [comment]
https://wepyjs.github.io/wepy/#/?id=%e7%bb%84%e4%bb%b6%e8%87%aa%e5%ae%9a%e4%b9%89%e4%ba%8b%e4%bb%b6

**Comment by bearRoe** [comment]
ok， 我使用.stop重新启动微信的开发者工具又可以。。。
