### ISSUE TITLE
能否使用react？

### ISSUE THREAD

**Issue by zzr7** [wepyjs/wepy#461]
大家有没有用过的，可否给予相关demo？  谢谢啦 🙏

**Comment by Gcaufy** [comment]
可以使用redux，不能使用react

**Comment by zzr7** [comment]
谢谢你，我刚才仔细阅读了文档，抱歉提出了这么弱的问题。非常棒的框架。谢谢你作出的伟大贡献。
----- 原始邮件 -----
发件人：Gcaufy <notifications@github.com>
收件人：wepyjs/wepy <wepy@noreply.github.com>
抄送人：黄小辰 <lepin@vip.sina.com>, Author <author@noreply.github.com>
主题：Re:_[wepyjs/wepy]_能否使用react？_(#461)
日期：2017年10月24日 11点14分

可以使用redux，不能使用react

&mdash;

**Comment by skyFi** [comment]
wepy亲民VUE，如果喜欢React风格的话，可以 goto: https://github.com/skyFi/weapp-native
