### ISSUE TITLE
关于引入scss文件的问题

### ISSUE THREAD

**Issue by xing00** [wepyjs/wepy#465]
在wpy文件中引入一个scss文件，然后wepy build --no-cache，之后修改这个scss文件的内容，样式不会更新，如果是修改wpy文件的css内容，样式可以正常更新，请问一下这个问题怎么解决？

**Comment by Gcaufy** [comment]
![image](https://user-images.githubusercontent.com/2182004/31984843-86e69f56-b995-11e7-8817-1894af670aaa.png)

亲测可行。

**Comment by xing00** [comment]
@Gcaufy 我新建了一个新项目，还是不行，wepy-cli是1.5.8的，引入是有效的，修改了控制台也有相关编译的信息，就是没效果。换成sass试试？
![2017-10-25 3 17 38](https://user-images.githubusercontent.com/7943928/31985563-1fe2a6ee-b998-11e7-92b8-21478769e7d2.png)
![2017-10-25 3 17 33](https://user-images.githubusercontent.com/7943928/31985564-2015d1c2-b998-11e7-92e6-40c41b0feb13.png)
![2017-10-25 3 17 28](https://user-images.githubusercontent.com/7943928/31985565-206ff832-b998-11e7-9fa7-c047bf899c79.png)

**Comment by Gcaufy** [comment]
`@import`语法是不会编译父文件的，建议使用src属性，
后面我再考虑一下这里的策略是否要调整一下。

**Comment by xing00** [comment]
好的，明白了
