### ISSUE TITLE
使用setData设值无效

### ISSUE THREAD

**Issue by fireflylight66** [wepyjs/wepy#469]
```javascript
// view
{{count}}

// js
data = {count:0}
onLoad(){
// 这里修改count没有效果 
this.setData({
  count: 11
});
}
```

请问是哪里需要设置吗? 我看其他人有在wepy项目中使用setData方法
因为wxParse中有调用这个方法设值

**Comment by aim-leo** [comment]
控制台打印this,是没有setData方法的，这个方法是wx的。令我比较困惑的是,在回调里面设置data的值，居然不能检测到更改。
![image](https://user-images.githubusercontent.com/26627341/32530741-7d7e773e-c405-11e7-9cfd-4681e26cb571.png)
控制台的数据改了，但是不管是视图还是watch，都检测不到数据变动。

**Comment by Gcaufy** [comment]
```
// view
{{count}}

// js
data = {count:0}
onLoad(){
   this.count++;
}
```

**Comment by fireflylight66** [comment]
谢谢 我知道直接赋值可以修改数据  这表示setData不能够使用了吗?
