### ISSUE TITLE
app.wepy onLaunch 无法访问 $wxapp对象

### ISSUE THREAD

**Issue by githbq** [wepyjs/wepy#472]
```js
export default class extends wepy.page {
onLaunch(){
 this.$wxapp // undefined   这真的合理吗
}
}
```
在原生小程序里，可以直接在 onLaunch 中使用 this即可访问 app对象
为什么不暴露出这个this出来

**Comment by githbq** [comment]
找到原因了
```js
  APP_EVENT.forEach(function (v) {
            config[v] = function () {
                for (var _len2 = arguments.length, args = Array(_len2), _key2 = 0; _key2 < _len2; _key2++) {
                    args[_key2] = arguments[_key2];
                }

                var rst = void 0;
                app[v] && (rst = app[v].apply(app, args));
                return rst;
            };
        });
```
作者在 对 onLaunch 方法进行了一个 apply 转换了this 为wepy自己的this ，
但是却错误的使用了  getApp 方法进行获取   $wxapp 要知道 onLanuch 的事件执行的时候 
微信小程序 的app对象还没有生成出来 自然拿到的 this.$wxapp 必然是一个undefined 对象 
这样是不是很不合理 应该使用原生的 onLaunch方法中  this进行二次封装再 转换这个 this.$wxapp 
而不是在onLanuch方法调用 getApp() 这是作者一个很明显的失误

**Comment by Gcaufy** [comment]
1. wepy的app/page中的this是wepy的this，和原生小程序的不是一码事，在wepy中统计不用原生this
2. 访问原生app的this没有任何意义，故不会暴露出来
3. onLauch中的this.$wxapp返回undefined是因为在onLauch时并不能用getApp()获取原生app对象
4. $wxapp真正的赋值是在page.onLoad事件中，请参考base.js@$createPage
5. 有问题欢迎PR。

**Comment by githbq** [comment]
3. onLauch中的this.$wxapp返回undefined是因为在onLauch时并不能用getApp()获取原生app对象

这个是不是属于编程失误呢，可以不推荐使用app ，但是 是不是不应该强制 让 onLanuch得不到 app的信息

**Comment by githbq** [comment]
算了，以后不再提出任何 issue ， unstar .

**Comment by scott-leung** [comment]
这哥们有点暴躁啊

**Comment by Gcaufy** [comment]
上面解释得很详细了，在没弄明白之前不要老是否定别人，万一是自己理解错了呢？
ISSUE上报的如果是BUG，我会在第一时间修复，不会浪费时间去争论一些没有意义的事情，因此关闭ISSUE。

另外，谢谢你的unstar。
来回顾你过往提过的一些ISSUES：
https://github.com/wepyjs/wepy/issues?utf8=%E2%9C%93&q=author%3Agithbq%20
我只想说一点，请尊重开源，尊重开源作者。切不要摆出一副“我不是针对你 我是说在座的各位都是辣鸡”的姿态。
