### ISSUE TITLE
在页面获取数据后,以动态传值的方式向组件中传递数据,出现问题

### ISSUE THREAD

**Issue by jayconscious** [wepyjs/wepy#479]
在页面获取数据后,以动态传值的方式向组件中传递数据,
:navbarPer.sync="navbarPer"   组件中可以取到，但是
:navbarPer.sync="modulePer.navbarPer"组件中取不到该值

**Comment by jayconscious** [comment]
如果我在首页获取到一些配置数据,在其他页面也会用到,用什么样的方式更好？设置storage，还是。。。

**Comment by jayconscious** [comment]
如果我在首页获取到一些配置数据,在其他页面也会用到,用什么样的方式更好？设置storage，还是。。。

**Comment by Gcaufy** [comment]
https://wepyjs.github.io/wepy/#/api?id=wepypage-class

preload是目前来说最优雅的一种方式 。

**Comment by zfha** [comment]
@Gcaufy 没有解决问题。如题，希望组件能识别父元素的子元素。。而不是页面。

**Comment by Gcaufy** [comment]
暂时不会修改这个问题，后面可能会修改props的实现机制来解决这个问题。
暂时请用computed去处理类似情况。
