### ISSUE TITLE
wepy build时提示找不到crypto模块

### ISSUE THREAD

**Issue by aben1188** [wepyjs/wepy#481]
wepy从1.5.8升级到1.5.9之后，build时提示找不到crypto模块：

[Error] Error: 找不到模块: crypto
被依赖于: E:\LypData\MyDev\zxq\node_modules\request\lib\helpers.js。
请尝试手动执行 npm install crypto 进行安装。

crypto是node的核心模块，怎么会找不到呢？按照提示npm i crypto也还是不行（实际上提示npm中的crypto已被废弃，建议使用node中的crypto核心模块）。

os为win7 64位，node为8.6，npm为5.3。

**Comment by aben1188** [comment]
测试发现，wepy build --watch不会提示找不到crypto模块，但wepy build --no-cache就会

**Comment by Gcaufy** [comment]
找不到`crypto`模块是因为你在代码中require了某些不能在小程序中使用的模块。

**Comment by aben1188** [comment]
但开发者工具中却并不报错哦，如果是在代码中引用了node环境下才能使用的模块的话，那开发者工具应该会报错。

**Comment by billwing** [comment]
@aben1188  请问这个问题解决没？

**Comment by Gcaufy** [comment]
@billwing 没有理由会在小程序中引用 `crypto` 模块

**Comment by billwing** [comment]
嗯嗯，明白了，应该是服务端做的事情

**Comment by up9cloud** [comment]
@Gcaufy 请问一下，我想引用 `util.format` 不过也是报错，能开放吗？
```js
import { format } from 'util'

...
format('%d秒后重试', this.timeLeft / 1000)
```
