### ISSUE TITLE
求助：playplayBackgroundAudio()安卓 ios 不兼容？

### ISSUE THREAD

**Issue by hellokidder** [wepyjs/wepy#486]
首先，我是个新手如果有什么低级错误请见谅啊
然后
`wepy.playBackgroundAudio({
        dataUrl: self.node.noise,
        title: '123'
      })`
我的程序在ios上能够运行，在安卓播放不了音频，提示音乐文件错误，
查了有关的文档说，因为没有添加 title属性，但是我添加上去以后依然在安卓机上放不出音频，很难受
卡在这个问题已经好几天了

**Comment by hellokidder** [comment]
有用原生的框架写了一遍，发现确实不是框架的问题

**Comment by Gcaufy** [comment]
好的。那就关掉 了
