### ISSUE TITLE
1.6.0版本，事件参数传递问题。当参数为空是，传递的参数为一个_class对象

### ISSUE THREAD

**Issue by railgun20001** [wepyjs/wepy#493]
```
gotoPage (url, index) {
            console.log(index)
            wx.navigateTo({
                url: `${url}?index=${index}`
            })
        },
```
`@tap="gotoPage('/pages/sort')"`
控制台输出 _class {active: true, name: "system", source: e, type: "tap", timeStamp: 1887, …}
以前这种写法是可以的，index是undefined，可以设置gotoPage (url, index=0)，现在不行

`@tap="gotoPage('/pages/sort', '{{iSelect}}')"`
可以正常传参

**Comment by ligan21** [comment]
我也遇到这种情况，请问你是如何解决的？

**Comment by Gcaufy** [comment]
@ligan21 
```
npm install wepy --save
wepy build --no-cache
```
