### ISSUE TITLE
在wepy中的Promise不能使用finally()方法

### ISSUE THREAD

**Issue by khejing** [wepyjs/wepy#495]
请问是否可以让用的promise库是可配置的，这样就可以用bluebird，就可以使用finally()方法了。在小程序开发过程中经常会遇到在发起网络请求时显示一个遮罩，然后不管网络请求成功或失败，都得把遮罩隐藏哈

**Comment by Gcaufy** [comment]
默认使用的是'promise-polyfill'库，你可以自己尝试着替换。

**Comment by milkmeowo** [comment]
@khejing 可以尝试用 `complete` 实现，可以写在拦截器里面，具体实现可以看 [拦截器源码](https://github.com/wepyjs/wepy/blob/master/packages/wepy/src/app.js#L146-L157)

```
import wepy from 'wepy';

export default class extends wepy.app {

    constructor () {
        this.intercept('request', {
            config (p) {
                   // 配置obj
            },
            success (p) {
                // 请求成功,注意小程序所有 HTTP 状态码都返回 200，然后 statusCode 里面才是真正的 状态码，错误拦截可以写在这里
            },
            fail (p) {
                // 这里貌似只能是网络错误了。。。
            },
            complete (p) {
                // 这里把他当 finally 用，关闭你的遮罩层之类的试试
            },
        });
    }
}
```

[拦截器 Api](https://wepyjs.github.io/wepy/#/api)

> intercept(api:String, provider:Object)：使用拦截器对原生API请求进行拦截。

拦截器可以不单只可以拦截 request 呀，基本上小程序能 Promise 的 API 都可以拦截。
除了[这里](https://github.com/wepyjs/wepy/blob/master/packages/wepy/src/app.js#L87-L120)定义的几种情况

1. 自定义的 `noPromiseAPI`: 配置在 [`wepy.config.js` 中 `appConfig` 下的 `noPromiseAPI` ](https://github.com/wepyjs/wepy/blob/master/packages/wepy-cli/templates/template/wepy.config.js#L44)

2. 预设的 [noPromiseMethods](https://github.com/wepyjs/wepy/blob/master/packages/wepy/src/app.js#L87-L109)  方法

3. `on` 开头的所有方法，一般指事件监听 API

4. 方法名包含 `Sync` 的方法： 一般指同步的方法

基本上，如无意外，除了上面 4 种情况，你启用了 promise 之后，其他的 API 都能被拦截

**Comment by Gcaufy** [comment]
@milkmeowo 厉害啊。一些没写在文档中的内容你都能挖出来。

**Comment by wulunyi** [comment]
我通过 async 函数，使用 try catch finally 去做了这样的事

**Comment by khejing** [comment]
@wulunyi 的方法是最适合我的，用拦截器的话，需要在一个全局函数里关闭某个组件方法打开的遮罩，不大适合我的需求哈。谢谢大家了！

**Comment by YUANLIN327** [comment]
@milkmeowo 在success里面如何去call fail的函数然后让promise能够catch到这个error呢?

**Comment by yueban** [comment]
结合 @wulunyi  @khejing 的思路贴一下代码：
```javascript
async fetchData() {
  try {
    this.showloading()
    await requestAPI()
      .then((res) => {
        //do something
      })
      .catch((error) => {
        //catch error
      })
  } finally {
    this.hideLoading()
  }
}
```
