### ISSUE TITLE
不支持对象{...data}?

### ISSUE THREAD

**Issue by iceshu** [wepyjs/wepy#499]
SyntaxError: unknown: Unexpected token (64:24)
  62 |                 if (state && msg) {
  63 |                     wx.requestPayment({
> 64 |                         ...msg,
     |                         ^
  65 |                         'success': function (res) {
  66 |                         },
  67 |                         'fail': function (res) {

**Comment by Gcaufy** [comment]
看看是不是这个问题
https://github.com/wepyjs/wepy/issues/442

**Comment by iceshu** [comment]
多谢 啊
