### ISSUE TITLE
解析 wx:else的bug

### ISSUE THREAD

**Issue by huike1989** [wepyjs/wepy#5]
如图所示:
代码：
![image](https://cloud.githubusercontent.com/assets/7878971/21090117/7880d11e-c078-11e6-8ca7-6696b5554423.png)
控制台出错：
![image](https://cloud.githubusercontent.com/assets/7878971/21090137/8a284488-c078-11e6-8e39-a35b27597850.png)

生成的wxml文件：

![image](https://cloud.githubusercontent.com/assets/7878971/21090152/a7c727e8-c078-11e6-88b4-6b81959504c3.png)

**Comment by huike1989** [comment]
wx:else=""

**Comment by Gcaufy** [comment]
嗯嗯， 这个是已知问题，xmldom 在解析DOM节点时，对于无值的属性解析会报warning，后面再看看能否从代码本身绕过这个问题
暂时请赋空值解决

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy/commit/28ce22fb412654333346469beb6f710105559d62
