### ISSUE TITLE
1.6.0版本xmldom error并终止

### ISSUE THREAD

**Issue by gloye** [wepyjs/wepy#508]
![image](https://user-images.githubusercontent.com/10335322/32478815-ba37bb16-c3c1-11e7-9e82-3a7f3f64e64e.png)
```
[xmldom error]  element parse error: Error: attribute value must after "="
@#[line:undefined,col:undefined]

```
- 项目中使用了pug模板；
- 1.5.8版本也会报错，但是程序会继续执行，可以正常编译。

**Comment by wulunyi** [comment]
不要使用 < 符号，我全部调整为 a - b >= c 这种形式

**Comment by wulunyi** [comment]
也可以用 wxs 去定义判断的方法然后使用
[wxs](https://mp.weixin.qq.com/debug/wxadoc/dev/framework/view/wxs/)
