### ISSUE TITLE
page 的 on 事件，增加拦截器功能。

### ISSUE THREAD

**Issue by shenqihui** [wepyjs/wepy#51]
使用场景：

1、 用户分享页面出去，触发 onShareAppMessage ，api 规定是返回一个 Object ，所以可以在 wepy.page 的 onShareAppMessage 执行返回之后，对 Object 进行二次设置，在进行返回。
貌似这个不适合 promise 。官方 demo 上不支持。

2、其他用户点击，触发动作 onload ，这时候 options 先经过拦截器进行拦截，设置 options ，用设置之后的 options 进行 wepy.page 的 onload 事件的回调，此时可加 promise 。

简单实用场景如上。

希望能开发这个功能。

**Comment by Gcaufy** [comment]
这个功能可以有更简单的实现。

定义基类：
```
exports myPage extends wepy.page {
    onLoad () {
        doSomething()
    }
}
```

页面继承基类。
```
exports index extends myPage {
    onLoad () {
        super.onLoad();
    }
}
```
