### ISSUE TITLE
【建议】wepy的组件化方案探讨

### ISSUE THREAD

**Issue by excaliburhan** [wepyjs/wepy#511]
wepy支持组件化，但是使用起来需要到对应的github仓库clone相应的`*.wpy`文件使用，比较麻烦。

每次新生成项目的时候，1是手动下载组件，如果引用第三方组件多的时候很麻烦；2是手动拷贝原有的目录，这可能会引入并不需要的组件。

基于这个原因，自己撸了一个简单的cli工具 [wepy-com-cli](https://github.com/excaliburhan/wepy-com-cli) ，做的事情是在项目根目录使用`wepycom add 组件名字`，就会下载对应的git仓库代码到本地对应目录，可以做到按需加载组件。

所有组件存放在 [wepy-com-templates](https://github.com/wepy-com-templates) 这个组织中，保重组件库的干净整洁。

这种方式需要整合第三方的wepy组件，如果量级上来的话还是很可观的。目标是一个表单，一个按钮都可以用组件化的形式做。

不知道是否可行？

**Comment by wulunyi** [comment]
我最近也是在这样操作

**Comment by excaliburhan** [comment]
npm install的方式在初始化的时候是不太方便，假设你需要按需安装ui组件，你需要多次执行npm install xxx。

现在的cli工具提供两个主要功能：1是查看所有的组件列表，2是添加组件到本地对应目录，主要想做的事是聚合社区的组件，方便他人使用第三方组件。

**Comment by Gcaufy** [comment]
非常感谢。
推荐使用npm install 的方式去安装组件
组件需要通过NPM进行版本管理的。

使用`wepycom add xxxx`和`npm install xxx`效果是一样的。而且npm资源是有比较规范的版本管理机制。

**Comment by excaliburhan** [comment]
确实npm在版本管理有优势，import的时候也比较清爽，不用写很长的路径。
但是*.wpy中import的相对路径的资源文件，如图片、js、css，就会有问题。

所有的内容都要整到一个wpy文件中，不知道有没有优雅一点的开发方法。

**Comment by wulunyi** [comment]
同问，现在还是想把这些都拆成不同的文件便于维护，不然一个文件代码就好几百行，维护很吃力

**Comment by Gcaufy** [comment]
@excaliburhan JS/CSS、 理论上是没有任何问题的，多个引用模块也会同时被copy至npm目录下，不过图片文件好像的确会出现问题。现在还没有检测引用的图片的机制。

**Comment by excaliburhan** [comment]
@Gcaufy 非常感谢。
支持js和css能满足大部分组件化开发了。
图片可以暂时用base64，就是体积会变大一些。或者使用cdn图片也可以的，就是不如base64干净。
