### ISSUE TITLE
wepy new project不成功

### ISSUE THREAD

**Issue by railgun20001** [wepyjs/wepy#514]
![image](https://user-images.githubusercontent.com/22837283/32540755-949c2a8a-c4a8-11e7-9ac2-d6b6577d66ba.png)

wepy-cli1.6.0
npm 5.5.0
node 8.3.0
如上图所示，一直卡在这里
试过npm cache clean --force并不管用

**Comment by Gcaufy** [comment]
应该是NPM网络不通
你CTRL+C后，把后面的命令复制出来单独运行试试看看。

**Comment by fryg123** [comment]
把NPM安装命令改成“cnpm（https://npm.taobao.org/）”试试，npm国内经常安装失败

**Comment by railgun20001** [comment]
@Gcaufy 可以了，确实是NPM网络不通
