### ISSUE TITLE
component methods 无法在模板内使用

### ISSUE THREAD

**Issue by forfuns** [wepyjs/wepy#516]
点击按钮一直报以下错误：

Cannot read property '0' of undefined;at pages/project_detail page $QasDetail$test function
TypeError: Cannot read property '0' of undefined

**Comment by forfuns** [comment]
```

//模板内使用
<view class="button-wrap">
      <button
        class="button"
        @tap="test()"
      >增加问题</button>
    </view>

<text class="label2">{{numFormat(index,2)}}</text>

//以上两种使用方式都无法执行

methods = {
      navigateTo(url) {
        console.log('url',url);
        wepy.navigateTo({
          url
        });
      },
      toggerDetail(qa){
        // console.log('qa',qa);
        // qa.show = !qa.show;
      },
      test(event){
          console.log('test', event);
      },
      numFormat(num,length){
        let numStr = num + '';
        while(numStr.length<length){
          numStr = '0'+numStr;
        }
        return numStr;
      }

    }
```

**Comment by jasonchou3** [comment]
同问

**Comment by Gcaufy** [comment]
原生小程序都没有办法支持到。

**Comment by jasonchou3** [comment]
能否支持一下wxs？
<wxs src="../component/tools.wxs" module="tools"/>
<text>{{tools.msg}}</text>
会编译成：

<wxs src="../component/tools.wxs" module="tools"/>
 <text>{{$tabbar$calender$tools.msg}}</text>

带上了component名的作用域

**Comment by Gcaufy** [comment]
能给出具体的例子么？

**Comment by jasonchou3** [comment]
代码：
`
<wxs src="../component/tools.wxs" module="tools"/>
<text>{{tools.msg}}</text>
`

会编译成：
`
<wxs src="../component/tools.wxs" module="tools"/>
 <text>{{$tabbar$calender$tools.msg}}</text>
`
带上了component名的作用域

tools.wxs:
`module.exports.msg = 'some msg'
`

**Comment by Gcaufy** [comment]
这个可能暂时需要你使用replace插件去replace一次咯。

暂时没有办法去实现判断这个数据是否是组件数据 。

**Comment by forfuns** [comment]
close了吧
我尝试使用computed去解决，谢谢回答
