### ISSUE TITLE
1.4.3分享任然无法正常使用

### ISSUE THREAD

**Issue by kiner-tang** [wepyjs/wepy#52]
![image](https://cloud.githubusercontent.com/assets/10286961/23339505/2c989412-fc5f-11e6-9fb5-d3bf7b62f202.png)
![image](https://cloud.githubusercontent.com/assets/10286961/23339508/6190b1d6-fc5f-11e6-8593-0bdb4f3a09cc.png)

**Comment by Gcaufy** [comment]
周末提交了一个commit https://github.com/wepyjs/wepy/commit/6ce9561cee9239ca3193ffdbc85bd04445505717 解决了这个问题，可以先手动参考commit修改一下，在下一个版本发布时解决此问题。
