### ISSUE TITLE
建议将后缀名修改为vue原生的  这样就不用用编辑器配置了

### ISSUE THREAD

**Issue by vatezj** [wepyjs/wepy#529]

**Comment by shawerestart** [comment]
wepy不是 vue。只是类似vue的写法。如果模板改成了vue，很容易让人混淆，到时候又会有一堆人来说为什么这样不行那样不行的

**Comment by udbmnm** [comment]
是的，不能改成vue，容易造成混淆，其实可以在wepy new 后面加个参数控制下吧

**Comment by Gcaufy** [comment]
这里不会改成`.vue`
如果你希望使用`.vue`后缀，你可以修改`wepy.config.js`中的`ext`字段

**Comment by vatezj** [comment]
嗯 谢了
