### ISSUE TITLE
ios和android预览模式下， 小程序发送接口请求失败

### ISSUE THREAD

**Issue by YufJi** [wepyjs/wepy#537]
1、开发工具并没有开启压缩代码
2、手机上打开调试模式就正常了
3、我的请求引用的是 async /await
4、程序入口也引入了promisify 

求解    大佬求解

**Comment by YufJi** [comment]
我好像知道了 应该是我小程序配置的接口地址 和 当前项目里调用的地址不一致导致的

**Comment by Gcaufy** [comment]
安全域名
