### ISSUE TITLE
wepy build --watch 热更新问题

### ISSUE THREAD

**Issue by jayconscious** [wepyjs/wepy#541]
如果有较大代码(差不多20~30行)块粘贴过来时，不能更新，必须手动编译一下

**Comment by Gcaufy** [comment]
理论上不存在这种情况

**Comment by jayconscious** [comment]
现在编译的不稳定，会把pages中<script>的内容 build 到 dist 的相应的.wxml中
![image](https://user-images.githubusercontent.com/29750917/32929689-c2b3d9e8-cb94-11e7-9cb9-a93b33471d53.png)

**Comment by Gcaufy** [comment]
看看是不是哪里标签没有闭合还是什么情况 ？
可以尝试使用new出来的demo去build看是否存在这种情况

**Comment by jayconscious** [comment]
找到问题了，缺失了一个闭合标签，O(∩_∩)O谢谢
