### ISSUE TITLE
[BUG] pug 模式下@customEvent.user="myFn" 无效

### ISSUE THREAD

**Issue by zaxlct** [wepyjs/wepy#543]
```
<template lang="pug">
  child(@childFn.user="parentFn")
</template>
```
上面代码，子组件 emit 不会触发 parentFn 方法，

```
<template>
    <child @childFn.user="parentFn"></child>
</template>
```
换成这样正常了

 "wepy": "^1.6.0"
微信开发者工具 1.64

**Comment by Gcaufy** [comment]
看一下dist目录下生成的代码，两种情况有什么不同的地方

**Comment by zaxlct** [comment]
`child(@childFn.user="parentFn")`
` <view bindtap="$child$tap">Click me</view>`
@Gcaufy

**Comment by Gcaufy** [comment]
如果要定位这个问题需要做的是，判断一下使用pug和不使用pug
两份dist是有哪里不同，包括JS，wxml
因为如果生成的dist一模一样，那么功能肯定也是一样的。
找到了diff之后才能知道，为什么会生成这个diff

**Comment by zaxlct** [comment]
两份dist产生的 diff 需要我提供下供参考吗？

**Comment by zaxlct** [comment]
又发现了一些 pug 的新 BUG，算了还是老老实实写 html 吧。
不过还是很感谢 wepy，谢谢。
