### ISSUE TITLE
请教下,为什么拿不到值

### ISSUE THREAD

**Issue by CurryHan** [wepyjs/wepy#544]
不好意思 因为没有论坛 就在issue里提了下面这个问题。
```
onReady(){
    var _this=this;
    var system=wepy.getSystemInfo();
    let windowWidth=system.windowWidth;
    _this.imgHeight=(windowWidth-8)/2;
  }
```
wepy.getSystemInfo()返回值 是undefined

**Comment by Gcaufy** [comment]
参考一下：
https://github.com/wepyjs/wepy/wiki/wepy%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8Promise
https://github.com/wepyjs/wepy/wiki/wepy%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8async-await

```
wepy.getSystemInfo().then(res => {this.height = res.height};
```
或者
```
async onReady () {
    let system = await wepy.getSystemInfo();
}
```



要去了解一下Promise和await的基础知识。
如果不熟的话，那建议还是用原生的写法去写吧
```
wx.getSystemInfo({
    success: function (rst) {
        _this.height = rst.height;
    }
})
```

**Comment by CurryHan** [comment]
@Gcaufy  感谢你的回答
