### ISSUE TITLE
在wepy中怎么用Object.assign混入其他的引用声明？

### ISSUE THREAD

**Issue by ChazLun** [wepyjs/wepy#547]
const Tab = require('path/tab/index');

// 在 Page 中混入 Tab 里面声明的方法
Page(Object.assign({}, Tab, {
  // ...
}));

**Comment by Gcaufy** [comment]
没太理解你的意图

**Comment by ChazLun** [comment]
var Zan = require('../../dist/index');

Page(Object.assign({}, Zan.Tab, {
  data: {
    tab1: {
      list: [{
        id: 'all',
        title: '全部'
      }, {
        id: 'topay',
        title: '待付款'
      }, {
        id: 'tosend',
        title: '待发货'
      }, {
        id: 'send',
        title: '待收货'
      }, {
        id: 'sign',
        title: '已完成'
      }],
      selectedId: 'all',
      scroll: false
    }
}
这种在原生中写的Object.assign，我在wepy中去包含data的时候不可以

**Comment by dlhandsome** [comment]
@ChazLun 可以看看mixin
