### ISSUE TITLE
关于class与style的绑定

### ISSUE THREAD

**Issue by sipei97** [wepyjs/wepy#549]
首先，用不了数组
`<view :class="['foods' , {(seller.shop.display_model > 1 ? 'style-single' : 'style-big') : seller.shop.display_model > 0}]">`
编译时
`:class expression is not correct, it has to be {'className': mycondition}`
同时不会生成对应的.wxml文件
其次，不能多重判断
`<view class="foods" :class="{(seller.shop.display_model > 1 ? 'style-single' : 'style-big') : seller.shop.display_model > 0}">`
多重判断编译为
`<view class="foods {{'style-big') : seller.shop.display_model > 0 ? '(seller.shop.display_model > 1 ? 'style-single' : ''}}" >`
内联样式
`<scroll-view class='food' scroll-y="true" scroll-top="{{scrollTop}}" :style="{height: screenHeight + 'px'}">`
这样也是不行的

**Comment by Gcaufy** [comment]
1. `:style`不支持
2. 只支持`{'className': mycondition}`的语法

所以需要写为： 
```
<view class="foods" :class="{'style-single' ?seller.shop.display_model > 1, 'other': othercondition}">
```

**Comment by sipei97** [comment]
谢谢
我用了其它方式，只是想让你知道有这个事。

**Comment by AlingChen** [comment]
@sipei97 你好 内联样式怎么解决的 如果需要绑定动态的样式 怎么解决？

**Comment by sipei97** [comment]
@AlingChen 

#### 不好意思，这个邮箱提醒是在发送到垃圾箱里的，没注意到。
#### 然后我已经很久没用 wepy 了，记不起来了，你可能要自己找找其他人的。

**Comment by Gcaufy** [comment]
```
style="color: {{myCode}}"
```

**Comment by qiuyaofan** [comment]
style="transform:translateY({{translateY}}px);" 但是改变translateY console.info(this.translateY)有变化，但是页面的样式没变化，在wpy输出{{translateY}}也没变化有遇到吗 @Gcaufy
