### ISSUE TITLE
v1.4.4：升级到1.4.4后，wepy -v 显示的版本号还是v1.4.3

### ISSUE THREAD

**Issue by wn7067509** [wepyjs/wepy#55]
<img width="407" alt="2017-02-28 5 41 39" src="https://cloud.githubusercontent.com/assets/16200299/23399984/4ebd2970-fddd-11e6-9a4b-7e47325be800.png">

**Comment by Gcaufy** [comment]
1.4.3是 cli 版本，wepy版本是1.4.4

**Comment by wn7067509** [comment]
噢噢，不过感觉wepy和cli的命令和含义有点容易混淆

**Comment by Gcaufy** [comment]
对的，我应该同时升级一下cli保持版本一致，我的错。
