### ISSUE TITLE
props 双向传值无效

### ISSUE THREAD

**Issue by HP-Ekrn** [wepyjs/wepy#554]
index页面中调用组建mask， status值再mask中变化的时候并没有同步至index中
写法： :status.sync="maskShown"

**Comment by HP-Ekrn** [comment]
在微信开发工具中 是有效的，但是在手机端开发版下运行的时候 就无效了 请问到底咋回事啊

**Comment by Gcaufy** [comment]
未关压缩上传代码

**Comment by HP-Ekrn** [comment]
@Gcaufy 咋关呢 上线后会是正常的吗

**Comment by Gcaufy** [comment]
看文档，或者搜索ISSUE, 有说明这个问题， 这个问题很多人都有问到
