### ISSUE TITLE
onLoad事件调用多次

### ISSUE THREAD

**Issue by yinpinghui** [wepyjs/wepy#57]
page1
```
<template>
    <view class="container">
    <navigator url="/pages/page2" open-type="navigate">
          <view>go to page2</view>
    </navigator>
    </view>
</template>
<script>
    import wepy from 'wepy';
    export default class Index extends wepy.page {
    	onLoad(){
    		console.log("page 1 onLoad occur")
    	}
    }
</script>

```
page2 
```

<template>
    <view class="container">
    <navigator url="/pages/page1" open-type="navigate">
          <view >go to page1</view>
    </navigator>
    </view>
</template>
<script>
    import wepy from 'wepy';
    export default class Index extends wepy.page {
        onLoad(){
            console.log("page 2 onLoad occur")
        }
    }
</script>
```

点几次之后就会出现

should not change the protected attribute __wxWebviewId__

另外open_type如果是navigate的时候，只能点击几次，则无法进行下去了

**Comment by Gcaufy** [comment]
用你的代码测试过，并没有出现onLoad事件调多次的情况。
另外只能点击几次，则无法进行下去了是因为小程序默认只能打开5个页面，这一点小小程序文档中有提到过：https://mp.weixin.qq.com/debug/wxadoc/dev/api/ui-navigate.html#wxnavigatetoobject

**Comment by yinpinghui** [comment]
我之前在我的代码里面进行测试，发现这个问题，为了严谨性，我单独起了一个项目，用cli建立了一个新的项目，用开发者工具进行测试，并在iphone6ps打开console也测试了，都会出现onload多次加载的情况。
5个页面的事情是我的失误，这个不是问题。

为了保证重现，我也不从Page1->page2->page1,而是page1->page2->back->page2->back这样测试，还是重新两个warning，我需要整个代码都提交一下？

**Comment by Gcaufy** [comment]
参照你的测试步骤在开发者工具还原，并没有发现有任何问题，以下是还原步骤和输出：

```
进入page1: 
page 1 onLoad occur

go to page2: 
page 2 onLoad occur

back:
// nothing

go to page2:
should not change the protected attribute __wxWebviewId__
should not change the protected attribute __route__
page 2 onLoad occur

back:
//nothing


```

**Comment by yinpinghui** [comment]
en ,对，问题的焦点就是最后的page2 onload occur是不应该出现的，我们看生命周期的第三行
```
A	B（再次打开）	A.onHide(), B.onShow()
```
当再次打开的时候，onload是不应该再次发生的

**Comment by Gcaufy** [comment]
back的时间会关闭 page2，所以再次再进page2时会触发 onload

**Comment by yinpinghui** [comment]
sorry, my bad, 还真是我的意识错误，我在原生的做了一次测试，发现的确如此

sorry bother u
