### ISSUE TITLE
wepy项目中使用Promise的问题

### ISSUE THREAD

**Issue by zenggo** [wepyjs/wepy#571]
wiki中的用法是：
```
npm install promise-polyfill --save
import Promise from 'promise-polyfill';
...
this.use('promisify');
```
但是在某些环境下promisify无效
观察wepy/app.js执行promisify的过程中，引用的是全局的Promise:
```
// wepy/app.js // version: up to date
// 150行
 return Promise.reject('aborted by interceptor');
// 166行
 const p = new Promise((resolve, reject) => { ...
```
再观察`promise-folyfill`：
```
// v 6.0.2
// promise-polyfill/promise.js
(function(root){
...
// 225行起
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = Promise;
  } else if (!root.Promise) {
    root.Promise = Promise;
  }
})(this);
```
Promise对象并没有被挂到全局上
这两点导致在某些没有自带全局Promise的环境下promisify失败，我目前的解决方案是在`wepy/app.js`中加一行`import Promise from 'promise-polyfill'`

**Comment by Gcaufy** [comment]
参考这个：
https://github.com/wepyjs/wepy/wiki/wepy%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8async-await

**Comment by zenggo** [comment]
ok了，建议更新下 https://github.com/Tencent/wepy/wiki/wepy%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8Promise 这个wiki
