### ISSUE TITLE
动态传值是指父组件向子组件传递动态数据内容，父子组件数据完全独立互补干扰。

### ISSUE THREAD

**Issue by Es201n** [wepyjs/wepy#573]
动态传值是指父组件向子组件传递动态数据内容，父子组件数据完全独立互补干扰。
这里 “互补干扰” 是不是写错字了？ "互补干扰"=>"互不干扰"？

**Comment by Gcaufy** [comment]
感谢指出问题，印象中这个问题应该已被 @aben1188  修复
