### ISSUE TITLE
自定义组件传值报错，unexpected attribute name, near `.once`

### ISSUE THREAD

**Issue by yue-yue** [wepyjs/wepy#574]
自定义一个组件ArticleDetail
![image](https://user-images.githubusercontent.com/13928133/33239922-c8155178-d2e7-11e7-9e7e-74d7d0e9cc5b.png)

ArticleDetailSwiper引用组件时，报错
![image](https://user-images.githubusercontent.com/13928133/33239921-c5a34d6e-d2e7-11e7-9033-2637f5d48470.png)
![image](https://user-images.githubusercontent.com/13928133/33239932-ef65891e-d2e7-11e7-9947-3c59208e8c61.png)

![image](https://user-images.githubusercontent.com/13928133/33239923-cc06aa8e-d2e7-11e7-9805-3cd9ff98c091.png)

**Comment by Gcaufy** [comment]
`articleDateil` or `articleDetail` ?

**Comment by liusome** [comment]
![Uploading 11111111111111.png…]()

没写错也报这个错。

**Comment by Gcaufy** [comment]
@liusome 
key 改成小写试试， 原因就是组件未被编译

**Comment by liusome** [comment]
@Gcaufy 
![image](https://user-images.githubusercontent.com/13285305/33758880-305417cc-dc3b-11e7-99d8-2a3eae36c06b.png)
这样吗？ 不行哦

**Comment by Gcaufy** [comment]
components 里改成小写了么？

**Comment by liusome** [comment]
@Gcaufy 改了的
![image](https://user-images.githubusercontent.com/13285305/33758991-8ef9b43a-dc3b-11e7-89a0-9efe439d6061.png)

**Comment by Gcaufy** [comment]
看看是不是编译报错了，看看dist里面的文件看看为什么 没有被编译。

**Comment by liusome** [comment]
![image](https://user-images.githubusercontent.com/13285305/33759058-de236ea2-dc3b-11e7-8d17-d02e5c4928c0.png)
有个这个 报错 @Gcaufy

**Comment by Gcaufy** [comment]
语法报错，你再多排查一下问题吧。

**Comment by wangyao92** [comment]
兄弟啊，这个问题最后解决了没  我也报这个错了

**Comment by Gcaufy** [comment]
@wangyao92 他是编译报错了，你看看你是不是也是这个问题。
```
components = {}
```
写成了
```
components: {}
```

**Comment by wangyao92** [comment]
我就是这样components={}写的
![image](https://user-images.githubusercontent.com/21259609/33931032-cedf168e-e029-11e7-89f7-95101fa791ac.png)

**Comment by wangyao92** [comment]
![image](https://user-images.githubusercontent.com/21259609/33931178-30d3b71e-e02a-11e7-9915-b802baac8293.png)

**Comment by wangyao92** [comment]
![image](https://user-images.githubusercontent.com/21259609/33931197-426b7cf0-e02a-11e7-9840-2f03624fb7f7.png)

**Comment by wangyao92** [comment]
![image](https://user-images.githubusercontent.com/21259609/33931228-58e7440a-e02a-11e7-9d76-05406ebcac19.png)
用法应该没什么问题吧。。

**Comment by wangyao92** [comment]
@Gcaufy  兄弟  有建议不

**Comment by Gcaufy** [comment]
一样的问题，编译报错，你要看看编译报的是什么错。

**Comment by AmosXu** [comment]
刚刚也碰到了这个问题，解决了，确保你的自定义便签没有下划线或者驼峰的形式，最好是单个字符，或者全部都是小写的字母就行

**Comment by YardWill** [comment]
@Gcaufy 为什么组件一定要小写，个人觉得这个设定很奇怪，我觉得为了区分自定义组件和原生组件，自定义组件强制采用大写形式才是合理的，这是一个bug？还是贵团队特意设定的？

**Comment by qilovehua** [comment]
我的一直报unexpected attribute name near .sync
最后竟然发现是 import CouponList from '../components/couponList.wpy' 多写了文件后缀
改成import CouponList from '../components/couponList'就好了

**Comment by Ding-Fan** [comment]
我是把一段注释在文件里移了个位置（本来放在自定义组件下面的，移到了自定义组件上面）就好了
🤔

**Comment by gaopengyue** [comment]
把style标签的scoped去掉试试

**Comment by king1903** [comment]
组件传值用:
静态传值 <a  title="{{title}}" />,
动态传值  <a :title.sync="title" />  给title赋值的时候别忘了$apply(),
参数名称是支持驼峰写法的. 子组件props中变量命名可以写成dataList, 父组件使用时可用-分隔,也可以直接驼峰,例如:data-list="{{datas}}" dataList="{{datas}}"是一样的.
