### ISSUE TITLE
【新功能支持】 关于在wepy中使用minui的问题

### ISSUE THREAD

**Issue by jimmyrogue** [wepyjs/wepy#579]
最近在尝试使用minui  https://github.com/meili/minui。
碰到一个问题，他们的组件使用小程序的自定义组件，比方说想唤起一个dialog，使用方法为
```
<template>
  <wxc-dialog class="wxc-dialog" title="我的测试" content="内容"></wxc-dialog>
</template>
<script>
let dialogComponent = this.selectComponent('.wxc-dialog')
dialogComponent && dialogComponent.show();
</script>
```
然而wepy的this中并没有selectComponent之类的方法。
![image](https://ws1.sinaimg.cn/large/006tKfTcgy1flxsp7cy49j31120amn1l.jpg)

如果是min自己的this则可以获得这个方法。
![minui](https://ws1.sinaimg.cn/large/006tKfTcgy1flxskqkuaaj30s807y40u.jpg)

不知能否支持一下？

**Comment by jimmyrogue** [comment]
经过群里大佬指点 
```
this.$wxpage.selectComponent()
```
这样才是正确调用方法

**Comment by 3110160** [comment]
@jimmyrogue this.$wxpage.selectComponent() 也报错

**Comment by jimmyrogue** [comment]
@3110160 https://github.com/jimmyrogue/wepy-X-minui 我写的一个demo 你可以参考一下

**Comment by Gcaufy** [comment]
@jimmyrogue 建议PR到这里
