### ISSUE TITLE
component 中没有写 methods = {} 的话，从其他 component 里无法使用 $invoke 方法

### ISSUE THREAD

**Issue by chaiyixiao** [wepyjs/wepy#59]
例如 comA 有方法 methodA（不放在 methods = {} 里，而放在 onLoad() 同级时）而 comA 的 methods 为空，此时若从 comB 调用 this.$invoke('comA', 'methodA')，会报 undefined 错误。

**Comment by Gcaufy** [comment]
@chaiyixiao 我刚在new 出来的demo测试了一下， index.wpy中:
```
this.$invoke('counter1', 'log', 1, 2, 3);
```
然后在counter.wpy中加入自定义方法:
```
onLoad () {
}
log () {
    console.log(arguments);
}
```

结果打印正确
```
[1, 2, 3]
```

**Comment by chaiyixiao** [comment]
1.4.5 (waiting)

F 修复了组件未定义methods时，使用$invoke报错的BUG。
working on 使用空template报错的BUG。

刚看到CHANGELOG，是以上已知 bug。
