### ISSUE TITLE
async/wait 无法使用,wepy.request 返回的不是一个Promise.

### ISSUE THREAD

**Issue by moersing** [wepyjs/wepy#62]
![image](https://cloud.githubusercontent.com/assets/12471233/23786010/7d19c178-05a5-11e7-9f39-82ca2c715b7c.png)

注：url是可以使用的,只是提issue之前我修改了而已。

**Comment by Gcaufy** [comment]
参看WIKI： https://github.com/wepyjs/wepy/wiki/wepy%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8async-await

**Comment by moersing** [comment]
可以，很6，谢谢。

**Comment by imWildCat** [comment]
@Gcaufy 
```javascript
export default class extends wepy.app {

    constructor () {
        super();
        this.use('promisify');
    }
}
```

建议去掉分号。

**Comment by Gcaufy** [comment]
@imWildCat 对于语法规范，可以自己配置eslint
