### ISSUE TITLE
组件<List :items.sync="foods"/>，父页面执行foods.push(...)时，子组件不更新

### ISSUE THREAD

**Issue by wangzexi** [wepyjs/wepy#63]
观察**微信web开发工具**中的**AppData**发现：
`foods`已经获得新元素，
但`$List$items`还未获得新元素。

如何解决？

尝试发现的不优雅的解决方案：
```
let foods = this.foods;
foods.push(data.food);

this.foods = [];
this.$apply();

this.foods = foods;
this.$apply();
```

**Comment by Gcaufy** [comment]
意思是
```
this.foods.push(data.food);
this.$apply();
```
这样不生效？
理论上不会出现这种情况的，只要数据改变了，在`$apply`的时候就会更新数据。

**Comment by wangzexi** [comment]
对，调用了`this.$apply()`，但显示层不生效。

因为经过我测试：
当`this.foods.push(data.food)`后，
List组件内部的`this.items`此时已经同步了数据，说明`:items.sync="foods"`这里没有问题。

所以我猜测是框架脏数据检查`setData`里的问题。

会不会是因为`this.foods`是数组，脏数据比对时只比较了数组的指针，所以没有更新显示层？
这样的话，就可以解释，使用其它数组交替`$apply`一次就能正常更新显示层的原因了。

**Comment by Gcaufy** [comment]
脏数据检查是进行的值比较，有两份数据:
一份是老的数据`this.data.foods`
另一份是老数据的深拷贝`this.foods`
你在改变`this.foods`后，会与原有的`this.data.foods`比较，所以只要在不手动修改`this.data.foods`的情况下，`$apply`就一定会生效。

**Comment by wangzexi** [comment]
好了，解决办法：
```
this.foods.push(data.food);
this.$com.List.$apply();
```

不过确实很奇怪，
另一个Tab的items就可以正常使用`this.$apply()`更新显示，而这个List则必须在其本身`$apply`。

**Comment by Gcaufy** [comment]
使用`.sync`的方式绑定数据，当父组件的数据改变好，是会自动触发子组件的`$apply`，不会需要手动调用 `this.$com.List.$apply();`， 所以你这里还是有问题。

**Comment by Gcaufy** [comment]
文档中有对`sync`和`twoWay`两个属性有说明

```
console.log(this.$parent.parentTitle); // 60.  --- twoWay为true时，子组件props修改会改变父组件对应的值
console.log(this.syncTitle); // 'p-title-changed' --- 有sync属性的props，当父组件改变时，会影响子组件的值。
```

**Comment by wangzexi** [comment]
👌我再调试调试，找找原因。

**Comment by chaiyixiao** [comment]
@wangzexi 你好，请问你有找到原因吗？我也遇到同样的问题...

**Comment by wangzexi** [comment]
@chaiyixiao 原因依然不清楚。

我觉得对于 List 组件，更好的方法，应该像例程一样由 List 组件提供 `setItems()` `getItems()` `insertItem()` `removeItem()` 方法，在组件的方法内使用 `this.$apply()` 都是有效的。

**Comment by Gcaufy** [comment]
@chaiyixiao 你看一下你的wepy版本。
1.4.7中，修复了使用引用类型作为双向绑定不会触发父组件脏检查的BUG。
