### ISSUE TITLE
删除dist目录后，wepy build --watch 未生成 npm 目录

### ISSUE THREAD

**Issue by liumin1128** [wepyjs/wepy#64]
我删除了dist目录，再编译的时候却没有npm文件夹，就运行不了了

**Comment by Gcaufy** [comment]
npm目录在生成后后生成`.wepycache`文件的，防止在build时，重复build npm目录。
如果人工删除dist目录后，有两个选择可以重复生成npm文件夹。

1. 删除`.wepycache`文件，重新再build
2. 使用`wepy build --no-cache`命令进行完整build。

**Comment by liumin1128** [comment]
明白了，谢谢
