### ISSUE TITLE
v1.4.5初始项目就报错了

### ISSUE THREAD

**Issue by sqaiyan** [wepyjs/wepy#65]
![Uploading QQ图片20170313150909.png…]()
第一次用这个，不知道咋搞 工程默认安装wepy-aysnc-function的，还提示这个错，按照wiki上安装async，node_moduls里面没什么变化 还是之前那个默认的包。

**Comment by Gcaufy** [comment]
看不到报错说明

**Comment by sqaiyan** [comment]
上传图片失败，晕死。 报1.Cannot set property 'Promise' of undefined
2. '__route__' of undefined;at "pages/index" page lifeCycleMethod onShow function
3.Cannot read property 'setData' of undefined;at "pages/index" page lifeCycleMethod onReady function

我新建空的项目不会报错，

**Comment by Gcaufy** [comment]
确认一下是否关闭`ES6转ES5`

**Comment by sqaiyan** [comment]
ok了，谢谢，之前好过一次，没注意是这个问题，感谢
