### ISSUE TITLE
无接口能优雅地调用其它methods里的方法

### ISSUE THREAD

**Issue by lilac** [wepyjs/wepy#66]
目前，如果要在一个方法里面调用另一个方法，需要使用蹩脚的方法，如
```js
class A extends wepy.page {
  methods = {
    done() {}
    submit() {
       // done something
       let self = this;
       aPromise.then( () => {
          // FIXME: The below looks ugly. Sadly wepy does not provide alternatives.
          self.methods.done.apply(self);
       });
    }
}}
```

看前面的`self.methods.done.apply(self);`不够简洁，可是我看代码和文档都没有能够代替方法。
可否增加一个类似`$invoke`的方法，来调用本模块的其它方法？

**Comment by Gcaufy** [comment]
这里设计与vue不一样，
`methods` 只负责响应页面事件，不被其它方法调用。如果需要一个可调用方法，请写成自定义方法：
```
class A extends wepy.page {
  methods = {
    tapDone() {
        this.done();
    }
    submit() {
       // done something
       aPromise.then( () => {
          // FIXME: The below looks ugly. Sadly wepy does not provide alternatives.
          this.done();
       });
    }
    done() {
    }
}}
```

**Comment by lilac** [comment]
不理解你给的代码，`done`和`tapDone`都在methods下面，为何调用`this.done`而调用`this.tapDone`就不行？

**Comment by Gcaufy** [comment]
把`done`写成自定义方法就行了。
`methods`只负责响应页面事件，如`bindtap`，`bindchange`等事件。这一类事件只允许作小程序的响应事件，不能互相调用。

需要调用的话，就将它写成自定义方法，就像我上面的示例代码一样。

**Comment by lilac** [comment]
我又试了几种方法。原来你指的自定义方法是写在methods外面的方法，而不是如你给的代码`done`写在`methods`对象里面。
谢谢！

**Comment by lzl124631x** [comment]
> 这里设计与vue不一样，是有意设计成这样的。
methods 只负责响应页面事件，不被其它方法调用。

为什么设计成这样? 有必要么? @Gcaufy
