### ISSUE TITLE
import会生成冗余的文件

### ISSUE THREAD

**Issue by moersing** [wepyjs/wepy#69]
1. 在app.wepy 下 import static文件夹下的index.scss，index.scss修改的时候app.wxss不能同步?

**Comment by Gcaufy** [comment]
理论上可以的，以前测过，看看是不是路径不对？

**Comment by moersing** [comment]
@Gcaufy  我测试过，确实有这个问题，另外，我看了compile-style的源码，它只会在启动时解析css然后writefile，才会出现这种问题，另外，由于微信内置支持`@import` 语法，而compile是writefile，这可能造成文件冗余，是否能够直接将`@import xxx.scss=> @import xxx.wxss` ? 这样的实现可能会相对简单，你觉得呢？

**Comment by Gcaufy** [comment]
看错了你的问题，如果是你用的是`@import`那么是不会编译的。因为小程序本身就支持`@import` 不需要重新编译`app.wpy`只需要编译`static/index.scss`本身就行了。所以你在`app.wpy`中需要import编译后的样式文件`@import static/index.wxss`

这里你还可以使用外链的形式，如下：
```
// app.wpy
<style src="./static/index.scss" lang="scss"></style>
```
然后修改`statis/index.scss`时就会触发`app.wpy`的更新
```
[09:41:16] [变更] 文件: src\pages\index.scss
[09:41:16] [编译] 页面: src\pages\index.wpy
[09:41:16] [写入] 配置: dist\pages\index.json
[09:41:16] [写入] WXML: dist\pages\index.wxml
[09:41:16] [写入] JS  : dist\pages\index.js
```

**Comment by moersing** [comment]
可能是我之前没有描述清楚,上几张图吧: 
1. 这是`app.wpy` 
![56c4068a-45b5-40d0-a4aa-e44798c1da9a](https://cloud.githubusercontent.com/assets/12471233/23978571/c3147b4e-0a2f-11e7-8319-dd43ac26fc72.png)
2.这是`statics/index.scss`
![a3c084d4-d938-4992-bb48-77e943e0459a](https://cloud.githubusercontent.com/assets/12471233/23978578/cd4f93b4-0a2f-11e7-94e2-470570aa8255.png)
3.这是生成的`app.wxss`
![af49b035-daab-4142-a399-e1cb37719a76](https://cloud.githubusercontent.com/assets/12471233/23978574/c9849dec-0a2f-11e7-9a28-1c792abc8a98.png)
4.这是修改`statics/index.scss`之后的运行结果
![8ce17570-1ab0-46f6-8359-e12993b55ead](https://cloud.githubusercontent.com/assets/12471233/23978582/d0368790-0a2f-11e7-8012-0ec26f1444b8.png)

PS: 在第二张图中, index.scss 和 app.wpy 的样式是合并在一起了，所以，index.scss改变，并不会rewrite到 app.wpy中。

**Comment by Gcaufy** [comment]
明白你的意思，index.wxss的确是冗余的文件咯。后面看一下这里是否有优化的空间。

**Comment by moersing** [comment]
嗯嗯，如果有时间，我看看尝试修复一下这个问题.
