### ISSUE TITLE
页面退出后组建数据没消失

### ISSUE THREAD

**Issue by BEIBEI123** [wepyjs/wepy#74]
我有一个考试页面，页面里面引入了做题组建、计时组建，当我退出该套试卷刚进入另外一套试卷时，还能看到前一套时间的题目内容，直到新试卷题目从服务器加载过来，计时器的暂停和继续也无法正常使用（第一次进入页面时计时器的暂停和继续是正常的）

**Comment by Gcaufy** [comment]
小程序与H5不一样，H5中在进行页面切换时页面上的定时器，js内存数据也会随之丢失。但小程序中视图层和逻辑层是分离的，不管你页面怎么切，逻辑层中内存的数据不会丢失。因此需要通过页面的`onUnload`事件去手动将逻辑层中的内存数据清空。

**Comment by BEIBEI123** [comment]
好的，谢谢，完美解决了
