### ISSUE TITLE
页面加载异步获取数据，子组件通过props拿不到值

### ISSUE THREAD

**Issue by CommanderXL** [wepyjs/wepy#81]
父组件数据如果不是通过异步获取的，而是直接在`data`属性里面定义好了，然后通过`props`传递给子组件的时候，子组件是可以通过`props`去获取相对应的属性值。

但如果数据是异步获取的，然后通过`props`去传递相应的数据到子组件中，拿不到对应的属性值。我看`demo`中的写法是通过在父组件中掉子组件的异步的方法，再去渲染子组件。

另外就是`props`的数据类型定义: 父组件传递一个`Array`类型的数据，子组件相对应的属性存在一个问题：

```javascript
    父组件:
    <template>
        <sub :list="list">
    <template>
    
    <script>
        export default class Super from wepy.page {
            data = {
                list: [
                    {
                        name: '小红'
                    },
                    {
                        name: '小兰'
                    }
                ]
            }
        }
    </script>
    
    子组件:
    
    <script>
        export default class Sub from wepy.component {
            props = {
                list: {}  //  正常,能拿到数据
                list: []  //  打印出来为undefined
                list: {
                    type: Array  // 会报错.
                    type: Object   //  正常
                }
            }
        }
    </script>
```

**Comment by Gcaufy** [comment]
1. 第一个问题， 父组件数据如果不是通过异步获取的，`sub :list="list">` 为静态传值，父组件的数据改变后子组件的数据不会改变。如果希望父组件的数据异步改变后同步到子组件，则需要``sub :list.sync="list">``

2. 第二个问题。props定义时只提供 props = Object 或者 props = String 两种写法，并不存在 props = Array的写法。所以`list: {}`，`list:{type:Object}`都是合理的，`list: []`为不合理声明，后面可以优化一下。`list:{type:Array}`理论上也不应该报错。

**Comment by CommanderXL** [comment]
👏

**Comment by delayhsiao** [comment]
@Gcaufy  骗纸啊，试了根本不行啊，父组件里面异步获取的数据，子组件里根本得不到更新啊，加了.sync也没用

**Comment by Gcaufy** [comment]
@delayhsiao 贴关键代码看看

**Comment by zhang-xiao** [comment]
遇到了同样的问题，在开发者工具里是可以通过sync来让父组件更新子组件的，可是在真机上不行。。。

**Comment by zhang-xiao** [comment]
@Gcaufy 还真是踩了个坑。。。。可以在文档中提个醒，或者大神看看这个问题是怎么引起的。。。

是这样的，如果真机预览的时候开启了 代码压缩上传 的功能，那个sync在组件首次初始化的时候是不起作用的，遇到同样问题的同学记得把这个功能关掉就好了。

**Comment by dyq086** [comment]
那发布的时候岂不是代码没有压缩了？

**Comment by Gcaufy** [comment]
```
npm run build
```

**Comment by littleQing** [comment]
@Zhang Xiao  关闭了代码压缩果然就好了（一脸懵逼（~.~）加惆怅），那发布的时候呢？不压缩
