### ISSUE TITLE
ESLint提示wx未被定义

### ISSUE THREAD

**Issue by delayhsiao** [wepyjs/wepy#84]
在wepy中使用小程序的wx方法会报错
比如wx.login()这样的
但是用wepy.getUserInfo()会拿不到数据，求解

**Comment by Gcaufy** [comment]
@dolymood

**Comment by neurotoxinvx** [comment]
两种解决方式：
1、在你调用 wx.login 的代码上一行书写 `/* eslint-disable no-undef */` 让 eslint 忽略下方的 no-undef 错误
2、`let wx = window.wx` 声明变量保存 jssdk 引入的 window.wx

不过我觉得还是应该关注一下为什么 wepy.getUserInfo 会拿不到用户信息，请问你是否申请了 appid ？

**Comment by Gcaufy** [comment]
@neurotoxinvx :+1:

**Comment by Gcaufy** [comment]
在wechat-demo中也是用了`wepy.getUserInfo` ，我用自己的appid在手机上预览是没有问题的。

**Comment by Gcaufy** [comment]
@delayhsiao 在`.eslintrc.js`中加入
```
  'globals': {
      'wx': true
  },
```

**Comment by delayhsiao** [comment]
@neurotoxinvx appid不申请还怎么在微信开发者工具里面创建项目（手动抱拳）
关键是如果用wx.getUserInfo是可以拿到用户信息的，但是wepy.getUserInfo就拿不到，也不是一直拿不到，new project之后首次运行是可以拿到的，过了一阵子就拿不到了，清除用户授权信息之后再重新编译调试还是不行，我也很绝望。最后直接wx.getUserInfo……

**Comment by Gcaufy** [comment]
@delayhsiao 
我这边测试并没有发现拉不到用户信息的情况 。
使用wehcat-demo测试看看是否存在拿不到用户信息的情况

**Comment by delayhsiao** [comment]
@Gcaufy 我这边基本上一开始都是拉得到用户的，只是一直开着过了很长时间后，不知道是授权掉了还是怎么的就拉不到数据了。重新登录也不行，只要换回Wx就能获取到，然后再改成wepy也能了，很郁闷

**Comment by Gcaufy** [comment]
@delayhsiao 那只能断点调试看看咯。

**Comment by luogao** [comment]
似乎遇到了相同的问题，我在使用`wepy.getUserInfo` 和 `wepy.getSetting`都遇到类似没有返回数据的情况，但是换成`wx.getUserInfo`和`wx.getSetting` 就有数据返回了
