### ISSUE TITLE
循环子组件里的事件影响其他子组件

### ISSUE THREAD

**Issue by willove** [wepyjs/wepy#87]
现在有一个答题模块，在主页面里面用列表循环了一批题目和ABCD的选项，选项内容写在了子组件的data里面，通过radio的change事件进行对data选项内容进行更改，然后this.$apply()提交。但是这一步就会造成在对某一个题目进行勾选时页面其他题目同样的选项也会被勾选，按照理想状态这个数据作用域应该在被循环的子组件里面，只会影响我勾选的那一个组件，相同的其他组件不会被事件影响到。

**Comment by Gcaufy** [comment]
有简单的demo代码说明么？
