### ISSUE TITLE
wepy new demo时能否不要执行npm install 命令？

### ISSUE THREAD

**Issue by yunhor** [wepyjs/wepy#88]
用wepy-cli new project时，最后总是要等 npm install 好长时间，原因你懂的。
能否不要执行这个npm install ? 让我们可以自行用cnpm 或是其它比较快的安装。
谢谢

**Comment by Gcaufy** [comment]
手动cancle， 然后copy命令自己安装。

**Comment by yunhor** [comment]
谢谢 @Gcaufy 
不好意思,我自己不会用npm ,可以配置成 npm config set registry " https://registry.npm.taobao.org "
