### ISSUE TITLE
对第三方 Store 库的支持问题

### ISSUE THREAD

**Issue by jas0ncn** [wepyjs/wepy#89]
我自己写了一个类似于 Vuex 的 Store。
Store 中参考了 Vuex 对 state define 了 getter 和 setter，防止对 state 的直接修改。
然而如果将 Store 绑定到 data 上，Wepy 会对 data 的 getter 进行包装，覆盖掉了原来的 getter，有没有类似 Vue.js 的 plugin api 或者要对 Store 进行怎么样的修改来兼容呢？

Store 我放在 gist 上了：
https://gist.github.com/jas0ncn/541e5ed6f73d049dbf80d2e344cdb7cd

**Comment by dolymood** [comment]
Wepy 应该是不会对data的 getter 进行包装的，倒是会深度克隆一份，有可能是这里的原因。

因为 Wepy 采用的是脏检查机制，所以必须要对data进行深度克隆 然后才可以检查
