### ISSUE TITLE
wx:for组件嵌套传参取不到值

### ISSUE THREAD

**Issue by xiao345** [wepyjs/wepy#9]

**Comment by Gcaufy** [comment]
的确如些，因为props的机制问题导致的。暂时的解决办法就是把wx:for写入到组件内部，后面我再看能否解决这个问题。

**Comment by xiao345** [comment]
什么时候处理？这种需求很常见，希望能尽快处理

**Comment by ykx456654** [comment]
props不能传数组吗？
Cannot set property Symbol(Symbol.species) of function Array() { [native code] } which has only a getter
TypeError: Cannot set property Symbol(Symbol.species) of function Array() { [native code] } which has only a getter

**Comment by Gcaufy** [comment]
@ykx456654 可以传数组的。参考一下wechat-demo

**Comment by Gcaufy** [comment]
在循环中使用组件的示例请参看这里： https://github.com/wepyjs/wepy-wechat-demo/commit/6198df5cc5d91089317be534b6d881ddabe1f05b

**Comment by Songkeys** [comment]
@Gcaufy 
您好，看了一下示例。请问如果用`<repeat>`的话，必须传成 Object 类型吗？
我用 Array 类型也遇到了：
```
jsEnginScriptError
Cannot set property Symbol(Symbol.species) of function Array() { [native code] } which has only a getter
TypeError: Cannot set property Symbol(Symbol.species) of function Array() { [native code] } which has only a getter
```
