### ISSUE TITLE
 wepy build 目录的问题

### ISSUE THREAD

**Issue by yunhor** [wepyjs/wepy#91]
在 gorepos/src 目录下 wepy new wepytest 项目,结果build out 生成的是 在 gorepos/dist/wepytest/src/ 而不是在gorepos/src/wepytest/dist 里(npm目录生成在这里),非常奇怪,如果项目的祖先没有"src"目录,则编译输出正常.

![srcdist](https://cloud.githubusercontent.com/assets/1693437/24833073/09e17fb2-1cf1-11e7-900a-b1ccfc1b23ec.png)
![dist](https://cloud.githubusercontent.com/assets/1693437/24833078/1b021fe0-1cf1-11e7-9029-203cb466265d.png)
![tmp](https://cloud.githubusercontent.com/assets/1693437/24833079/209fb9a8-1cf1-11e7-9654-53565ec87b4c.png)

**Comment by Gcaufy** [comment]
fixed.

**Comment by yunhor** [comment]
谢谢@Gcaufy
