### ISSUE TITLE
建议能增强压缩文件的功能。

### ISSUE THREAD

**Issue by martin-sun** [wepyjs/wepy#94]
当process.env.NODE_ENV为production时， wepy在编译时能开启 对src的 js, css 以及图片的压缩。
建议 
1. 能否也支持对 wxml文件的压缩支持？
2. 能否把生成的dist目录下的npm文件夹下的js文件也自动压缩？

**Comment by Gcaufy** [comment]
以上两个功能都已经支持了

1. https://github.com/wepyjs/wepy/tree/master/packages/wepy-plugin-filemin
2. wepy build --no-cache

**Comment by martin-sun** [comment]
嗯，试过了，非常好，谢谢。
