### ISSUE TITLE
今天发现了一个坑。

### ISSUE THREAD

**Issue by DarrenHou1993** [wepyjs/wepy#96]
![image](https://cloud.githubusercontent.com/assets/9291785/25038509/b885926c-2131-11e7-989e-aec48ea4f13f.png)
这个单词拼错了  导致我老是报错。 刚开始没太注意。打断点发现了。。。

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy/commit/e90cc15aa0e4aa3556858fba38517847c1c9eaf8

**Comment by Gcaufy** [comment]
Sorry，多谢，已修复
