### ISSUE TITLE
async/await中的异常不能被捕获

### ISSUE THREAD

**Issue by princescar** [wepyjs/wepy#97]
`
  onLaunch() {
    try {
      this.boom()
    } catch (err) {
      console.log('CATCH', err)
    }
  }

  boom (s) {
    return new Promise((resolve, reject) => {
      reject(new Error('promise rejected'))
    })
  }
`

catch无法捕获promise rejection, console里显示Possible Unhandled Promise Rejection: Error: promise rejected(…)

#### 版本

-     "wepy": "^1.5.1",
-     "wepy-async-function": "^1.4.4",
-     "wepy-com-toast": "^1.0.2"
-     "babel-eslint": "^7.2.1",
-     "babel-plugin-syntax-export-extensions": "^6.13.0",
-     "babel-plugin-transform-export-extensions": "^6.22.0",
-     "babel-preset-es2015": "^6.24.1",
-     "babel-preset-stage-1": "^6.24.1",
-     "cross-env": "^4.0.0",
-     "eslint": "^3.18.0",
-     "eslint-config-standard": "^7.1.0",
-     "eslint-friendly-formatter": "^2.0.7",
-     "eslint-plugin-html": "^2.0.1",
-     "eslint-plugin-promise": "^3.5.0",
-     "eslint-plugin-standard": "^2.0.1",
-     "wepy-compiler-babel": "^1.5.1",
-     "wepy-compiler-less": "^1.3.10",
-     "wepy-eslint": "^1.5.2",
-     "wepy-plugin-imagemin": "^1.3.7",
-     "wepy-plugin-uglifyjs": "^1.3.6"

**Comment by Gcaufy** [comment]
```
async onLaunch() {
  try {
    await this.boom()
  } catch (err) {
    console.log('CATCH', err)
  }
}
```

**Comment by princescar** [comment]
@Gcaufy的写法可以catch到, 是我自己对async/await的理解不够深刻, 抱歉:-)
