### ISSUE TITLE
增加对 :class 的支持？

### ISSUE THREAD

**Issue by atian25** [wepyjs/wepy#99]
`<view class="weui_panel" :class="{ 'weui_panel_access': access }">`

目前是编译为: `<view class="weui_panel" v-bind:class.once="{ 'weui_panel_access': access }">`

报错：`unexpected attribute name, near .once`

**Comment by Gcaufy** [comment]
好的，可以考虑的功能。

**Comment by atian25** [comment]
PS: 现在有没有 wx-wxss 的 wepy 封装版?

**Comment by Gcaufy** [comment]
暂时没有

**Comment by Gcaufy** [comment]
已发布的1.5.3已经支持上了`:class`
